### ISSUE TITLE
[Feature] armhf support for kubernetes-dashboard app

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#10]
## Feature

There is armhf support for the kubernetes-dashboard, so we should look at adding that for the dashboard because it's super popular with Raspberry Pi users.

https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard

For an example on how to find the architecture, see the [openfaas app](https://github.com/alexellis/arkade/blob/master/cmd/apps/openfaas_app.go)

Here's the dashboard app:

https://github.com/alexellis/arkade/blob/master/cmd/apps/kubernetes_dashboard_app.go

**Comment by Waterdrips** [comment]
/close

This is fixed
