### ISSUE TITLE
Add kube-score

### ISSUE THREAD

**Issue by xamino** [alexellis/arkade#1001]
Include [kube-score](https://github.com/zegl/kube-score) in arkade. This would allow us to use it as part of our CICD pipeline to verify our kubernetes resources via the `arkade-get` Github workflow action.

## Expected Behaviour
Similar to any other tool – `kube-score: latest` would be great, plus support to point it to specific versions.

## Possible Solution
`kube-score` is a Golang program, so statically built, therefore should be comparatively simple to add support for, I hope.

## Context
Currently I have to use a less popular, "random" Github Action to install `kube-score` (because we're migrating from another CI system I want to keep existing functionality). I'd much prefer to be able to use arkade / arkade-get for this since we already found it useful for other tools. :grin: 

## If requesting a CLI for "arkade get"

How many downloads does this tool have? [523,480](https://somsubhra.github.io/github-release-stats/?username=zegl&repository=kube-score&page=1&per_page=5)

If approved, are you willing to submit a pull request for this? Sorry, no, no time currently.

**Comment by alexellis** [comment]
This has been added by @rgee0, thanks @xamino for the suggestion.
