### ISSUE TITLE
Add terraform-docs

### ISSUE THREAD

**Issue by cyberox** [alexellis/arkade#1015]
Include [terraform-docs](https://github.com/terraform-docs/terraform-docs) in arkade. This would allow us to use it as part of our CICD pipeline to verify our terraform resources via the arkade-get Github workflow.

## Expected Behaviour
Similar to any other tool – `terraform-docs: latest` would be great, plus support to point it to specific versions.

## Current Behaviour
Generate documentation from Terraform modules in various output formats, 

## Possible Solution
Add `terraform-docs` to arkade

## Context
We are currently using this tool in our CICD pipeline, so it would be nice to install it the same way as the other tools used in the pipeline.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? 3,126,996
If approved, are you willing to submit a pull request for this? Yes

**Comment by alexellis** [comment]
Please send a PR :+1:

**Comment by cyberox** [comment]
@alexellis the PR is ready

**Comment by cyberox** [comment]
added

**Comment by alexellis** [comment]
Thanks @cyberox
