### ISSUE TITLE
Add tflint

### ISSUE THREAD

**Issue by cyberox** [alexellis/arkade#1016]
Include [tflint](https://github.com/terraform-linters/tflint) in arkade. This would allow us to use it as part of our CICD pipeline to verify our terraform resources via the arkade-get Github workflow.

## Expected Behaviour
Similar to any other tool – `tflint: latest` would be great, plus support to point it to specific versions.

## Current Behaviour
A Pluggable Terraform Linter

## Possible Solution
Add `tflint` to arkade

## Context
We are currently using this tool in our CICD pipeline, so it would be nice to install it the same way as the other tools used in the pipeline.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? 2,335,234
If approved, are you willing to submit a pull request for this? Yes

**Comment by alexellis** [comment]
Please go ahead and send a PR

**Comment by alexellis** [comment]
Great @cyberox
