### ISSUE TITLE
Create arkade docker image

### ISSUE THREAD

**Issue by elyesbenamor** [alexellis/arkade#1017]
## Expected Behaviour
Using docker container to use arkade for containers lovers and fans
## Current Behaviour
The image will be used as follows
`docker run -it --network="host" \
  -v $HOME/.arkade/bin/:$HOME/.arkade/bin/ \
  -v $HOME/.kube:/$HOME/.kube \
  --env KUBECONFIG=${KUBECONFIG:-$HOME/.kube/config} \
  arkade install .....
`
`docker run -it --network="host" \
  -v $HOME/.arkade/bin/:$HOME/.arkade/bin/ \
  -v $HOME/.kube:/$HOME/.kube \
  --env KUBECONFIG=${KUBECONFIG:-$HOME/.kube/config} \
  arkade get ....
`
`docker run -it --network="host" \
  -v $HOME/.arkade/bin/:$HOME/.arkade/bin/ \
  -v $HOME/.kube:/$HOME/.kube \
  --env KUBECONFIG=${KUBECONFIG:-$HOME/.kube/config} \
  arkade system install ....
`
## Details
As a switch user (kube switch ) to manage my kubeconfigs it is better to pass the kubeconfig file as env variable once 
`switch` cli is invoked, else if running one cluster the default will be in the `.kube` folder.'

We also mount the binary folder expected where arrkade will install them in order to persist them locally.
## Done ?

I have implemented the dockerfile and tested it on my environement and you can look at the image on [docker hub](https://hub.docker.com/r/elyes000/arkade).

**Comment by elyesbenamor** [comment]
@alexellis would you be intrested ?

**Comment by alexellis** [comment]
Hi @elyesbenamor I'm not sure that I see the value in complicating arkade.

Can you better explain why this is needed?

**Comment by elyesbenamor** [comment]
@alexellis it is only for local developer who wants to rely on containers and like myself have lots of clusters , once switched using kubeswitch, it is a better way to use an ephemeral container to deploy stuff using ark.

**Comment by alexellis** [comment]
I don't want this for arkade, but if you sponsor me on a 15USD+ tier / mo I'll add it. If you don't want to support my work, you could maintain your own dockerfile triggered with cron every day?

**Comment by alexellis** [comment]
🤷
