### ISSUE TITLE
[Feature Request] Adding Pixie

### ISSUE THREAD

**Issue by ishanmkh** [alexellis/arkade#103]
👋 we recently launched [Pixie's](https://github.com/pixie-labs/pixie) beta with community users spanning both application developers deploying on K8s and SRE/DevOps managing workloads. 

It'd be great if Pixie could be added to the supported list of apps! we're fans and our community would love it as well. 

Pixie is k8s native. It can be installer by running `bash -c "$(curl -fsSL https://withpixie.ai/install.sh)"` could be invoked by ark install. 

Summary of install steps here: https://github.com/pixie-labs/pixie#quick-start

**Comment by alexellis** [comment]
Hi thanks for your suggestion.

I clicked through and read this but I still don't understand what the product does? Can you explain in plain language why I would use this and how much it costs?

> Pixie is an edge intelligence platform to help you debug in minutes and avoid wasting months instrumenting your entire codebase.

**Comment by ishanmkh** [comment]
Sure @alexelli! sorry about the confusing description

You can use Pixie to get performance monitoring data (and dashboards) for your services & workloads without code-level instrumentation.  

It's intended to make troubleshooting production and ci/cd canary workloads faster and easier by giving automatic monitoring coverage.   

Here's a sample of what you'd get out of the box:
- Service level latency, error-rate, rps
- Pod level mem, cpu, iops
- Database views (mysql/psql/cassandra etc.)
- Raw network requests traced using eBPF
- (coming this month) data integrations into Prometheus
- (coming in June) Code level function tracing (stack-traces+variables) for golang and other compiled languages

Pixie is a saas product. Pixie community is free for individual and small teams (github page points to this). Pixie Enterprise is for large teams/enterprises.

Under the hood (ref: [docs](https://docs.withpixie.ai/getting-started/how-pixie-works/)):
- Data collection: pixie deploys daemonsets that collect request traces (http, grpc, mysql, etc) and system metrics (cpu, mem, utli) using eBPF (a VM in the linux kernel)
- Storage & compute: data is processed by Pixie's query engine which sits inside the K8s cluster and is deployed as services. all data remains o
- Interface: Live UI serves automatic dashboards and the `px` CLI allows in-terminal data, tables  & integrations with Prometheus.

**Comment by alexellis** [comment]
Let's keep the issue open for a week or two more to gauge interest from the arkade community.

I'm not sure if you're aware, but there is a generic installation command:

```bash
arkade install chart --help
```

**Comment by ishanmkh** [comment]
sounds good @alexellis. it's a new project with initial community outreach planned in the coming few weeks so we can circle back after that.  thanks!

**Comment by alexellis** [comment]
Thanks, please feel free to report back here, and do take a look at `arkade install chart --help`, you're welcome to use this in your docs.

**Comment by ishanmkh** [comment]
sure @aledbf will add it to our docs!

**Comment by alexellis** [comment]
Hi @ishanmkh, you may be interested in our new [Sponsored Apps](https://github.com/alexellis/arkade#sponsored-apps), have a read and see if it's a good fit for you.

Alex

Btw are you working with @aledbf or did you mean to tag me in the last comment?

**Comment by ishanmkh** [comment]
@alexellis very interested to be a sponsored app. sent an email to figure out details. let's do it! 

btw -added `aledbf` by mistake. was meaning to cc you. corrected.
