### ISSUE TITLE
Add OpenTofu

### ISSUE THREAD

**Issue by rgarrigue** [alexellis/arkade#1039]
## Expected Behaviour

Adding OpenTofu, Terraform community fork https://github.com/opentofu/opentofu

## Current Behaviour

tool not found

## Context

Switching from terraform to opentofu. It's more convenient to try out versions with Arkade.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? 

>  Downloads: 33,888 (Release 1.6.2)

If approved, are you willing to submit a pull request for this?

Yes

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

```
❯ uname -a
Linux XXXXXXX 6.6.19-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Mar  1 18:16:16 UTC 2024 x86_64 GNU/Linux
❯ 
❯ cat /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

* What arkade version is this?

```
arkade version

Version: 0.11.4
Git Commit: 7aefb132a1dc703a6a895cd75c12deb6775459e2
```

**Comment by alexellis** [comment]
Hey @rgarrigue - just so you're aware, we do have a contributing guide, and don't accept PRs unless they're approved by a maintainer.

I'd suggest you take a quick read.

We'll take a look at this request to add OpenTofu in due course.

Alex

**Comment by rgarrigue** [comment]
I saw that, sorry about doing it in the bad order, to begin with I just wanted to see how to add tools, then got started on opentofu... Thanks for considering it 👍🏿

**Comment by alexellis** [comment]
No problems. Thanks for the interest in arkade.

How did you decide to make the PR, are you a user already?

**Comment by rgarrigue** [comment]
I've been using Arkade for a couple of years to replace homemade scripts to install this & that.

And the motivation for the PR, well needed opentofu, want to train Golang, tried, got it working, though I should contribute my tiny bit

**Comment by alexellis** [comment]
Thanks sounds good.

**Comment by alexellis** [comment]
This has been merged and released, so closing the original issue.

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).
