### ISSUE TITLE
[Feature] Update location of nginx-ingress chart

### ISSUE THREAD

**Issue by aledbf** [alexellis/arkade#104]
## Context

Due to the deprecation of the stable chart repository, the nginx-ingress chart is being migrated to 
https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
The installation instructions already use this chart https://kubernetes.github.io/ingress-nginx/deploy/#using-helm

**Note:** the migration introduced breaking changes:
- the chart was renamed to `ingress-nginx` to align the Github repository with the chart name
- a cleanup of labels and switch of defaults
- umbrella issue https://github.com/kubernetes/ingress-nginx/issues/5161

**Comment by pierluigilenoci** [comment]
@alexellis why closed? the migration is done?

**Comment by alexellis** [comment]
Look as the linked PRs, what am I missing?

**Comment by pierluigilenoci** [comment]
I'm sorry, I got confused. It's all right. 😕
