### ISSUE TITLE
e2e tests fails on Test_CheckTools/Download_of_crane

### ISSUE THREAD

**Issue by rgarrigue** [alexellis/arkade#1043]
## Expected Behaviour

make e2e should be successful 

## Current Behaviour

```
❯ make e2e | grep FAIL
fatal : Aucun nom trouvé, impossible de décrire quoi que ce soit.
--- FAIL: Test_CheckTools (0.00s)
    --- FAIL: Test_CheckTools/Download_of_crane (0.34s)
```

## Possible Solution

Haven't investigated

## Steps to Reproduce (for bugs)

`make e2e`

## Context

I was running e2e to check my PR, found this unrelated issue. Not blocking for me.

## Your Environment

```
❯ uname -a
Linux berget 6.6.19-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Mar  1 18:16:16 UTC 2024 x86_64 GNU/Linux
❯ 
❯ cat /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

* What arkade version is this?

master branch, my commit over 7aefb13

**Comment by alexellis** [comment]
Hi @rgarrigue I assume you know how to look into this and are happy to try to fix it?

Perhaps the project changed their download format or paths for one of the Operating Systems. That's where I'd look first.

See what's showing as not found, check their releases page, see if they forgot to attach binaries etc.

**Comment by rgee0** [comment]
Unable to reproduce this locally using 86e0ff5

```
 --- PASS: Test_CheckTools/Download_of_crane (0.98s)
 ```

**Comment by rgarrigue** [comment]
Same, seems like an outage on the download. Sorry for the disturbance.
