### ISSUE TITLE
kubectl CLI is outdated by several versions

### ISSUE THREAD

**Issue by James5979** [alexellis/arkade#1048]
The default version of `kubectl` provided by `arkade get kubectl` should always track the latest version of the binary since Kubernetes uses version skew (i.e. +/- one version).

The binary for `kubectl` downloaded by `arkade` currently gives version `v1.24.2` by default, i.e. when running: `arkade get kubectl`.

Please upgrade the default version to `v1.29.3`.

A nice way to automatically track the latest (stable) version of `kubectl` is to `curl` the following: `curl -L -s https://dl.k8s.io/release/stable.txt`.

If someone wishes to use an older version of `kubectl` with `arkade` then they can specify `arkade get kubectl@TYPE_VERSION_HERE`.

**Comment by James5979** [comment]
`arkade version` output:

...
Version: 0.11.6
Git Commit: acb1bd999ac81840fbbe49f3d1cc1fbd386f7fd4
...

Apologies if you received any email noise from this issue, I accidentally submitted before I had finished writing.

**Comment by alexellis** [comment]
Hi @James5979 are you happy to send a PR to update to the latest version?

We can look separately at the version lookup later.

**Comment by James5979** [comment]
> Hi @James5979 are you happy to send a PR to update to the latest version?

Hi @alexellis,

Thank you for your quick reply.

I would create a PR, but unfortunately I do not know Go. 

If you remember this being something trivial to update then I can always have a look for you.

> We can look separately at the version lookup later.

Nothing major, just a suggestion for the future.

As a workaround, I can always track stable with:

`arkade get kubectl@$(curl -L -s https://dl.k8s.io/release/stable.txt)`

A bit out of context, but I purchased one of your inlets pro personal licenses the other day and it is *amazing*! I have been using the inlets operator and I will definitely update you on how it works out. 🙂

**Comment by rgee0** [comment]
I've proposed a change covering the maintenance side of this
