### ISSUE TITLE
Download script failing due to Squarespace migration - TLS error

### ISSUE THREAD

**Issue by dmytroba-salt** [alexellis/arkade#1056]
See the following log:

```
$ curl -sLS https://get.arkade.dev          
curl: (60) SSL: no alternative certificate subject name matches target host name 'get.arkade.dev'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

## Expected Behaviour

`curl -sLS https://get.arkade.dev` succeeds.

## Current Behaviour

`curl -sLS https://get.arkade.dev` fails.

**Comment by sthomson-wyn** [comment]
@alexellis 
![image](https://github.com/alexellis/arkade/assets/108886656/17f23126-15e1-4c7d-8cfa-fa9e46a32bd8)

**Comment by nlamot** [comment]
As a workaround, you could install arkade directly from github. For example, in Github actions we're doing this:
```bash
if ! [ -x "$(command -v curl)" ]; then
  sudo apt update && sudo apt install -qy curl
fi
curl https://raw.githubusercontent.com/alexellis/arkade/master/get.sh | sudo sh
echo "PATH=$HOME/.arkade/bin:$PATH" >> $GITHUB_ENV
```

**Comment by alexellis** [comment]
Yes unfortunately there is nothing I can do about this.

Squarespace won't allow me to edit any records, and say that they won't issue the certificate for up to 72 hours.

This migration has been a terrible experience, with no warning.

**Comment by alexellis** [comment]
@nlamot there is no need to do that with GitHub Actions, there are custom actions for arkade already that download the tool and set it up. https://github.com/alexellis/arkade?tab=readme-ov-file#install-clis-during-ci-with-github-actions

The arkade-get action doesn't use the domain to do the installation, but JavaScript and the latest URL:

https://github.com/alexellis/arkade-get

Check out the README..

And for all the folks coming out of the woodwork to complain, please sponsor me for this project if you are using it. It's hard enough to run open source projects already :+1:

**Comment by alexellis** [comment]
I've hosted something manually with Caddy, which is less than ideal. It fixed the issue, however Squarespace can't really expect people migrated to its platform to have 72 hours of downtime to provision a TLS cert, can they?

Sponsorships accepted at [https://github.com/sponsors/alexellis](https://github.com/sponsors/alexellis)
