### ISSUE TITLE
OpenFaas: MaxInFlight sent to STAN is 0 (even when max-inflight @ install is >= 1)

### ISSUE THREAD

**Issue by kylos101** [alexellis/arkade#106]
## Expected Behaviour
MaxInFlight received by STAN should match what was specified during install with ark

## Current Behaviour
STAN is receiving a MaxInFlight of 0

## Possible Solution
[Change this string from max_flight to max-flight? I could be horribly wrong, I don't know GO.](https://github.com/alexellis/arkade/commit/496f8b4c9aa06512faa3f3841e02e810d1d9a455#diff-6939d1a84033db97f5e630a192f81484R182)

Note: as a workaround, I plan to patch the config for my queue-worker, to set this # manually.

## Steps to Reproduce (for bugs)
```
# install openfaas
ark install openfaas \
  --gateways 3 \
  --queue-workers 2 \
  --max-inflight 10 \
  --set=faasIdler.dryRun=false \
  --set=nats.external.enabled=true \
  --set=async=true \
  --set=nats.external.host=nats-client.default.svc.cluster.local \
  --set=nats.external.clusterName=stan \
  --set=nats.external.port=4222

# inspect stan logs
kubectl logs statefulset/stan -f --all-containers

# see entries like this
[1] 2020/05/04 01:52:58.062182 [ERR] STREAM: [Client:faas-worker-queue-worker-667869d6b7-cjf4m] Invalid MaxInflight (0) in subscription request from _STAN.sub.stan
```
## Context
My queue-worker pods cannot start, as they cannot connect to STAN.

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux kytop 5.1.15-surface-linux-surface #8 SMP Thu Jun 27 12:03:55 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
Version: 0.2.9
Git Commit: 496f8b4c9aa06512faa3f3841e02e810d1d9a455
```

* What helm version is this?

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Comment by alexellis** [comment]
I'll take a look today

**Comment by kylos101** [comment]
Okay, I recall it works when nats external enabled is false. I figure it
may only be a problem when external is true, or perhaps specific to my
environment.

FYI, I have authentication disabled in NATS, currently, because auth cannot
be set yet when installing STAN via the helm chart.

Thanks,

Kyle

**Comment by kylos101** [comment]
Works like a champ, thank you, @alexellis !
