### ISSUE TITLE
[App Request] install/upgrade Datadog agent / daemonset

### ISSUE THREAD

**Issue by blaisep** [alexellis/arkade#108]
## Expected Behaviour

```
arkade install datadog --daemonset="true"

```
## Current Behaviour

Currently I install the daemonset as a custom chart using Datadog's `stable/datadog` repo:
```
arkade install chart --repo-name stable/datadog \
    --set datadog.apiKey=$DD_API_KEY \
    --set datadog.apm.enabled="true" \
    --set datadog.clusterAgent.enabled="true" \
    --set datadog.clusterAgent.token=$DD_CLUSTER_KEY
```
The UI is captured here:
https://asciinema.org/a/327151

I have also installed it as a daemonset, which apparently is the preferred approach.
https://docs.datadoghq.com/agent/kubernetes/?tab=daemonset

## Possible Solution

I believe that `arkade` could provide a more intuitive CLI between the user and the various decisions: 

### Helm2 vs Helm3, 

https://docs.datadoghq.com/agent/kubernetes/?tab=helm

### Helm vs daemonset, 

https://github.com/helm/charts/tree/master/stable/datadog
https://docs.datadoghq.com/agent/kubernetes/?tab=daemonset

#### Optional agents, 

https://docs.datadoghq.com/agent/kubernetes/?tab=helm#optional-collection-agents

#### Integration options

https://docs.datadoghq.com/agent/kubernetes/?tab=helm#integrations
https://docs.datadoghq.com/getting_started/agent/autodiscovery/?tab=docker

## Context

This is mostly as a convenience for new or sporadic practitioners because the k8s ninjas may feel comfortable navigating helm charts.

The Daemonset configuration is daunting and prone to many errors

Installing the agent from Helm is only a little bit simpler but still requires making several decisions which are often irrelevant and the syntax for the values can be easy to screw up.

- Create a 32 char base64 `clusterAgent.token`
- Cluster agent, node agent, both?
- Choose the manifest with the collection

https://github.com/helm/charts/tree/master/stable/datadog

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Darwin Trials-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```

* What arkade version is this?

```
Version: 0.3.2
Git Commit: 9757df68cdfcabf7638417e7c2e9e4d813b7efdf
```

**Comment by alexellis** [comment]
This may make a good sponsored app (see README) - or if there is unprecedented, genuine demand from the community, I may consider it as a contributed app.
