### ISSUE TITLE
k10multicluster not found in latest kastenhq/external-tools release

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#1082]
## Expected Behaviour

The k10multicluster binary should be available in each release

## Current Behaviour

The latest [7.0.0](https://github.com/kastenhq/external-tools/releases/tag/7.0.0) release has no binary for k10multicluster.

## Possible Solution

Either remove the CLI or wait for @MichaelCade to speak with his team about a fix or to confirm if this was intentional.

**Comment by alexellis** [comment]
Let's disable the download for the time being.

**Comment by MichaelCade** [comment]
This tool with 7.0 release was depreciated.

**Comment by rgee0** [comment]
Thanks for the update @MichaelCade 

@alexellis i’ll remove the commented out code as part of my next change unless someone gets there first
