### ISSUE TITLE
Metrics-server doesn't work on a local cluster spun up using k3sup

### ISSUE THREAD

**Issue by nimamahmoudi** [alexellis/arkade#109]
I installed the `metrics-server` on a `k3s` cluster created using `k3sup`, but the metrics-server doesn't seem to be able to collect metrics.

## Expected Behaviour
`kubectl top node` to show the metrics of the nodes in the cluster.

## Current Behaviour
```
kubectl top node
error: metrics not available yet
```
I get errors like this in the logs of the successfully provisioned metrics server pod:
```
E0510 01:29:51.454416 1 reststorage.go:160] unable to fetch pod metrics for pod kubernetes-dashboard/dashboard-metrics-scraper-7b8b58dc8b-kpkcx: no metrics known for pod
E0510 01:29:51.450163 1 reststorage.go:135] unable to fetch node metrics for node "xxxxx": no metrics known for node
```

## Possible Solution
Probably something is missing in `k3s` deployments that is in there for `k8s`. In that case, maybe arkade could check and install those if necessary?

## Steps to Reproduce (for bugs)

1. k3sup install --ip $IP --user ubuntu
2. ark install metrics-server --wait true

## Context
Basically, I spin up a cluster using k3sup (following the Github readme for the project). Everything works smoothly with all other deployments (like minio, registry, local app, etc.). After deploying the metrics-server through arkade, the metrics server doesn't work.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu-18.04 using WSL

```
uname -a
Linux NMLap 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

* What arkade version is this?

```
arkade version
            _             _
  __ _ _ __| | ____ _  __| | ___
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.3.2
Git Commit: 9757df68cdfcabf7638417e7c2e9e4d813b7efdf
```

**Comment by alexellis** [comment]
Hi there, thanks for your interest in arkade

1) k3s has metrics-server built in now, so there's no need for you to try to install it again. See the docs at k3s.io
2) the error you saw is normal, the metrics are not instant and take a few minutes to collect. 

Since this isn't related to arkade I'm going to close. If you need technical support for Kubernetes, their Slack is a good place to start, as are the docs.

If we do find this to be an issue with arkade, I'll reopen. 

Alex

**Comment by nimamahmoudi** [comment]
Oh, I probably deleted the metrics server that came along with k3s. Regarding the error, it doesn't show any metrics even after days have passed, so there is an error. But, I will get to the k3s implementation.

Thanks for the help.

**Comment by alexellis** [comment]
I would expect an error if you deleted the built-in k3s controller.

**Comment by alexellis** [comment]
Try creating a new cluster, and feel free to use Slack for technical support requests like this.
