### ISSUE TITLE
arkade e2e URL check tests are failing due to ktop release v0.3.6

### ISSUE THREAD

**Issue by nitishkumar71** [alexellis/arkade#1103]
E2E URL tests are failing due to ktop. Ktop latest release i.e. v0.3.6 does not have binaries in it.
See vladimirvivien/ktop#46

**Comment by rgee0** [comment]
Looks to be fixed @ https://github.com/vladimirvivien/ktop/releases/tag/v0.3.7

Pattern is as previous and pipelines since v0.3.7 was released have been passing E2E.

**Comment by alexellis** [comment]
Thanks @rgee0
