### ISSUE TITLE
[feature] Add pihole install

### ISSUE THREAD

**Issue by eharrow** [alexellis/arkade#111]
Available from https://hub.helm.sh/charts/mojo2600/pihole

**Comment by alexellis** [comment]
Is this third-party/community-quality or from the upstream project? The naming of mojo2600 makes me think it's the former?

**Comment by eharrow** [comment]
Not sure. I have not used helm before and think this is one devs attempts at a helm chart.

**Comment by aneelysis** [comment]
This is the official pihole docker image, if that helps: https://hub.docker.com/r/pihole/pihole

**Comment by Shikachuu** [comment]
/template
@eharrow are you still intrested?

Can you fill the issue template please?

**Comment by Shikachuu** [comment]
/close
Sorry, but as far as we know, there is no offical helm chart for pi-hole, nor a recommendation for this community chart.
Also the issue is invalid since because the issue template was not used, but feel free to open a new one any time.
