### ISSUE TITLE
Add glab cli support

### ISSUE THREAD

**Issue by e-roux** [alexellis/arkade#1119]
## Expected Behaviour

Add glab CLI as a supported CLI

```shell
arkade get glab
```

## Current Behaviour

Gitlab is part of the Apps catalog, but its CLI is not supported.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? 
n.a.

If approved, are you willing to submit a pull request for this?
no

**Comment by alexellis** [comment]
Hi @e-roux

I'm fine with this suggestion.

if you need this tool, you can wait for someone to pick this up, or you can [sponsor me via GitHub](https://github.com/sponsors/alexellis) and I'll do it for you and have it merged within a short period of time.

Alex
