### ISSUE TITLE
[App] Add nats-connector to arkade

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#112]
## Expected Behaviour

Add an app for the openfaas nats-connector helm chart to arkade, once complete openfaas users will be able to subscribe to events from NATS simply by running `arkade install nats-connector`

https://github.com/openfaas/faas-netes/tree/master/chart/nats-connector

**Comment by alexellis** [comment]
For this PR I would suggest following the example of the `loki` app which was refactored by @Waterdrips recently to use some helpers and to deduplicate code.

**Comment by alexellis** [comment]
/add label: good first issue, help wanted

**Comment by viveksyngh** [comment]
Derek assign: me
