### ISSUE TITLE
[App] - Add Loki for log indexing/viewing and integration to OpenFaaS

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#115]
## Add an app for Loki

Loki can be used for log indexing/viewing, and there is a separate integration for OpenFaaS by @LucasRoesler

[Loki](https://grafana.com/oss/loki/) appears to have a helm chart now: https://github.com/grafana/loki/blob/master/docs/installation/helm.md

## Additional context

@LucasRoesler has a Loki log provider for which we can also create a separate arkade app `openfaas-loki`: https://github.com/LucasRoesler/openfaas-loki/

Step 1 - PR for Loki with defaults
Step 2 - PR for Loki adding some additional flags
Step 3 - PR for `loki-openfaas` and testing that the latest version works as expected with Lucas' log provider, if not to raise an issue

**Comment by mehyedes** [comment]
I would like to work on this issue if that's ok

**Comment by alexellis** [comment]
Sounds good to me. I've just updated the issue with 3 steps, do you have any questions?

**Comment by mehyedes** [comment]
Thanks, not for now. But will let you know if anything comes up.

**Comment by alexellis** [comment]
@mehyedes how are we doing with this app? We're looking to move forward with a blog post which would need this. https://trello.com/c/6cTnrTIG/127-add-loki-logs-blog-post

**Comment by Waterdrips** [comment]
/assign: me

We discussed with @mehyedes and it sounds like you might be busy and unable to get to this soon.

Ill take this if you don't mind?

**Comment by mehyedes** [comment]
Sure @Waterdrips . Thanks

**Comment by alexellis** [comment]
We now have the `loki` app thanks for @Waterdrips in #119 - now to go and add openfaas-loki

**Comment by LucasRoesler** [comment]
@Waterdrips I finally published the helm chart for openfaas-loki via a github page, this will work now

```sh
helm repo add lucas https://lucasroesler.com/openfaas-loki
```

**Comment by Waterdrips** [comment]
Thanks @LucasRoesler - PR opened to include this in arkade :tada:
