### ISSUE TITLE
Enable the scale to zero on raspberry pi

### ISSUE THREAD

**Issue by njjry** [alexellis/arkade#116]
I would like to use the scale-to-zero on raspberry pi. But the instruction only uses arkade install to install openfass. So I wonder if there is a way to configure the --dry-run to false using arkade install or any other ways to install openfaas with --dry-run to false on raspberry pi?
I am using raspberry pi 3B+.

Thanks

**Comment by alexellis** [comment]
Hi, thanks for using OpenFaaS and arkade.

This question would be better served via Slack.

Alex

**Comment by alexellis** [comment]
For your reference, you can pass any helm configuration via `--set` so, look at the helm chart README file for the correct flag and then add `--set`, so `arkade install openfaas --set faasIdler.dryRun=false`

**Comment by njjry** [comment]
Thanks
