### ISSUE TITLE
portainer

### ISSUE THREAD

**Issue by gloubix** [alexellis/arkade#118]
Hi !

Thx to all the work done i managed to install a k3s node with rancher multipass on my mac to start playing with but i can't find a way to add persistance to portainer intalled via arkade.

At each reboot i have to recreate all : adm password settings etc ; anyway to add persistance ?

Thx

**Comment by alexellis** [comment]
Hi @gloubix - I assume that Portainer do not have this enabled in their chart.

@deviantony - do you have support for persistent volumes in the [Portainer helm chart yet](https://github.com/portainer/portainer-k8s/)?

Alex

**Comment by alexellis** [comment]
@gloubix from looking at the chart that the guys have upstream, it would appear that this is not supported yet, feel free to log an issue with them [on their thread here](https://github.com/portainer/kubernetes-beta/issues/1)

I'll close this issue now and am happy to update the `portainer` app once the helm chart is updated.
