### ISSUE TITLE
[Feature] Traefik v2 app

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#12]
## Task

Add app for traefik v2

https://docs.traefik.io

https://docs.traefik.io/getting-started/install-traefik/#use-the-helm-chart

**Comment by braybaut** [comment]
https://github.com/alexellis/arkade/pull/23

**Comment by wingkwong** [comment]
Following @braybaut's steps , the installation was fine but it showed ``404 page not found`` when visiting ``http://localhost:8082/dashboard/``. Any idea?

Arkade version.
```
Version: 0.2.8
Git Commit: 8f311a3ad529cff36e854b3a3ab8f07cd0195105
```

Steps to reproduce:
```
k3d create -n traefik-playground
export KUBECONFIG="$(k3d get-kubeconfig --name='traefik-playground')"
kubectl create namespace traefik-playground
arkade install traefik2 --dashboard -n traefik-playground 
kubectl port-forward svc/traefik 8082:80 -n traefik-playground &
```

**Comment by alexellis** [comment]
I think you port forwarded Traefik itself rather than the dashboard. @Waterdrips can probably assist here

**Comment by Waterdrips** [comment]
It does appear not to be working. It should be matching the /dashboard/ route using the traefik ingressroute CRD, but it doesnt seem to pick that up. 

Ill have a look and see if i can work it out

**Comment by Waterdrips** [comment]
/close 

we have traefik v2 #40
