### ISSUE TITLE
[App] NFS provisioner

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#121]
The NFS provisioner for Kubernetes allows NFS to back PersistentVolumes and looks relatively simple to install:

```
helm install stable/nfs-client-provisioner --set nfs.server=x.x.x.x --set nfs.path=/exported/path
```

I'm looking for someone to add an `nfs-provisioner` app.

Follow the example of the `loki` app which uses a newer style

**Comment by kadern0** [comment]
@alexellis, @Waterdrips I've been working for a bit on this, but don't understand something on this code:
https://github.com/alexellis/arkade/blob/master/pkg/apps/loki.go

Shouldn't it be application agnostic (function name and file name)? Do I create one for the nfs-provisioner with almost the same code as the loki one?

**Comment by Waterdrips** [comment]
Yeh it can be changed to a generic helm app in pkg/apps. 

I was looking at that earlier and thought that. I'm happy for that to be renamed and take a generic app struct as input.

I was working on a larger reactor for more apps and made that change in my branch.

The only thing to mention is that lots of apps need pre helm and post helm commands run, so a generic helm one would need wrapping in an app specific one in that case.
