### ISSUE TITLE
arkade install returns empty node architecture

### ISSUE THREAD

**Issue by goffinf** [alexellis/arkade#131]
Trying out arkade for the first time, following nuno's WSL2+k3d blog post (see: https://wsl.dev/wsl2-k3d-arkade/)

The arkade install *does* work successfully on a WSL2 that has NOT been configured for SystemD, but NOT for one that has. So, whilst this may or may not be an arkade issue per se, I would like to understand why, especially given that if I simulate the GetNodeArchitecture (see below) method used with kubectl the value "amd64" is returned

It is also worth noting that I can install portainer directly from the published YAML without any problem at all on the Systemd WSL2 distro (https://raw.githubusercontent.com/portainer/portainer-k8s/master/portainer.yaml)

```
func GetNodeArchitecture() string {
	res, _ := KubectlTask("get", "nodes", `--output`, `jsonpath={range $.items[0]}{.status.nodeInfo.architecture}`)

	arch := strings.TrimSpace(string(res.Stdout))

	return arch
}
```

## Expected Behaviour
Successful install of portainer

## Current Behaviour
```
$ ark install portainer
Using kubeconfig: /home/goffinf/.kube/config
Node architecture: ""
Error: only Intel and "arm" is supported for this app
```

```
$ kubectl get nodes
NAME                     STATUS   ROLES    AGE   VERSION
k3d-bigcastle-worker-1   Ready    <none>   63m   v1.18.4+k3s1
k3d-bigcastle-worker-2   Ready    <none>   63m   v1.18.4+k3s1
k3d-bigcastle-master-0   Ready    master   63m   v1.18.4+k3s1
k3d-bigcastle-worker-0   Ready    <none>   63m   v1.18.4+k3s1
```
Checking one of the node using jsonpath per the GetNodeArchitecture() method:

```
$ kubectl get nodes k3d-bigcastle-worker-0 -o=jsonpath="{.status.nodeInfo.architecture}"
amd64
```

Likewise with uname:
```
$ uname -m
x86_64
```

```
$ uname -a
Linux DESKTOP-XXXXXXX 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## Steps to Reproduce (for bugs)
1. Configure WSL2 for systemd (see: https://forum.snapcraft.io/t/running-snaps-on-wsl2-insiders-only-for-now/13033  or   https://hoverbear.org/blog/getting-the-most-out-of-wsl/)
2. Install k3d
3. Create a k3d cluster
4. Install arkade
5. arkade install portainer

## Context
I am testing WSL2 with a number of K8s distributions. One (common) use case is to configure WSL2 for SystemD (more closely simulates corporate environment, allows use of snap and other Systemd capabilities, etc...).

## Your Environment

* What Kubernetes distribution are you using?

k3d v3.0.0-rc.6

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Linux DESKTOP-XXXXXXX 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* What arkade version is this?

```
arkade version
Version: 0.3.6
Git Commit: 3b6845bced66cecfd302f153792ae10052718596
```

**Comment by alexellis** [comment]
You'll usually see an empty architecture for the node if you are mistakenly running as root or have a bad KUBECONFIG setting.

**Comment by alexellis** [comment]
Are you running as root? Have you tried setting a KUBECONFIG env var?

**Comment by goffinf** [comment]
Ah mystery solved ... I ran a different arkade install (cert-manager) and noted this in the output:
```

....
Error: fork/exec /usr/local/bin/kubectl: permission denied
```

Sure enough, checked kubectl permissions and execute was only enabled for root.  A quick chmod +x, then tried the portainer install again ...
```
$ arkade install portainer
Using kubeconfig: /home/goffinf/.kube/config
Node architecture: "amd64"
=======================================================================
= Portainer has been installed                                        =
=======================================================================


# Open the UI:

kubectl port-forward -n portainer svc/portainer 9000:9000 &

# http://127.0.0.1:9000

# Or access via NodePort on http://node-ip:30777

Find out more at https://www.portainer.io/


Thanks for using arkade!
```

So all good now.  Sorry for the noise. Happy to close

Regards

Fraser

**Comment by alexellis** [comment]
Thanks for using arkade
