### ISSUE TITLE
[App Request] please add grafana

### ISSUE THREAD

**Issue by gshiva** [alexellis/arkade#142]
Prometheus + Grafana has become pretty much standard now

https://github.com/helm/charts/tree/master/stable/grafana

**Comment by alexellis** [comment]
Hi, thanks for your suggestion. Did you know that we have Grafana already? I would always recommend looking at what is already supported before asking for an app.

**Comment by gshiva** [comment]
Did go through the list before adding... and reviewed the prometheus ticket. Maybe an update to https://github.com/alexellis/arkade/README.md ?
