### ISSUE TITLE
How to fail if tool is not supported in os/arch?

### ISSUE THREAD

**Issue by rberrelleza** [alexellis/arkade#157]
What's the recommendation on handling binaries that are not available on the users OS or arch? E.g. I'm looking into adding [kubie](https://github.com/sbstp/kubie/releases), but they only have binaries for linux and macos on amd64. 

Is there a way to fail `arkade get` with a friendly message?

**Comment by alexellis** [comment]
Hi @rberrelleza - not as far as I know, what happens currently - 404?

We could give an error like, Server returned a not found error, APP may not be available for your system.

**Comment by Waterdrips** [comment]
If we know which arche/os combos are supported can we create a map/list for a tool and verify the client conforms before trying a get? 

could be a 
```go 
map[string][]string

"linux": ["amd64", "arm64", "i386"],
"macos": ["amd64"]
```
Hang that off the `Tool` and add a `func (t *Tool) IsSupported(os, arch string) bool` 
then have a func that takes that map, given `os` and `arch` and sees if its there?

**Comment by rberrelleza** [comment]
Today, depending on the tool, you might get a 404 or a template-related error (for cases where a variable might not generated or something like that). 

I like @Waterdrips approach here. I think we could add that as an optional field, so that we can give the user a more specific error message (e.g. "kubie is not available on Windows") rather than a more cryptic, or implementation specific error, like a 404.

**Comment by alexellis** [comment]
I think that handling the HTTP code would be a simple approach. The templates just need to go to an invalid URL when there's no package available

**Comment by alexellis** [comment]
There shouldn't be errors from the template. Can you show some examples?

**Comment by rberrelleza** [comment]
> There shouldn't be errors from the template. Can you show some examples?

None of the ones in arkade. This came to me while I was working on adding kubie. It doesn't have a windows or arm release, and didn't know what best practice to follow.

**Comment by alexellis** [comment]
I think that just allowing the code to hit a 404 should be OK.

**Comment by alexellis** [comment]
It seems that we get a "404 not found" message, I'm OK with that. We could perhaps write something like "arkade didn't find a compatible binary for your system"

Adding --os --arch flags to `arkade get` would be helpful for testing though, where we can inject/override the values.

**Comment by Shikachuu** [comment]
Since then, we have the `--os` and `--arch` flags with a graceful handling of 404 may I close this?

**Comment by rberrelleza** [comment]
Fine with me!
