### ISSUE TITLE
Registry ingress shoud use namespaced Issuer

### ISSUE THREAD

**Issue by meyskens** [alexellis/arkade#160]
## Expected Behaviour
The `docker-registry-ingress` should only create resources like the cert-manager Issuer in the namespace it is being installed into.

## Current Behaviour
The `docker-registry-ingress` creates a cluster wide issuer called `letsencrypt-prod-registry` potentially exposing a security risk by allowing all name spaces to use it or cause a naming collision to break another app.

## Possible Solution
```
metadata:
  name: letsencrypt-prod-registry
  namespace: {{.Namespace}}
```
already has namespace defined, so it probably was a mistake so `kind: ClusterIssuer` needs to become `kind: Issuer`

## Context
https://github.com/alexellis/arkade/blob/master/cmd/apps/registry_ingress_app.go#L187

**Comment by Waterdrips** [comment]
This makes sense. Does the openfaas-ingress also create a cluster issuer? If so that could be updated too?

**Comment by alexellis** [comment]
For the openfaas app, having the option to go to ClusterIssuer may be better for backwards compatibility, for the other apps I wouldn't offer it.
