### ISSUE TITLE
add note for zsh

### ISSUE THREAD

**Issue by OfTheDelmer** [alexellis/arkade#165]
When trying to install with zsh it seems like the password prompt flashes for 2 secs and fails.

## Expected Behaviour

I'm not sure what the exact issue is, but with `zsh` the following seems to work:

```shell
sudo sh < <(curl -sLS https://dl.get-arkade.dev)
```

## Current Behaviour

Running the current install I see the password prompt for a second and then it disappears.

```shell
$ curl -sLS https://dl.get-arkade.dev | sudo sh
Password:
[5]  + 76464 done                   curl -sLS https://dl.get-arkade.dev |
       76465 suspended (tty input)  sudo sh
```

## Possible Solution

```shell
sudo sh < <(curl -sLS https://dl.get-arkade.dev)
```

## Steps to Reproduce (for bugs)

1. Be on catalina `10.15.5` or newer?
2.have zsh
3. run install

## Your Environment

* What Kubernetes distribution are you using?

```
k3s version v1.17.2+k3s1 (cdab19b0)
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
darwin
```

* What arkade version is this?

```
Version: 0.5.1
```

**Comment by alexellis** [comment]
@OfTheDelmer thanks for the report. Did the change I made in the commit above help at all?

**Comment by alekczapski** [comment]
If it were useful, for Ubuntu WSL works fine.
```
➜  ~ zsh --version
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
➜  ~
```
```
➜  ~ curl -SLfs https://dl.get-arkade.dev | sudo sh
[sudo] password for user:
x86_64
Downloading package https://github.com/alexellis/arkade/releases/download/0.6.10/arkade as /tmp/arkade
Download complete.

Running with sufficient permissions to attempt to move arkade to /usr/local/bin
New version of arkade installed to /usr/local/bin
            _             _
  __ _ _ __| | ____ _  __| | ___
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.6.10
Git Commit: 08ce44c5a23ff95576f7ccdc7e6ea956a6cbd85e
➜  ~
```

**Comment by alexellis** [comment]
Thank you @alekczapski 

@OfTheDelmer would you like to test again?

**Comment by rberrelleza** [comment]
@alexellis I just tried it on MacOS+zsh, and I get the same error that @OfTheDelmer reported.

**Comment by Shikachuu** [comment]
@rberrelleza this issue is still there with the current version of arkade?

**Comment by rberrelleza** [comment]
@Shikachuu not anymore! 
![image](https://user-images.githubusercontent.com/475313/154382837-a54f0740-3ba6-461f-aed6-ee635330981e.png)
