### ISSUE TITLE
Remove custom helm download code

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#168]
## Expected Behaviour

There is now generic code to download helm, so we can get rid of the duplicated code for downloading helm here: 

https://github.com/alexellis/arkade/blob/master/pkg/helm/helm.go#L24

We have a "tool" for helm3 and `arkade get`:

https://github.com/alexellis/arkade/blob/master/pkg/get/tools.go#L24

The linkerd2 app provides an example of how to download helm:

https://github.com/alexellis/arkade/blob/8de0eff4feb0702787a434821ea5f267be855e0b/cmd/apps/linkerd_app.go#L125

## Possible Solution

* Delete the custom helm download code
* Have apps call a similar method to the linkerd2 app example
* Test with edge cases i.e. windows / git bash

**Comment by alexellis** [comment]
@Amalkh5 were you working on this?

**Comment by Amalkh5** [comment]
@alexellis how can I replace the current code logic in downloading helm and helm3  while the  "tool" only provides helm3?
because of all logic in helm.go https://github.com/alexellis/arkade/blob/master/pkg/helm/helm.go#L24 decoded around the fact that there are helm and helm3

**Comment by alexellis** [comment]
Good point Amal. We can add helm2 as a tool or depreciate it. I would vote for deprecation of helm2. @Waterdrips wdyt?

**Comment by Waterdrips** [comment]
Depricate is usually my preference 🙂🤞

**Comment by alexellis** [comment]
Let's do it then? First PR will remove helm 2 completely. Second PR should remove the duplication with helm 3.

You guys can split the work, or I'm happy for Amal to run with it.

**Comment by Amalkh5** [comment]
@Waterdrips happy to do both, what do you think?

**Comment by Waterdrips** [comment]
Go for it. Let me know if you need anything from me

**Comment by Amalkh5** [comment]
@Waterdrips as I working on the code I noticed that char_app,cronconnector_app,kafkaconnector_app, and postgres_app are installed using helm2 only, is that right? and if so I think we need first to make them support helm3

**Comment by alexellis** [comment]
They will all work with helm 3, don't worry about it. Alex

**Comment by Amalkh5** [comment]
@alexellis because I got the following error in [TemplateChart](https://github.com/alexellis/arkade/blob/master/pkg/helm/helm.go#L277) function :-
```
Error: unknown flag: --name
Error: exit code 1, stderr: Error: unknown flag: --name

exit status 1
```
then i check with helm3 template to find out that they changed release name parameter from `--name` to `release-name`
after i update it i got the following error:- 
```
$ go run main.go install cron-connector

Using kubeconfig: /Users/AmalAlkhamees/.kube/minikube-config
Client: x86_64, Darwin
2020/08/25 17:23:05 User dir established as: /Users/AmalAlkhamees/.arkade/
"openfaas" has been added to your repositories

Node architecture: "amd64"
Chart path:  /var/folders/30/rs8_07d90xvb5k16p6swq24r0000gp/T/charts
Error: expected at most two arguments, unexpected arguments: 
Error: exit code 1, stderr: Error: expected at most two arguments, unexpected arguments: 

exit status 1
```

**Comment by alexellis** [comment]
You'll need to just move away from using helm template, or look up the new syntax. I'd suggest not using the templating behaviour, we don't support it in the newer apps anyway.

**Comment by Amalkh5** [comment]
@alexellis I opened PR #197 to remove the templating behavior from the apps mentioned above which will also add support for helm3.  
After that, I will open PR to remove helm2 completely.

**Comment by alexellis** [comment]
Thank you @Amalkh5 

Where would you say we are with this exercise now? cc @Waterdrips

**Comment by Amalkh5** [comment]
@alexellis almost done , i opened PR #204 to remove helm 2 after merge i will submit the last PR that will close this issue.
