### ISSUE TITLE
Idea: add doctl tool

### ISSUE THREAD

**Issue by kylos101** [alexellis/arkade#174]
Cloud providers often have CLI tools. I currently use Digital Ocean. Installing doctl (the Digital Ocean tool) with ark would be a nice alternative to:

```
curl -sL https://github.com/digitalocean/doctl/releases/download/1.46.0/doctl-1.46.0-linux-amd64.tar.gz | tar -xzv
```

## Expected Behaviour
`ark get` would include support for `doctl`.

## Current Behaviour
Ark does not currently include Amazon (aws), Azure (az), or Digital Ocean (doctl) CLI tools. Some of then are tied to an SDK or seem big. doctl seems like "the right size".

## Possible Solution
1. `ark get` would include doctl in the list
2. `ark get doctl` would download and extract doctl to the /tmp folder (like `ark get kubectl`), and then print instructions...

```
Downloading doctl
https://github.com/digitalocean/doctl/releases/download/1.46.0/doctl-1.46.0-linux-amd64.tar.gz
Tool written to: /tmp/doctl

Run the following to copy to install the tool:

chmod +x /tmp/doctl
sudo install -m 755 /tmp/doctl /usr/local/bin/doctl
```

## Context
I install doctl using the command above.

**Comment by alexellis** [comment]
Thank you for the suggestion. doctl is also useful for managing Kubernetes clusters on DOKS, so I'd be up for accepting a PR.

Would you like to work on this, or should we find someone else on Slack to take it?

**Comment by kylos101** [comment]
Hi Alex, I'd be happy to work on it. I've never worked in Go though, so
it's going to take me a little bit to ramp up. Is that okay?

**Comment by Waterdrips** [comment]
@kylos101 I'm happy to provide help in testing/questions for this if that helps. Just let me know :)

**Comment by kylos101** [comment]
> @kylos101 I'm happy to provide help in testing/questions for this if that helps. Just let me know :)

That'd be perfect, thank you, @Waterdrips !

**Comment by alexellis** [comment]
Start by adding your definition here:

https://github.com/alexellis/arkade/blob/master/pkg/get/tools.go

And by adding a test there:

https://github.com/alexellis/arkade/blob/master/pkg/get/get_test.go

Take special care around the extensions and names for different platforms and OSes - https://github.com/digitalocean/doctl/releases

We have Go templates to generate the proper name, and you should find a suitable example to copy. And thanks @Waterdrips for volunteering to help out.

**Comment by kylos101** [comment]
Hi @Waterdrips I think #179 is ready for you to take a peek? 

A couple things (you'll see these as Conversations on the Files in the PR):
1. I'm a unsure if anything else is needed for ARM and wanted to get your feedback. If we do nothing else, if someone tries from a device with an ARM processor, it'll yield a 404. I'm pretty sure that's okay because it doesn't look like DO provides support for ARM.
2. I used `log` and `fail` instead of `fatalf` when spinning through my test objects. This way if there are multiple failures I see them all at once. Is that okay?

**Comment by kylos101** [comment]
Added in #186. Thank you for the help @Waterdrips  and @alexellis!
