### ISSUE TITLE
[CLI tool] Add kubebuilder

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#180]
## Description

Add [kubebuilder](https://book.kubebuilder.io/quick-start.html#create-a-project) - a binary for building Kubernetes controllers.

**Comment by viveksyngh** [comment]
I will be working on this.

**Comment by Amalkh5** [comment]
@viveksyngh I already finished this issue yesterday, can you please review my PR?

**Comment by alexellis** [comment]
I've merged it, thank you @Amalkh5
