### ISSUE TITLE
arkade install portainer fails on arm64

### ISSUE THREAD

**Issue by matonb** [alexellis/arkade#188]
## Expected Behaviour
Portainer container gets installed.

## Current Behaviour
Fails with message:
```
Using kubeconfig: /root/.kube/config
Node architecture: "arm64"
Error: only Intel and "arm" is supported for this app
```
## Possible Solution
Update `portainer_app.go` to allow arm64 architecture

## Steps to Reproduce (for bugs)
```
curl -sfL https://get.k3s.io | sh -
curl -sLS https://dl.get-arkade.dev | sudo sh
arkade install portainer
```

## Context
Trying to create k3s cluster on Raspberry PI 4s with Portainer
I have portainer running (docker run portainer/portainer, args omitted...) on another RPi 4 with Raspberry OS 64bit, so I know it works...

## Your Environment

* What Kubernetes distribution are you using?
```
kubectl version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:44:09Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:44:09Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/arm64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspberry PI4 - Raspberry OS 64bit
`/boot/cmdline.txt` updated to allow cgroup memory, appended:
```
cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
```

```
uname -a
Linux pi.example.com 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux

cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* What arkade version is this?

```
arkade version

Version: 0.6.4
Git Commit: 76049b52349f44e325e288b9ea8e264efa890f3e
```

**Comment by alexellis** [comment]
Hi there, the error you are seeing was added by us on purpose to prevent incorrect installation. They may have changed this since we built the app? Can you link to where they started releasing a 64-bit arm image?

**Comment by deviantony** [comment]
Heya, the portainer-beta for k8s was only built for Linux amd arm. The upcoming version 2.0 (should be released by the end of the month) will have k8s support and multi-platform support as well.

**Comment by alexellis** [comment]
Thanks for commenting @deviantony

**Comment by alexellis** [comment]
So @matonb it seems that arkade is technically correct, but if you like, you can view the code and apply Portainer to your RPi using the approach we take in the app. It may work in some circumstances where the RPi's 64-bit OS can run a 32-bit binary (that's probably what you saw) - that's not a generic rule for arm chips however.

https://github.com/alexellis/arkade/blob/master/cmd/apps/portainer_app.go#L55

https://github.com/alexellis/arkade/blob/master/cmd/apps/portainer_app.go#L73

```
curl -s https://raw.githubusercontent.com/portainer/portainer-k8s/master/portainer-nodeport.yaml|sed s/amd64/arm/| kubectl apply -f
```

**Comment by matonb** [comment]
@alexellis 
> 
> 
> Hi there, the error you are seeing was added by us on purpose to prevent incorrect installation. They may have changed this since we built the app? Can you link to where they started releasing a 64-bit arm image?

In answer to your question, I'm not sure when they started to release them, but there are offical arm64 porintainer images on dockerhub

**Comment by AM6331** [comment]
Not sure if this is what you're looking for: [https://hub.docker.com/layers/portainer/portainer-ce/2.0.0/images/sha256-0f026d148bdc7243350a9f726c03b4d52637a8e917403812e5e1715af15b3337?context=explore](https://hub.docker.com/layers/portainer/portainer-ce/2.0.0/images/sha256-0f026d148bdc7243350a9f726c03b4d52637a8e917403812e5e1715af15b3337?context=explore)
