### ISSUE TITLE
Add `arkade update` instructions like we have in k3sup

### ISSUE THREAD

**Issue by Waterdrips** [alexellis/arkade#19]
## Expected Behaviour

`arkade update` could print the upgrade instructions (like k3sup does)
## Current Behaviour

no command 
## Possible Solution

check how k3sup does it, and use a similar approach
https://github.com/alexellis/k3sup/blob/master/cmd/update.go

**Comment by Waterdrips** [comment]
Derek add label: help wanted, skill/beginner, good first issue

**Comment by alexellis** [comment]
I'm surprised that I missed this, will add it in whilst I'm there.
