### ISSUE TITLE
Add helmfile as tool

### ISSUE THREAD

**Issue by tuananh** [alexellis/arkade#193]
Add `helmfile` https://github.com/roboll/helmfile as tool

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

**Comment by alexellis** [comment]
Hi @tuananh, In future please could you wait for approval before working on a PR to add a tool or app?

Thanks

**Comment by tuananh** [comment]
@alexellis sure. we use `hemlfile` at work a lot so I thought it might be useful
