### ISSUE TITLE
arkade get needs to create $HOME/.arkade if it doesn't exist

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#195]
arkade get needs to create $HOME/.arkade if it doesn't exist

## Current Behaviour

```
space-mini:inletsctl alex$ arkade get faas-cli
Downloading faas-cli
https://github.com/openfaas/faas-cli/releases/download/0.12.9/faas-cli-darwin
Error: open /Users/alex/.arkade/bin/faas-cli: no such file or directory
```

## Possible Solution

Create the folder always, and ignore the error, or check if it exists and then create it if it doesn't.

**Comment by alexellis** [comment]
Reported by @tuananh on Slack

**Comment by guacamole** [comment]
@alexellis can i give this a shot?

**Comment by alexellis** [comment]
Feel free to try. It is user-facing so ideally needs completing today.

We have other issues that are less critical if you're not comfortable with the timeline.

**Comment by guacamole** [comment]
I'll do it today!

**Comment by alekczapski** [comment]
I see that $HOME/.arkade is not enough, you need create $HOME/.arkade/bin

**Comment by guacamole** [comment]
that's exactly what i found and by adding the `/bin` to `$HOME/.arkade` it worked :)

**Comment by alexellis** [comment]
I just ran `mkdir $HOME/.arkade` and it worked for me.

The `get` code needs to create and manage the folder, we already have code for that, so we just need to re-use it.

**Comment by alexellis** [comment]
Sorry for butting in here, but I thought this was too urgent to leave unresolved.

It's a very minor change to make it work: https://github.com/alexellis/arkade/releases/tag/0.6.9

Feel free to send another PR if you feel I've missed something.
