### ISSUE TITLE
Use Latest Dashboard in Tekton App

### ISSUE THREAD

**Issue by nickgerace** [alexellis/arkade#198]
The [Dashboard](https://github.com/tektoncd/pipeline) for the [Tekton App](https://github.com/alexellis/arkade/blob/master/cmd/apps/tekton_app.go) is uniquely versioned from the core [Tekton Pipelines](https://github.com/tektoncd/pipeline) service. It's currently outdated, and since it is independently versioned, I believe it should be removed altogether from the Tekton Pipelines installation.

## Expected Behaviour

While we could upgrade the version manually, or use "latest", I believe that this may be a good opportunity to drop the Dashboard from the Tekton installation. The Dashboard is an optional GUI accessory, and this may be better for Arkade users for multiple reasons: more important being a potential mismatch between the "latest" Pipelines release and the "latest" Dashboard release.

## Current Behaviour

We currently have the Dashboard version "0.5.1" hardcoded, which is incompatible with the newest versions of Pipelines.

## Possible Solution

I have made a PR, and will update this issue with the link.

(EDIT: PR #199)

## Context

I was showing arkade to my colleagues, and realized that the Dashboard was outdated, and is most likely unnecessary for Tekton Pipelines users (by default).

## Your Environment

* What Kubernetes distribution are you using?

Kind with Docker Desktop for macOS

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
macOS 10.15.6
```

* What arkade version is this?

```
% arkade version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.6.9
Git Commit: d538641dcc6895fe06c8843f60cb541dd13eb65b
```

**Comment by alexellis** [comment]
Thanks for raising this Nick.

Given that we also deploy ArgoCD with a dashboard, what would prevent us from deploying Tekton with a compatible pinned version of its dashboard?

**Comment by nickgerace** [comment]
Not a problem Alex.

We might be able to use "latest" for the dashboard, just like we do for Tekton pipelines. My concern is that since the dashboard can sometimes lag behind the pipelines release, I would be cautious about bundling both "latest" versions together.

On the other hand, after hearing that ArgoCD App has the dashboard bundled, it's worth noting that the dashboard versions are forward compatible for a few pipelines releases. For example, if Pipelines v4 came out before Dashboard v4, Dashboard v3 should still work with Pipelines v4. This, the user would (realistically) never actually encounter a situation where both versions were incompatible, so maybe it would be worth keeping the dashboard after all. I see both sides of this now.

Does that make sense? Is it an unrealistic concern?

**Comment by alexellis** [comment]
I would suggest that rather than removing the dashboard, that you pin to two known versions - you can pick those versions.

**Comment by nickgerace** [comment]
Okay great. I'll update the PR accordingly when I get the chance, and update this issue. Thank you @alexellis.

**Comment by nickgerace** [comment]
Changed the title to reflect the new nature of the PR.

**Formerly**: Remove Dashboard from Tekton App
**Now**: Use Latest Dashboard in Tekton App

**Comment by nickgerace** [comment]
I believe I misread your last response @alexellis, my apologies. I'd personally prefer to use "latest" for both the dashboard and pipelines, like many other Arkade apps.
