### ISSUE TITLE
Add --helm3 flag to chart app

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#20]
## Description

Add --helm3 flag to chart app

The `arkade install chart` command should have helm3 support and use it by default.

**Comment by alexellis** [comment]
Derek add label: help wanted, skill/beginner, good first issue

**Comment by kadern0** [comment]
Hi, I've been looking at this one. I have it somehow working, but I get validation errors from helm. Any ideas?

`./arkade install chart --repo-name stable/nginx-ingress --repo-url https://kubernetes-charts.storage.googleapis.com --set defaultBackend.enable=false
Using kubeconfig: /home/kaderno/.kube/config
Using helm3
Client: x86_64, Linux
2020/02/29 21:15:47 User dir established as: /home/kaderno/.arkade/
"stable" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
VALUES values.yaml
Command: /home/kaderno/.arkade/bin/helm3/helm [upgrade --install nginx-ingress stable/nginx-ingress --namespace default --values /tmp/charts/nginx-ingress/values.yaml --set defaultBackend.enable=false]
Release "nginx-ingress" has been upgraded. Happy Helming!
NAME: nginx-ingress
LAST DEPLOYED: Sat Feb 29 21:16:02 2020
NAMESPACE: default
STATUS: deployed
REVISION: 7
TEST SUITE: None
NOTES:
The nginx-ingress controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace default get services -o wide -w nginx-ingress-controller'

An example Ingress that makes use of the controller:

  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: example
    namespace: foo
  spec:
    rules:
      - host: www.example.com
        http:
          paths:
            - backend:
                serviceName: exampleService
                servicePort: 80
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - www.example.com
          secretName: example-tls

If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

  apiVersion: v1
  kind: Secret
  metadata:
    name: example-tls
    namespace: foo
  data:
    tls.crt: <base64 encoded cert>
    tls.key: <base64 encoded key>
  type: kubernetes.io/tls
error validating "/tmp/charts/nginx-ingress/Chart.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-customconfig-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-customnodeport-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-headers-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-nodeport-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-tcp-udp-configMapNamespace-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-tcp-udp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-tcp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-default-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-metrics-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-psp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-webhook-and-psp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-webhook-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-autoscaling-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-customconfig-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-customnodeport-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-headers-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-metrics-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-nodeport-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-psp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-tcp-udp-configMapNamespace-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-tcp-udp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-tcp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-webhook-and-psp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-webhook-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error parsing /tmp/charts/nginx-ingress/templates/addheaders-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/clusterrole.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/clusterrolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/job-createSecret.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/job-patchWebhook.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/psp.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/role.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/rolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/serviceaccount.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/validating-webhook.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/clusterrole.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/clusterrolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-daemonset.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-deployment.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-hpa.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-metrics-service.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-poddisruptionbudget.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-prometheusrules.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-psp.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-role.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-rolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-service.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-serviceaccount.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-servicemonitor.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-webhook-service.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-deployment.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-psp.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-role.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-rolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-service.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-serviceaccount.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/proxyheaders-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/tcp-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/udp-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error validating "/tmp/charts/nginx-ingress/values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
Error: kubectl exit code 1, stderr: error validating "/tmp/charts/nginx-ingress/Chart.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-customconfig-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-customnodeport-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-headers-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-nodeport-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-tcp-udp-configMapNamespace-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-tcp-udp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/daemonset-tcp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-default-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-metrics-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-psp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-webhook-and-psp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deamonset-webhook-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-autoscaling-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-customconfig-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-customnodeport-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-headers-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-metrics-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-nodeport-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-psp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-tcp-udp-configMapNamespace-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-tcp-udp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-tcp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-webhook-and-psp-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/tmp/charts/nginx-ingress/ci/deployment-webhook-values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
error parsing /tmp/charts/nginx-ingress/templates/addheaders-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/clusterrole.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/clusterrolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/job-createSecret.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/job-patchWebhook.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/psp.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/role.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/rolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/job-patch/serviceaccount.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/admission-webhooks/validating-webhook.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/clusterrole.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/clusterrolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-daemonset.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-deployment.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-hpa.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-metrics-service.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-poddisruptionbudget.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-prometheusrules.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-psp.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-role.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-rolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-service.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-serviceaccount.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-servicemonitor.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/controller-webhook-service.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-deployment.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-psp.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-role.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-rolebinding.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-service.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/default-backend-serviceaccount.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/proxyheaders-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/tcp-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error parsing /tmp/charts/nginx-ingress/templates/udp-configmap.yaml: json: line 0: invalid character '{' looking for beginning of object key string
error validating "/tmp/charts/nginx-ingress/values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
`

**Comment by aidun** [comment]
Do you have a PR for this, so we I can watch at your code?

**Comment by kadern0** [comment]
Here it is:
https://github.com/alexellis/arkade/pull/27

**Comment by alexellis** [comment]
This is no longer required and has been completed
