### ISSUE TITLE
[APP] Consul

### ISSUE THREAD

**Issue by nicholasjackson** [alexellis/arkade#202]
Consul Service Mesh is a popular Service Mesh for Kubernetes, it would be awesome if Akade supported the installation.

## Expected Behaviour
`arkade install consul` would install and configure Consul Service Mesh for K8s

## Possible Solution
The Consul Helm chart [https://github.com/hashicorp/consul-helm](https://github.com/hashicorp/consul-helm) can be used to install consul. By default the Helm chart does not enable Consul Service Mesh, this can be enabled by an additional Helm values with sensible defaults.

Happy to PR this.

**Comment by alexellis** [comment]
Sounds good - we already have Linkerd, Istio and OSM. Have a look at those variants and see what makes a good default kind of installation. I'll look out for a PR or feel free to ask a Q or 2 here.

**Comment by Shikachuu** [comment]
/msg: template

@nicholasjackson are you still intrested to do a PR?
Also can you fill the issue template please?

**Comment by Shikachuu** [comment]
/close
Closed in favor of #626
