### ISSUE TITLE
[APP] Vault

### ISSUE THREAD

**Issue by nicholasjackson** [alexellis/arkade#203]
Support the installation of Vault for Kuberenetes

## Expected Behaviour
`arkade install vault` would install Vault on Kubernetes with sensible defaults

## Possible Solution
Install Vault using the official Helm chart [https://github.com/hashicorp/vault-helm](https://github.com/hashicorp/vault-helm)

Happy to PR this :)

**Comment by alexellis** [comment]
SGTM - PR #201 should be something you can use as a guide.

Remember that we are using the DCO so you'll need to run `git commit -s` to sign-off (rather than GPG signing)

**Comment by alexellis** [comment]
I was thinking this would be a CLI download ("arkade get"), but you're right, it's an app to install, so forget about my comment re #201

**Comment by Shikachuu** [comment]
/msg: template

@nicholasjackson are you still intrested to do a PR?
Also can you fill the issue template please?

**Comment by Shikachuu** [comment]
/close
Closed in favor of #627
