### ISSUE TITLE
Install fails on MacOS + zsh when sudo requires a password

### ISSUE THREAD

**Issue by rberrelleza** [alexellis/arkade#206]
Running the recommended command to install arkade ( `curl -SLfs https://dl.get-arkade.dev | sudo sh`)  fails on my mac, when running on zsh:

![image](https://user-images.githubusercontent.com/475313/92154693-0d00d300-eddb-11ea-868e-7485da53cc00.png)

## Current Behaviour

It looks like the `sudo sh` part of the command is not waiting for curl to finish, or it gets lost when MacOS asks for my sudo password.  

Running the same command without `sudo` works fine. The same command also works fine on bash.

## Steps to Reproduce (for bugs)

1. Run `curl -SLfs https://dl.get-arkade.dev | sudo sh` in the terminal

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
This happens on MacOS 10.15 when using zsh.

**Comment by alexellis** [comment]
Are you sure this isn't to do with Catalina using zsh instead of bash?

**Comment by alexellis** [comment]
Because my sudo requires a password and it works for me on MacOS. I've not upgraded to Catalina and zsh though

**Comment by rberrelleza** [comment]
@alexellis you are correct, it only happens on zsh

**Comment by rberrelleza** [comment]
Same as https://github.com/alexellis/arkade/issues/165
