### ISSUE TITLE
Add homebrew tap

### ISSUE THREAD

**Issue by amalkh5** [alexellis/arkade#207]
## Expected Behaviour

Installing arkade through homebrew using `` brew install arkade``, it would ease the process of installation for mac users. 

## Possible Solution

As a solution, we could add a repo like `alexecllis/homebrew-alexellis` with the list of formulas like k3sup and arkade
and we can automate formulas updating using GitHub actions

**Comment by Amalkh5** [comment]
resolved by  https://github.com/alexellis/homebrew-alexellis

**Comment by alexellis** [comment]
We still need the automation, so in some respects this is still open (for me)

**Comment by alexellis** [comment]
Thanks for your example. The Civo example was also useful - https://github.com/civo/homebrew-tools

**Comment by Amalkh5** [comment]
@alexellis for automation we could use this as an example https://github.com/snyk/homebrew-tap/actions/runs/238648501/workflow I glad to work on it if you want

**Comment by alexellis** [comment]
That actually looks very good. I would be supportive of using something similar.

**Comment by alexellis** [comment]
@amalkh5

**Comment by alexellis** [comment]
Ref: https://github.com/lensapp/lens/issues/821

**Comment by max-ae** [comment]
`arkade` is now also available in the default Homebrew/core tap, so there is no more need for a third-party tap 😄

**Comment by Shikachuu** [comment]
@max-ae is right, I'll close this for now @alexellis.
