### ISSUE TITLE
Add Krew app

### ISSUE THREAD

**Issue by kylos101** [alexellis/arkade#210]
Any interest in having an app for [krew](https://krew.sigs.k8s.io/docs/user-guide/setup/install/)?

## Expected Behaviour
Install krew plugin for kubectl via `ark get krew`

## Current Behaviour
n/a

## Possible Solution
Add the `krew` app

## Steps to Reproduce (for bugs)
n/a

## Context
I'm troubleshooting Kong Ingress, and have multiple pod instances, and figure this might help per [this article](https://itnext.io/kubernetes-ingress-nginx-troubleshooting-made-easy-with-kubectl-plugins-dbc8fdff35fd). I'm using Loki Stack to peek at logs, so this isn't an immediate need. 👍 

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
tc/os-releaseLinux DESKTOP-11PAHMA 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

* What arkade version is this?

```
Version: 0.6.10
Git Commit: 08ce44c5a23ff95576f7ccdc7e6ea956a6cbd85e
```

**Comment by alexellis** [comment]
Thanks for the suggestion Kyle. 
What's inside krew.tar.gz? It doesn't appear to follow the patterns for different architectures, but I can see a .exe for Windows

**Comment by kylos101** [comment]
Doh! Sorry Alex, I'll take a peek and let you know.

**Comment by alexellis** [comment]
@kylos101 any update on this sir?

**Comment by kylos101** [comment]
Hi @alexellis thanks for the reminder. 

I see what you mean regarding the Github Release Assets for `Krew`. It doesn't appear to follow the same organizational structure as other tools (like `doctl`) - making it hard to leverage the current arkade pattern for downloading the right file for a given OS and CPU (at least w/o a code change).

For posterity, `krew.tar.gz` contains `krew.tar` which contains:
```
    krew-darwin_amd64
    krew-linux_amd64
    krew-linux_arm
    krew-windows_amd64.exe
    LICENSE
```

In hindsight, now that time has passed and I am rereading this, I'd prefer to delete this issue and only reopen if I provide a meaningful use case.

Here's hoping you got in a nice ride today! Have a good one.

**Comment by alexellis** [comment]
No worries. Thank you for the response 

Not riding much with all the rain 🌧️
