### ISSUE TITLE
[App] Sealed Secrets

### ISSUE THREAD

**Issue by Waterdrips** [alexellis/arkade#220]
## Expected Behaviour

- App https://github.com/bitnami-labs/sealed-secrets 
~~- CLI tool `kubeseal` added to tools?~~

This would be a useful app to provide for Arkade

**Comment by alexellis** [comment]
Sounds good to me. We already have `arkade get kubeseal` btw

**Comment by alexellis** [comment]
Thanks for picking this up. Have a look at the more recent apps in git history to understand how we are doing them now. Also think about the chart options and whether we need to block on arm (spoiler: we do have to)

**Comment by evalsocket** [comment]
No, today I will start and most probably create a pr forthis issue

**Comment by alexellis** [comment]
Hi @evalsocket is there anything we can help with? We do have Slack available if you want to chat.
