### ISSUE TITLE
[App] Octant

### ISSUE THREAD

**Issue by wahmedswl** [alexellis/arkade#227]
Please add [octant](https://octant.dev/) to the tool list, its great alternative to Kubernetes Dashboard.

thanks

**Comment by alexellis** [comment]
Hi @wahmedswl thanks for your interest in arkade. Can you tell us what format Octant is available in? Does it have a binary that we can download and run?

What architecture is it released for?

**Comment by wahmedswl** [comment]
@alexellis Octant provides binaries for every platform and are available in the releases, [https://github.com/vmware-tanzu/octant/releases/tag/v0.16.1](url). It needs ```kubeconfig``` or it can also be provided on start as well. I have installed it on Windows via their ```chocolatey``` package. They have well written installation instructions at [https://github.com/vmware-tanzu/octant](url).

Thanks

**Comment by alexellis** [comment]
I think Octant has been suggested in the past, but oh my goodness, the binary for MacOS is 83MB!

Feel free to start work on a PR for this @wahmedswl, or ping someone you may know at VMware to see if they want to contribute.

**Comment by wahmedswl** [comment]
Is there any app thats without k8s, seems like every app is hooked with k8s. Only simple download and run would be sufficient.

Thanks

**Comment by evalsocket** [comment]
@alexellis can this assign to me?

**Comment by Shikachuu** [comment]
@evalsocket are you still intrested?
