### ISSUE TITLE
[App] NGINX-Plus

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#234]
## Description

As part of the [Venafi Development Fund](https://venafi.com/blog/venafi-adds-30th-developer-machine-identity-management-development-fund), I've agreed to add NGINX-Plus to arkade to support Venafi customer needs.

"Production-Grade Application Delivery for Kubernetes"

https://www.nginx.com/products/nginx/kubernetes-ingress-controller/

https://github.com/nginxinc/kubernetes-ingress

To prevent confusion with `ingress-nginx` from @aledbf, I would be open to suggestions on naming. Perhaps `nginx-plus` or `nginx-inc`

Differences as explained by Nginx Inc: https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md

**Comment by nitishkumar71** [comment]
@alexellis ```nginx-inc``` would be better, as we can provide support for both OSS and Plus together. Please refer https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/#installing-via-helm-repository

we can expose two flags to enable plus version
1.  `nginxplus` for `controller.nginxplus`
2. `controller-image` for `controller.image.repository`

do let me know about your thoughts
