### ISSUE TITLE
[App] Add Kong IngressController

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#235]
## App

As part of the [Venafi Development Fund](https://venafi.com/blog/venafi-adds-30th-developer-machine-identity-management-development-fund), I've agreed to add Kong IngressController to arkade to support Venafi customer needs.

The openfaas community has also requested Kong Ingress and certain end-users make use of its OAuth capabilities, so it will be a win/win for everyone to have an app available

The openfaas-ingress app which generates ingress definitions should also be updated to have a matching ingress class option (if required).

More on GitHub:

https://github.com/Kong/kubernetes-ingress-controller

I would imagine this app being called `kong-ingress`

[helm instructions](https://github.com/Kong/kubernetes-ingress-controller#get-started)

```
$ helm repo add kong https://charts.konghq.com
$ helm repo update

# Helm 3
$ helm install kong/kong --generate-name --set ingressController.installCRDs=false
```

**Comment by nitishkumar71** [comment]
@alexellis I can pick this up.

**Comment by alexellis** [comment]
Sure, have you contributed before?

@Waterdrips what is the best app to use as a template? 

If Alistair doesn't get back in time, look at our most recently added app in git history as a template.

**Comment by Waterdrips** [comment]
Hello, good place to start looking is the Loki app, Ingess Nginx app or cert manager. Any questions let me know :)

**Comment by nitishkumar71** [comment]
> Sure, have you contributed before?
> 
> @Waterdrips what is the best app to use as a template?
> 
> If Alistair doesn't get back in time, look at our most recently added app in git history as a template.

@alexellis @Waterdrips Yes, I had worked on converting [Nginx App to use "new" pkg/apps/helm_app style](https://github.com/alexellis/arkade/issues/222)

**Comment by alexellis** [comment]
Added in #240 - thank you @nitishkumar71
