### ISSUE TITLE
Add Docker's "buildx" CLI to "arkade get"

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#242]
I'm starting to write code like this to upgrade buildx on various machines. It would be nice if we could download the binary via "arkade get"

On the releases page I also see Darwin, Windows and ARM :slightly_smiling_face: 

```bash
curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
```

**Comment by alexellis** [comment]
@rberrelleza would you like to take this one or #243 perhaps whilst you're hacking on the code?

**Comment by rberrelleza** [comment]
@alexellis buildx comes installed with docker CLI 19 (see https://docs.docker.com/buildx/working-with-buildx/#install). Do you still want a separate install?

**Comment by alexellis** [comment]
As I mentioned above, there are cases where it needs to be upgraded, particularly in CI.
