### ISSUE TITLE
kind not installable on Raspberry Pi (arm non-64)

### ISSUE THREAD

**Issue by mrsimpson** [alexellis/arkade#246]
## Expected Behaviour
When executing `arkade get kind` without additional flags, I'd expect the latest available version of kind to be installed.

## Current Behaviour
The download fails
```
Downloading kind
https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-linux-arm
Error: incorrect status for downloading tool: 404
``` 
The reason is that as of version `v0.9.0`, no releases for `arm` are published anymore, but only for `arm64`, see [the releases page](https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0)

## Possible Solution
As a user, I can work around the issue by specifying the exact version: 
```
arkade get kind --version=v0.8.1
```
However, it would be preferable that arkade itself suggested this or - better - worked around it (which of course is way more tricky)
Potential solutions (from cheap to expensive, probably)
1. If `404` is returned, suggest chosing a dedicated version for the given architecture, maybe pointing to the releases page
2. Check which of the earlier releases are available and install them, potentially with an information that the version installed is not the most current, but the most current for the given arch
3. Build from source

# Steps to Reproduce (for bugs)

1. execute `arkade get kind` on a raspbian based PI

## Context
I'm only ~playing~ learning locally, no production environment affected ;)

## Your Environment

* Raspberry Pi4, Raspbian
* What arkade version is this?
```
Version: 0.6.16
Git Commit: 9fbd7c330d63db42c66b4a463eb5fc1ac642d667
```

**Comment by alexellis** [comment]
Good to hear from you, I hope that you're doing well.

I'm sorry about KinD going away for RPi, but I think you'd have a much better experience with local k3s anyway

```
k3sup install --local
```

The "404" message is what we're going to use for the time-being. We could add another message after saying that a 404 means the binary may not be available for your given OS/architecture.
