### ISSUE TITLE
Istio installs unsupported version

### ISSUE THREAD

**Issue by howardjohn** [alexellis/arkade#25]
## Expected Behaviour
Applications should install supported versions

## Current Behaviour

https://github.com/alexellis/arkade/blob/master/cmd/apps/istio_app.go#L77 and unsupported version of Istio is installed: https://istio.io/news/support/announcing-1.3-eol-final/
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

**Comment by aidun** [comment]
I have to install a x86 cluster to test. I think I can make the required tests this afternoon or someone else would check my PR

**Comment by alexellis** [comment]
Thanks for your interest @howardjohn 👍

**Comment by howardjohn** [comment]
Thanks for updating!
