### ISSUE TITLE
Convert CI to GitHub Actions

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#262]
## Task 

Convert CI to GitHub Actions

## Context

Travis is removing its free tier for OSS projects, so this should be built with GitHub Actions instead, which is not going to add additional cost.

I would expect this to be one of the easier projects to convert given that Docker isn't used in the build.

See also:

https://github.com/mvdan/github-actions-golang
https://github.com/actions/create-release

**Comment by Waterdrips** [comment]
/close
duplicate of #263
