### ISSUE TITLE
[App] skopeo

### ISSUE THREAD

**Issue by developer-guy** [alexellis/arkade#265]
It would be nice if arkade supports a skopeo installation.

skopeo is a command-line utility that performs various operations on container images and image repositories.

here is for detail: https://github.com/containers/skopeo

**Comment by alexellis** [comment]
Is the a static binary for it? As I remembered, it needed several C libraries for GPG etc and had to be installed through brew.

**Comment by developer-guy** [comment]
yes you are right
![Screen Shot 2020-11-08 at 14 16 46](https://user-images.githubusercontent.com/16693043/98463563-19375100-21cd-11eb-9c6d-1c359512a2fd.png)

**Comment by alexellis** [comment]
Let's close this. And it's weird because I had the same idea as you yesterday and was thinking how we can manage it.

Perhaps printing a message "use brew"

Or finding another similar tool that doesn't need C libraries to work? @mattmoor had a suggestion for a similar tool.

**Comment by developer-guy** [comment]
There is more than one tool available for working registries 

One from Google :

https://github.com/google/go-containerregistry/blob/master/cmd/crane/doc/crane.md

One from regclient :


https://github.com/regclient/regclient

**Comment by mattmoor** [comment]
crane is pure Go, so `go get` should just work(tm).

There's also a public multi-arch image here:
```
# crane manifest gcr.io/go-containerregistry/crane | jq .
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 750,
      "digest": "sha256:a7df9d17f321c11f8d14d6ceeb325c7a2e38959109f18e4dd45a7dd2873b07ba",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 750,
      "digest": "sha256:59a61be66dfdee8cfb7d24e64901b2c6eb8b33f140495ac717509ba093fe60c8",
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 750,
      "digest": "sha256:24eb901541a7c443f0a1807c00f24e3ba8c0988b80cdb8be3114aedf8678a1f4",
      "platform": {
        "architecture": "ppc64le",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 750,
      "digest": "sha256:fa58c6ae7ceb51459c74a40b3787ebf396bed54cf64e3294c572baee37b9615a",
      "platform": {
        "architecture": "s390x",
        "os": "linux"
      }
    }
  ]
}
```

**Comment by developer-guy** [comment]
There is a static binary available on the releases page at this crane repo.
See for macOS:
https://github.com/google/go-containerregistry/releases/download/v0.1.4/go-containerregistry_Darwin_x86_64.tar.gz

![Screen Shot 2020-11-09 at 10 48 41](https://user-images.githubusercontent.com/16693043/98513677-4b05f180-2279-11eb-8ce1-bbc0c777ec7f.png)
