### ISSUE TITLE
Pin GitHub Actions to Go 1.13

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#269]
## Expected Behaviour

A specific Golang version should be used like the previous Travis build in the GitHub Actions for this project such as https://github.com/alexellis/arkade/blob/master/.github/workflows/ci-only.yml

## Current Behaviour

An unpredictable, but recent version is used.

## Possible Solution

Pin GitHub Actions to Go 1.13

See how Akos did this for the faas-netes repo https://github.com/openfaas/faas-netes/blob/master/.github/workflows/build.yaml

**Comment by alexellis** [comment]
This needs retro-fitting to the k3sup project.

**Comment by developer-guy** [comment]
I would like to take this, but I have questions about it.

Do we convert Makefile targets to per job in Github Actions?

**Comment by alexellis** [comment]
Please read the GitHub Action in this repo and compare it to the link I linked you to. You will see that the main difference is that one pins a Golang version.

Please can you do the same for arkade?

**Comment by developer-guy** [comment]
I think we can close this issue. @alexellis
