### ISSUE TITLE
docker-registry install fails due to missing chart on repo

### ISSUE THREAD

**Issue by TheEdgeOfRage** [alexellis/arkade#273]
## Expected Behaviour
When running `arkade install docker-registry` I expect it to install it to my cluster

## Current Behaviour
After running the command, I get the following error:

```
Using kubeconfig: /home/user/.kube/config
Client: x86_64, Linux
2020/11/15 11:13:36 User dir established as: /home/user/.arkade/
"stable" has been added to your repositories

Error: failed to fetch https://charts.helm.sh/stable/docker-registry-1.9.6.tgz : 404 Not Found
Error: exit code 1
```

The weird thing is that it says it tried to fetch it from `https://charts.helm.sh/`, but when I run `helm repo list`, I get the following

```
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
NAME    	URL                                             
openfaas	https://openfaas.github.io/faas-netes/          
stable  	https://kubernetes-charts.storage.googleapis.com
```

After running the command in the warning, it sets the correct repo for stable, but after rerunning `arkade install docker-registry`, it reverts back to the deprecated `kubernetes-charts.storage.googleapis.com` URL, even though the error from arkade still says `charts.helm.sh`.

I'm not sure which repos got deprecated and which not, but if I understood [this page](https://github.com/helm/charts/blob/master/README.md#status-of-the-project) correctly, `charts.helm.sh` is also deprecated?

## Possible Solution
When searching on artifacthub.io, this seems to be the only docker-registry chart available there:

https://artifacthub.io/packages/helm/twuni/docker-registry

I'm not sure whether that's the same that used to reside in the charts.helm.sh, but it might be a viable alternative.

## Steps to Reproduce (for bugs)
1. Run `arkade install docker-registry`

## Your Environment

* What Kubernetes distribution are you using?

k3s deployed with k3d

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"archive", BuildDate:"2020-10-16T20:58:56Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s2", GitCommit:"f8a4547bec36b4d1597c19c86b5063756d4c150e", GitTreeState:"clean", BuildDate:"2020-10-30T19:30:45Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

Linux chromium 5.9.8-arch1-1 #4 SMP PREEMPT Wed, 11 Nov 2020 23:11:48 +0000 x86_64 GNU/Linux


cat /etc/os-release

NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

* What arkade version is this?

```
arkade version

Version: 0.6.22
Git Commit: 690117d081d1ed750295361f1f54b8161d80adc2
```

**Comment by alexellis** [comment]
I can confirm that I'm getting the same error.

```bash
[root@nuc ~]# arkade version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.6.22
Git Commit: 690117d081d1ed750295361f1f54b8161d80adc2
[root@nuc ~]# kubectx
Default
[root@nuc ~]# arkade install docker-registry
Using kubeconfig: 
Using Kubeconfig: /var/lib/rancher/k3s/server/cred/admin.kubeconfig
Client: x86_64, Linux
2020/11/15 11:00:37 User dir established as: /root/.arkade/
https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz
/tmp/linux-amd64 linux-amd64/
/tmp/helm linux-amd64/helm
/tmp/README.md linux-amd64/README.md
/tmp/LICENSE linux-amd64/LICENSE
2020/11/15 11:00:49 extracted tarball into /tmp: 3 files, 0 dirs (485.721063ms)
Downloaded to:  /root/.arkade/bin/helm helm
"stable" has been added to your repositories

Error: failed to fetch https://charts.helm.sh/stable/docker-registry-1.9.6.tgz : 404 Not Found
Error: exit code 1
[root@nuc ~]# 
```

This is probably going to affect all charts that were in stable. We have already moved ingress-nginx, Mongo and a few others to the new upstreams. I'm shocked that the upstream maintainers just deleted these chart artifacts without providing an alternative.

**Comment by alexellis** [comment]
From: https://helm.sh/docs/faq/#i-am-getting-a-warning-about-unable-to-get-an-update-from-the-stable-chart-repository

You can run the following command to fix your repository:

```
$ helm repo add stable https://charts.helm.sh/stable --force-update  
```

**Comment by alexellis** [comment]
This is giving a 404 for docker-registry despite being listed in the index.yaml 🤦 

https://charts.helm.sh/stable/index.yaml

`https://charts.helm.sh/stable/docker-registry-1.9.6.tgz` <- 404

**Comment by alexellis** [comment]
jFrog's chart centre has a mirror which is actually working -> https://chartcenter.io/stable/docker-registry

**Comment by alexellis** [comment]
I looked into this then raised #274 - but was subsequently told by the helm maintainers that the 404 is a bug on their side, and that they were restoring the release aritfacts. See the notes on 274 and check your version of arkade.

**Comment by goncalo-oliveira** [comment]
> This is giving a 404 for docker-registry despite being listed in the index.yaml 🤦
> 
> https://charts.helm.sh/stable/index.yaml
> 
> `https://charts.helm.sh/stable/docker-registry-1.9.6.tgz` <- 404

The `index.yaml` seems to be updated, it's now `https://charts.helm.sh/stable/packages/docker-registry-1.9.6.tgz`

**Comment by goncalo-oliveira** [comment]
I also had the same issue using version `0.6.23`. Installing the latest `0.6.28` fixed this.

**Comment by alexellis** [comment]
Perfect. Thanks
