### ISSUE TITLE
Support issue WSL and helm binary

### ISSUE THREAD

**Issue by TheDemonCat** [alexellis/arkade#285]
When I try to get helm, I get a 404 error.

## Expected Behaviour
A 200 response, with helm having been successfully gotten.

## Current Behaviour
>arkade get helm         
Downloading helm
https://get.helm.sh/helm-v3.2.4-msys_nt-10.0-19041-amd64.tar.gz
Error: check with the vendor whether this tool is available for your system: incorrect status for downloading tool: 404

## Steps to Reproduce (for bugs)
1. use arkade version: 0.6.25
2. use wsl2
3. arkade get helm

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

```
HOST
>uname
MSYS_NT-10.0-19041

WSL2
$ uname -a
Linux DESKTOP-KT3E0CJ 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
uname -a

cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* What arkade version is this?

```
arkade version: 0.6.25
```

**Comment by alexellis** [comment]
What do you mean here when you say "host" and then separately say "WSL2" with a different value?

Which system are you running arkade within?

**Comment by TheDemonCat** [comment]
I am using win 10 with wsl2 installed. Arkade I run in windows OS.

**Comment by alexellis** [comment]
/set title: Support issue WSL and helm binary

**Comment by alexellis** [comment]
For Windows you must run arkade either in git bash, or in WSL, not in cmd.exe or powershell.

Please share a screenshot? cc @nunix

**Comment by nunix** [comment]
Hi,

I do confirm that the only way I could reproduce something similar is by downloading the `arkade.exe` and run it from CMD as @alexellis mentions (it actually tries to download the ARM version for Helm):
![image](https://user-images.githubusercontent.com/905874/101179058-0ee06980-364a-11eb-857b-32d04ff4d526.png)

And if I run it from WSL2 directly (mind that I downloaded the v0.6.25 directly, the latest install is v0.6.28) it works as intended:
![image](https://user-images.githubusercontent.com/905874/101179034-06882e80-364a-11eb-8df5-298a1ec3e8d4.png)

Can you share screenshots maybe?

Hope this helps

**Comment by TheDemonCat** [comment]
If I am using [arkade.exe](https://github.com/alexellis/arkade/releases/download/0.6.28/arkade.exe) version then errors like this:

windows
![image](https://user-images.githubusercontent.com/26283990/101187487-a2339200-367e-11eb-89b3-53837bcb1809.png)

wsl2
![image](https://user-images.githubusercontent.com/26283990/101187535-af508100-367e-11eb-91c1-90fc8d264b69.png)

If I use the [linux](https://github.com/alexellis/arkade/releases/download/0.6.28/arkade) version in wsl2 then it installs correctly
![image](https://user-images.githubusercontent.com/26283990/101188232-a0b69980-367f-11eb-9402-d743bd2b2aaf.png)

**Comment by nunix** [comment]
ok so Alex was right and it confirms my tests too.

So, as Alex stated, please **do not** use the arkade.exe on Windows. Actually, not sure what is/was the purpose there except, maybe, for the git bash integration?

As you know, you can leverage Windows binaries from WSL2, however the said binaries need to be working _for_ Windows.
Your best and safest bet is to use the linux binary on WSL2 and if by any chances you want to call it from Powershell/CMD then use `wsl -d <distribution name> -e arkade get helm` (for example, and you can even drop the "-d" part if you want to target the default WSL2 distribution)

**Comment by TheDemonCat** [comment]
No problems. I just expected the version arkade.exe to work in  Powershell / CMD

**Comment by alexellis** [comment]
We detail this in the README as *not supported*.

I'm going to close the issue, but thanks for using arkade and for getting in touch.

**Comment by r-darwish** [comment]
@alexellis Just being curious - can you explain how deeply does arkade relies on bash? Do you think it will take a reasonable amount of work to remove this dependency?

**Comment by alexellis** [comment]
Hi, I'm not sure how to help you here, because you're asking a deeply technical question with no context. 

Alex

**Comment by r-darwish** [comment]
It's more like asking if maybe I can help. What I mean to ask is whether the fact that arkade depends on bash is something temporary that you would like to get rid of in the future or is it too deeply integrated into the tool and cannot be removed.

**Comment by alexellis** [comment]
I still don't understand what you're trying to do and why the use of bash causes you problems?

Can you explain as if we'd never spoken before (we haven't) and like you'd given me no context yet (you haven't)?

**Comment by r-darwish** [comment]
I will try. What mostly makes Go applications so appealing is that they compile to a static binary that have all dependencies inside it, which makes them easy to install, and the also tend to work in Windows out of the box because they mostly require no external dependency.

So what I'm saying here that requiring bash as an external dependency is somewhat of... a burden, I suppose? It makes Windows support a bit more tricky because you have to run it either from WSL or bash git, which isn't the case for other tools such as kubectl.

So I wonder whether the functionality that bash provides for arkade can be replaced by some Go library, which will make arkade a bit more standalone executable, and easier to launch in Windows.

**Comment by ejsmith** [comment]
What @r-darwish said. :-) It just would be nice to be able to run arkade from a cmd or powershell terminal just like I can run `kubectl`, `kubectx`, ``kubens` and `help` from powershell on Windows without having to go into WSL or Git Bash.
