### ISSUE TITLE
[Feature] Move lib code from cmd/app/kubernets_exec.go to pkg

### ISSUE THREAD

**Issue by aidun** [alexellis/arkade#29]
Currently app code and lib code is scattered in `cmd/apps/kubernetes_exec.go` and `pkg`. This is a bit misleading and should be changed.

## Expected Behaviour

All shared code should be placed under `pkg`.

## Current Behaviour

The functions will not be private, they will be public.

## Possible Solution

I suggest to move the helm related code to `pkg/helm` and the Kubernetes related code to `pkg/kubernetes`.

Based on this there are three possible ways:

1. keep the old functions in `cmd/apps/kubernetes_exec.go` as stubs and call from there the new functions.
```
import "pkg/kubernetes"
func kubectl(....) error {
   return kubernetes.Kubectl(...)
}
```

2. keep the old functions in `cmd/apps/kubernetes_exec.go` and create new ones under `pkg/kubernetes`and `pkg/helm`

3. move complete to the new structure and modify all apps at once.

I would suggest the third solution.

## Context
I try to split the command from the packages to provide a cleaner codebase for further improvments.

**Comment by aidun** [comment]
Is it worth it to provide a WIP-PR?

**Comment by Waterdrips** [comment]
/close 

This has happened as part of #21 I think
