### ISSUE TITLE
always include architecture and OS in releasename

### ISSUE THREAD

**Issue by deknos** [alexellis/arkade#298]
i would ask you to rename your release artifacts that they always include architecture and Operating System in your binaryname for easiert distinguishment

## Expected Behaviour
instead of arkade, use arkade-amd64-linux and instead of arkade-armhf-linux.

## Current Behaviour
i use binenv (https://github.com/devops-works/binenv) and would like to include your binary there via pullrequest. This is hard, if there's no consistent naming in the release artifacts

## Possible Solution

sorry i have no idea how you do releases, nor atm i am knowledged about github actions.

I would also appreciate it, if you would include binenv in your toollist which could be installed. and i would set a pullrequest for binenv or you do it yourself.

because the less curl | bash calls we have, the better.

**Comment by alexellis** [comment]
arkade actually does the same job as binenv and was written much earlier, first in the k3sup project and then ported over to its own project.

OpenFaaS, inlets, k3sup, arkade and others are all released with the same format. You can see how we determine the rules in our get.go package.

https://github.com/alexellis/arkade/blob/master/pkg/get/get.go

And our unit tests which exercise the paths:

https://github.com/alexellis/arkade/blob/master/pkg/get/get_test.go

Whilst I sympathise with you on the lack of standard naming and formatting for binaries (believe me, I know - I've been writing code like this for years), perhaps binenv could benefit from a more flexible approach?
