### ISSUE TITLE
HashiCorp products are not using the latest versions as the default.

### ISSUE THREAD

**Issue by phillipsj** [alexellis/arkade#301]
## Expected Behaviour

When executing the following command I expect version 0.14.3 of Terraform to be the version that is installed, not 0.13.1. The same thing happens when installing Packer.

```
arkade get terraform
```
## Current Behaviour

By default Arkade installs older versions of both Packer and Terraform.

## Possible Solution

Update the default values for version to the latest release.

## Context

I just recently started using Arkade to installing tools and those tools are older versions than I typically use. I was able to install by passing the version flag. That just may not be what is expected by most users as they wouldn't know what version gets installed by default with reading the source.

* What arkade version is this?

0.6.5

**Comment by alexellis** [comment]
Hey @phillipsj

You can also run `--version` to pass in an override :slightly_smiling_face: and I guess that you're probably best always passing `--version` for tutorials anyway..

Were you waiting for someone to give you an OK to send a pull request?

Alex

**Comment by phillipsj** [comment]
I submitted a PR. It's out there.
