### ISSUE TITLE
get yq fails with 404

### ISSUE THREAD

**Issue by jceb** [alexellis/arkade#303]
## Expected Behaviour
Executing `arkade get yq` should install `yq`

## Current Behaviour
The following error message is shown:

```
Downloading yq
https://github.com/mikefarah/yq/releases/download/v4.2.1/yq
Error: check with the vendor whether this tool is available for your system: incorrect status for downloading tool: 404
```

## Steps to Reproduce (for bugs)
1. Install ArchLinux .. or I guess any other Linux system
2. Run `arkade get yq`

## Context
Would be great to have `yq` through arkade.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Linux torch 5.4.86-1-lts #1 SMP Wed, 30 Dec 2020 21:01:35 +0000 x86_64 GNU/Linux

cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

* What arkade version is this?

```
arkade version

Version: 0.6.25
Git Commit: ccee0f731397c59917ff72e64794f08748c921a3
```

**Comment by alexellis** [comment]
I can reproduce this on Linux.

@nitishkumar71 please could you take this on and submit a fix in a PR?

**Comment by jceb** [comment]
:+1:
