### ISSUE TITLE
$KUBECONFIG not honored by internal helm call

### ISSUE THREAD

**Issue by didi-home** [alexellis/arkade#309]
While using "arkade install", on execution of internal helm binary, $KUBECONFIG from logged-in user env is not honored.
It seems it is expecting the config to be at ~/.kube/config
(Command: /root/.arkade/bin/helm)

## Expected Behaviour
the kube config configured in $KUBECONFIG should be read

## Current Behaviour
```
# arkade install openfaas
Using Kubeconfig: /etc/rancher/k3s/k3s.yaml
Using kubeconfig:
Node architecture: "amd64"
Client: "x86_64", "Linux"
2021/01/14 09:41:59 User dir established as: /root/.arkade/
Using Kubeconfig:
[Warning] unable to create secret basic-auth, may already exist: Error from server (AlreadyExists): secrets "basic-auth" already exists
"openfaas" has been added to your repositories

VALUES values.yaml
Command: /root/.arkade/bin/helm [upgrade --install openfaas openfaas/openfaas --namespace openfaas --values /tmp/charts/openfaas/values.yaml --set gateway.directFunctions=true --set openfaasImagePullPolicy=IfNotPresent --set faasnetes.imagePullPolicy=Always --set basicAuthPlugin.replicas=1 --set gateway.replicas=1 --set queueWorker.replicas=1 --set queueWorker.maxInflight=1 --set clusterRole=false --set serviceType=NodePort --set ingressOperator.create=false --set basic_auth=true --set operator.create=false]
Error: Kubernetes cluster unreachable
Error: exit code 1, stderr: Error: Kubernetes cluster unreachable

# /root/.arkade/bin/helm ls -A
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
traefik kube-system     4               2021-01-13 17:22:32.72888941 +0000 UTC  deployed        traefik-1.81.0  1.7.19
```
Please note that calling the helm binary on its own works correctly, it just does not when executing by "arkade".

## Steps to Reproduce (for bugs)
1. move your kube config from ~/.kube/config to somewhere else
2. set $KUBECONFIG to new path
3. test ~/.arkade/bin/helm ls -A  -> this should work
4. test arkade install openfaas -> this will not work

reverse test for me worked, when I copied /etc/rancher/k3s/k3s.yaml to ~/.kube/config, it worked.

## Context
Since I'm using k3s, I set $KUBECONFIG in my .bashrc. All other tools seem to be working fine with this setting.

## Your Environment
```
VERSION:
   v1.20.0+k3s2 (2ea6b163)
```
+bundled kubectl

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux dodo6 5.4.72-gentoodidi #1 SMP Thu Nov 19 17:42:11 CET 2020 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz GenuineIntel GNU/Linux

Gentoo/Linux
```

* What arkade version is this?

```
            _             _
  __ _ _ __| | ____ _  __| | ___
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.6.37
Git Commit: 1038de3c2013fa390c024d9c9951d7e6eb332515
```

**Comment by alexellis** [comment]
You must not run arkade as root. I can put code in to prevent it, and maybe that's the only answer?

If you would like technical assistance, please join slack.

K3sup and arkade are not designed to be run on your master. Run them from your client and you should be fine.
