### ISSUE TITLE
[Bug] wait flag on install commands is missing

### ISSUE THREAD

**Issue by aidun** [alexellis/arkade#31]
Every app can implement a --wait flag. The flag is provided by `cmd/install.go`. The definition of the flag is missing.

## Expected Behaviour

Every sub command of install should have the ability to use the --wait flag

## Current Behaviour

The commands fail with an error if you provide the flag.

## Possible Solution
Provide something similar to this in the install command:
```
command.PersistentFlags().Bool("wait", false, "Wait for the commands to finish")
```

## Steps to Reproduce (for bugs)
1. git checkout master
2. go build
3. ./arkade install openness --wait
4.

## Your Environment
 not needed

**Comment by aidun** [comment]
@Waterdrips found point where it got lost:

https://github.com/alexellis/k3sup/commit/6184746be85963f66fa0f0b8a1a4111d35959a3e#diff-9062f38da02df2d6f4a859a669b5b08dL36

**Comment by Waterdrips** [comment]
@aidun thanks, did you want to raise a PR to put it back in?

**Comment by aidun** [comment]
Im already on it

________________________________
Von: Alistair Hey <notifications@github.com>
Gesendet: Wednesday, March 4, 2020 8:37:04 AM
An: alexellis/arkade <arkade@noreply.github.com>
Cc: Markus Hartmann <markush1986@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [alexellis/arkade] [Bug] wait flag on install commands is missing (#31)


@aidun<https://github.com/aidun> thanks, did you want to raise a PR to put it back in?

**Comment by aidun** [comment]
Derek assign: me

**Comment by Waterdrips** [comment]
> Derek assign: me

You need to be in the Derek file to use the commands, 

/assign: aidun

**Comment by aidun** [comment]
okay, that makes sense :/
