### ISSUE TITLE
`arkade install APP --set` doesn't work for all apps

### ISSUE THREAD

**Issue by rhorridge** [alexellis/arkade#311]
Discovered with Redis but applies to a number of apps.

## Expected Behaviour
`arkade install redis --set` => `Error: flag needs an argument: --set`

## Current Behaviour
`arkade install redis --set` => `Error: unknown flag: --set`

The following apps appear to be affected:
```
argocd
crossplane
docker-registry
docker-registry-ingress
info
kube-image-prefetch
kubernetes-dashboard
linkerd
metrics-server
openfaas-ingress
osm
portainer
redis
registry-creds
tekton
```

## Possible Solution
I notice that the `--set` flag is not documented for these apps - is this intended? Otherwise it would need to be implemented and documented for each of the affected apps.

## Steps to Reproduce (for bugs)
1. `arkade install redis --set`

## Context
Attempting to set Helm parameters to enable TLS. Minimum working example provided above.

## Your Environment

* What Kubernetes distribution are you using?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"archive", BuildDate:"2021-01-12T17:24:21Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+k3s2", GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11", GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
$ uname -a
Linux kraid 5.4.80-gentoo-r1 #3 SMP Fri Dec 4 12:21:45 GMT 2020 x86_64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz GenuineIntel GNU/Linux
$ cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

* What arkade version is this?

```
$ arkade version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.7.0
Git Commit: 5adda6b8be6ae3f985289237ae5a72a1596fc07c
```

**Comment by Waterdrips** [comment]
Hey @rhorridge Thanks for the issue! 

Ill take a look at those apps.

I can see straight away that some of those apps wont have a `--set` because they are not helm based commands. (docker-registry-ingress for example is just yaml files appled) 

There are some `--set` missing from others which do use helm. Ill get those added soon

**Comment by Waterdrips** [comment]
Places to check: 

- [ ] argocd
- [ ] crossplane
- [ ] docker-registry
- [ ] docker-registry-ingress
- [ ] info
- [ ] kube-image-prefetch
- [ ] kubernetes-dashboard
- [ ] linkerd
- [ ] metrics-server
- [ ] openfaas-ingress
- [ ] osm
- [ ] portainer
- [ ] redis
- [ ] registry-creds
- [ ] tekton

**Comment by rhorridge** [comment]
Thanks, much appreciated! Let me know if I can help with anything.
