### ISSUE TITLE
Namespace warning when when installing openfaas

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#317]
We're getting a namespace warning when when installing openfaas

## Expected Behaviour

A fresh installation would give no warnings

## Current Behaviour

```
[Warning] unable to create namespace openfaas, may already exist: Error from server (AlreadyExists): namespaces "openfaas" already exists
Client: armv7l, Linux
```

## Possible Solution

Just apply from the YAML file, don't try to create the namespaces again

## Steps to Reproduce (for bugs)

1. Create a cluster with kind
2. arkade install openfaas

## Context

I just ran into this and it was confusing for a user on Slack too, see in #home-clusters

**Comment by alexellis** [comment]
@Waterdrips PTAL?

**Comment by Waterdrips** [comment]
PR opened #318
