### ISSUE TITLE
ingress-nginx appears twice in 'arkade install --help'

### ISSUE THREAD

**Issue by antoineco** [alexellis/arkade#319]
I played with `arkade` for the first time today and noticed this in the output of the aforementioned command:

```
  gitlab                  Install GitLab
  grafana                 Install grafana
  info                    Find info about a Kubernetes app
  ingress-nginx           Install ingress-nginx
  ingress-nginx           Install ingress-nginx
  inlets-operator         Install inlets-operator
  istio                   Install istio
```

Just a small detail but I thought I could report anyway.

**Comment by alexellis** [comment]
@nitishkumar71 would you like to take this?

**Comment by nitishkumar71** [comment]
Sure @alexellis .
Thanks @antoineco for raising it.

**Comment by antoineco** [comment]
@nitishkumar71 @alexellis I couldn't assign myself but just sent a PR ☝️  Feel free to close it if that work has already been done.
