### ISSUE TITLE
Update docs and help flag for inlets-operator

### ISSUE THREAD

**Issue by antoineco** [alexellis/arkade#320]
The docs at https://docs.inlets.dev/#/tools/inlets-operator mention

> --license $LICESNE # inlets-pro license file. (Omit **if using inlets OSS**)

_(side note: notice the typo in the var)_

But when I try to install the operator using `arkade`, I'm denied the installation with:

```console
$ arkade install inlets-operator -p ec2 --token-file ~/.aws/key --secret-key-file ~/.aws/secret
Error: an inlets PRO license is required for the inlets-operator
```

Even the output of `--help` says

>  -l, --license string            The license key **if** using inlets-pro

Did the model change recently to "paid only" or is it a bug in `arkade`? (first time user)

**Comment by alexellis** [comment]
We'll get the docs updated. 👍 

The inlets-operator's README is all up to date:

https://github.com/inlets/inlets-operator

https://github.com/inlets/inlets-operator/issues/117

Btw, we have also allowed inlets PRO for personal use at work, so if you find value in the project, please consider supporting it. As a side effect you'll have secure infrastructure, where we previously warned against using the OSS version that way in the README.

[inlets PRO tiers](https://inlets.dev/pricing) - sponsors get 10% extra off

**Comment by alexellis** [comment]
@utsavanand2 do you mind removing any reference in the inlets docs to the OSS version of the proxy with the inlets-operator? I think I have covers most of it in https://github.com/inlets/docs/commit/fbecf716b53ef313e8b203d4e0fa313d9fc314c8

**Comment by alexellis** [comment]
I think we are covered now. If you see anything else, just paste the link here - @utsavanand2 is also going to take a quick pass over content.

**Comment by antoineco** [comment]
/reopen
because the flag is still misleading:

https://github.com/alexellis/arkade/blob/6680f8346be4a57a7edd345b1dca0c10e8d61234/cmd/apps/inletsoperator_app.go#L40

/assign: antoineco

**Comment by utsavanand2** [comment]
@antoineco I see why you got confused, and I'm updating the docs accordingly, but still to clarify
If you have the contents of the license in an env var, or want to just paste the license key use `--license` or `-l` flag.
If you have the license in a text file, you can provide the path to the license text file using the `--license-file` or `-f` flag.

**Comment by antoineco** [comment]
@utsavanand2 yes that part is clear, I just installed `arkade` thinking I would be able to use it to deploy some free software and it took me some time to research the project an figure out it wasn't the case. I figured I could clarify the wording of the flag since it says

**if using inlets-pro**

but there is no such thing as not using inlets-pro. That's it :) I think the issue is solved now.
