### ISSUE TITLE
Add natscli download

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#324]
The natscli can be used with nats that comes with openfaas/faasd

https://github.com/nats-io/natscli/releases/

Example use-case where I needed this -> https://lucasroesler.com/posts/2021/event-driven-faasd-with-postgres/ from @LucasRoesler

**Comment by alexellis** [comment]
@developer-guy or @nitishkumar71 would you like to take this one?

**Comment by developer-guy** [comment]
yes, I would like so 🙏
