### ISSUE TITLE
linkerd2 fails to download

### ISSUE THREAD

**Issue by HarryGogonis** [alexellis/arkade#327]
Downloading the linkerd2 client binary fails

## Expected Behaviour
`ark get linkerd2` installs linkerd2

## Current Behaviour
```sh
arkade get linkerd2 -v stable-2.9.2
Downloading linkerd2
https://github.com/linkerd/linkerd2/releases/download/stable-2.9.2/linkerd2-cli-stable-2.9.2-linux
Error: check with the vendor whether this tool is available for your system: incorrect status for downloading tool: 404
```
## Possible Solution
append the arch to download URL

## Steps to Reproduce (for bugs)

1. `arkade get linkerd2 -v stable-2.9.2`

## Context
Can't install linkerd2 with arkade

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a                                                                                                                                             
Linux buildkitsandbox 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86
_64 GNU/Linux
cat /etc/os-release      
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
```

* What arkade version is this?

```
Version: 0.7.1
Git Commit: 6680f8346be4a57a7edd345b1dca0c10e8d61234
```

**Comment by alexellis** [comment]
Hi thanks for the issue.

I'm confused as to why `2.9.0` would give a 404? Did the Linkerd team delete the binary for that release? Why does changing `2.9.1` fix the issue?

Alex

**Comment by alexellis** [comment]
I'll merge as I saw the same as yourself. Do we know why? cc @wmorgan

**Comment by alexellis** [comment]
Here's the latest release -> https://github.com/alexellis/arkade/releases/tag/0.7.2

**Comment by wmorgan** [comment]
We removed that specific release. See text at https://github.com/linkerd/linkerd2/releases/tag/stable-2.9.0
