### ISSUE TITLE
arkade get mc fails on Linux ARM (RaspberryPi)

### ISSUE THREAD

**Issue by jasonprado** [alexellis/arkade#330]
## Expected Behaviour
`$ arkade get mc` should download and install the minio client (mc) to `~/.arkade`

## Current Behaviour
```
$ arkade get mc
Downloading mc
{$arch = "arm"}}

                        https://dl.min.io/client/mc/release/linux-armv7l/mc
Error: check with the vendor whether this tool is available for your system: parse "{$arch = \"arm\"}}\n\t\t\t\n\t\t\thttps://dl.min.io/client/mc/release/linux-armv7l/mc": net/url: invalid control character in URL
```

The URL seems to include a more specific description of the architecture, `linux-armv7`. There is a URL on min.io: `https://dl.min.io/client/mc/release/linux-arm/mc`, which should probably be referred to.

## Possible Solution
Change how the `mc` URL is generated to specify `linux-arm` or work with the minio team to standardize their URL paths.

## Steps to Reproduce (for bugs)

1. Run raspbian 32-bit on a Raspberry Pi.
2. Install arkade. Verify arkade works for other tools.
3. `arkade get mc`

## Context

I'll have to install `mc` manually or another way. `arkade install minio` seemed to work.

## Your Environment

* What Kubernetes distribution are you using?
Not applicable.
```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
$ uname -a
Linux k3s-rpi1 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"```

* What arkade version is this?

```
$ arkade version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.7.1
Git Commit: 6680f8346be4a57a7edd345b1dca0c10e8d61234
```

**Comment by alexellis** [comment]
Hi @jasonprado are you open to submitting a PR to fix this for armv7?

Alex

**Comment by jasonprado** [comment]
I wasn't planning on it but sure I can try and fix it.

**Comment by alexellis** [comment]
Thanks.

Let us know if you need any help setting up or sending your first PR. Cc @nitishkumar71 @yankeexe

**Comment by jasonprado** [comment]
I'm a GitHub newbie so let me know if there's anything else I should do with this PR: #331

**Comment by jasonprado** [comment]
I added a test (and found an additional bug): #332

**Comment by nitishkumar71** [comment]
@jasonprado Thanks for correcting it, somehow I missed these thing in test case.
