### ISSUE TITLE
[feature request] we need to add falco as an app

### ISSUE THREAD

**Issue by developer-guy** [alexellis/arkade#347]
we can support Falco the container runtime security tool as an app, they have charts that we can use.
https://github.com/falcosecurity/charts 

## Expected Behaviour

```bash
$ arkade install falco --set falcosidekick.enabled=true
```
This command should install the Falco to the cluster using its Helm chart.

## Current Behaviour

There is no solution exist yet for Falco.

## Possible Solution

We can use the Helm charts of Falco to install it to the cluster. I mentioned the link above for the Helm charts of the Falco.

## Context

Falco is a very popular project in the container runtime security area, so, it would be nice if we can support the installation of the Falco in arkade.

## Your Environment

* What Kubernetes distribution are you using?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
$ uname -a
Darwin Batuhan-MBP.home 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```

**Comment by developer-guy** [comment]
I'm a volunteer to do this issue. 👍

**Comment by alexellis** [comment]
@developer-guy please spend more time on filling out this issue template, it seems rushed.

**Comment by developer-guy** [comment]
@alexellis I tried to add all the details in a proper way, can you review it, thank you.
