### ISSUE TITLE
add tekton cli to tools

### ISSUE THREAD

**Issue by tuananh** [alexellis/arkade#348]
add tekton cli for tools. since we already have tekton app, maybe this should be added too.

i was trying out tekton and it fails when installing cli :)

```
arkade get tekton
Error: cannot get tool: tekton
```

they support lots of os & platforms https://github.com/tektoncd/cli/releases

![image](https://user-images.githubusercontent.com/627278/109542253-6a11e300-7af7-11eb-8aed-dc26143dcf2d.png)

**Comment by alexellis** [comment]
Happy for you to do this @tuananh - do you want to go ahead with your PR?
