### ISSUE TITLE
Update Istio app to use istioctl and 1.8

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#350]
Update Istio app to use istioctl and 1.8

## Expected Behaviour

Istio 1.18 is now available and is installed via a CLI (similar to how Linkerd works)

## Current Behaviour

Still using the older helm chart

## Possible Solution

Update https://github.com/alexellis/arkade/blob/master/cmd/apps/istio_app.go

* Add `istioctl` as an app to `arkade get` (in `tools.go`)
* Use `istioctl` to install Istio

In addition, consider using @stefanprodan's defaults from his Flagger e2e tests for a minimal installation. 

https://github.com/fluxcd/flagger/commit/a2774d92da8cea75ad1dc0615338cef28143c6a0#diff-e608f1fdaeb7eddba9483ae06ebbc5eccf7ceaa4c6c5044084ebe8d4cef1242eR15-R17

## Context

https://github.com/openfaas/faas-netes/issues/714#issuecomment-789156173

**Comment by howardjohn** [comment]
Any reason to prefer 1.8 vs 1.9?

let me know if you run into any issues

**Comment by nitishkumar71** [comment]
I will work on it.

**Comment by alexellis** [comment]
Thank you @nitishkumar71
