### ISSUE TITLE
[APP] kyverno 

### ISSUE THREAD

**Issue by evalsocket** [alexellis/arkade#371]
Kyverno is a popular policy engine for Kubernetes, it would be awesome if Akade supported the installation.

## Expected Behaviour
`arkade install kyverno` would install and configure kyverno for K8s

Happy to PR this.

## Current Behaviour
Not Exist

## Possible Solution
The Kyverno Helm chart https://github.com/kyverno/kyverno/tree/main/charts/kyverno can be used to install kyverno. 

## Steps to Reproduce (for bugs)
NA

## Context
NA

## Your Environment

* K3d

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:54Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}

```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
$ uname -a
Darwin
```

* What arkade version is this?

```
$ arkade version
Version: 0.7.1
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [X] Yes
- [ ] No

**Comment by alexellis** [comment]
Please can you fill out the whole issue template including the fields that you deleted 🤷‍♂️

**Comment by alexellis** [comment]
@evalsocket please see my comment, or we'll need to close your issue and PR if you don't respond.
