### ISSUE TITLE
[APP] k9s

### ISSUE THREAD

**Issue by hholst80** [alexellis/arkade#373]
Pre-approval to package K9s tool for installation with Arkade?

https://k9scli.io/

```sh
➜  ~ which k9s
~/.local/bin/k9s
➜  ~ ldd `which k9s`
	not a dynamic executable
➜  ~ 
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [ ] Yes
- [x] No

**Comment by alexellis** [comment]
We already have K9s, so I'm confused what you're asking for here?

Can you elaborate @hholst80?

See also:
https://github.com/alexellis/arkade/blob/master/pkg/get/tools.go#L381

**Comment by hholst80** [comment]
Oh, I could not see it and it seemed like an obvious oversight. 

Well, on my part then it seems. We can close this. Thank you!
