### ISSUE TITLE
Bump docker-compose version

### ISSUE THREAD

**Issue by ryantfowler** [alexellis/arkade#374]
Arkade currently fetches `docker-compose` 1.27.4, and the most recent version is [1.29.1](https://github.com/docker/compose/releases/tag/1.29.1)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```
0.7.13
## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [ ] Yes
- [X ] No

**Comment by alexellis** [comment]
@developer-guy do you want to take a look at this please?

**Comment by alexellis** [comment]
@ryantfowler thanks for your interest here. We'll take a look. Are you aware of the `--version` flag that you can pass in?

**Comment by developer-guy** [comment]
> @ryantfowler thanks for your interest here. We'll take a look. Are you aware of the `--version` flag that you can pass in?

Hello @ryantfowler, yeah Alex is right, I just tested the installation of the docker-compose 1.29.1 with the following command
`arkade get docker-compose --version=1.29.1`

Everything is working, so, can you please the same command above 🙏

**Comment by ryantfowler** [comment]
Hi @alexellis I did stumble across the `--version` flag after opening this PR, and I was successful in installing the latest version of `docker-compose` with it. I was under the impression that there might be a desire to update the default version. My apologies if I misunderstood how this project usually goes about handling that.

@developer-guy I can confirm that I am able to download `1.29.1` with the command that you have shared above.

Thank you

**Comment by alexellis** [comment]
@developer-guy happy for you to send a PR to update the version to the latest :+1:

**Comment by developer-guy** [comment]
> @developer-guy happy for you to send a PR to update the version to the latest :+1: 

Of course, Im going to do that soon @alexellis
