### ISSUE TITLE
Error: open /tmp/portainer.yaml: permission denied

### ISSUE THREAD

**Issue by cmonty14** [alexellis/arkade#388]
## Expected Behaviour

Installing portainer with arkade should complete w/o error.

## Current Behaviour

Trying to install portainer fails with this error:
`Error: open /tmp/portainer.yaml: permission denied`

## Steps to Reproduce (for bugs)

1. curl -sLS https://dl.get-arkade.dev | sudo sh 
2. ark get helm
3. sudo mv /root/.arkade/bin/helm /usr/local/bin/
4. sudo chmod 755 /usr/local/bin/helm
5. ark install portainer   

## Context

After setup k3s HA on 3 node cluster I want to install some applications.
## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2021-01-14T10:55:09Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Linux pc4-pve 5.4.106-1-pve #1 SMP PVE 5.4.106-1 (Fri, 19 Mar 2021 11:08:47 +0100) x86_64 GNU/Linux

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* What arkade version is this?

```
arkade version
Version: 0.7.13
Git Commit: a7418b1652e1f96c6f86985572c828a96d136836
```

## Are you a GitHub Sponsor (Yes/No?)
Check at: https://github.com/sponsors/alexellis
- [ ] Yes
- [X] No

**Comment by cmonty14** [comment]
Not reproducable after fixing issue [svclb-traefik-<nnnnn> CrashLoopBackOff](https://github.com/alexellis/k3sup/issues/327)

**Comment by alexellis** [comment]
@Waterdrips any thoughts?

**Comment by alexellis** [comment]
@cmonty14 if arkade / k3sup are both of use to you, please consider becoming a sponsor using the link above. You're also welcome to join the community on [OpenFaaS Slack](https://slack.openfaas.io/)

**Comment by Waterdrips** [comment]
I'd guess /tmp/portainer.yaml was created by root on a previous run? Or /tmp/ permissions are not writable on the system

**Comment by alexellis** [comment]
@cmonty14 were you running arkade with `sudo` or as root?
