### ISSUE TITLE
Update Istio to 1.10

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#403]
Update Istio to 1.10 which is coming out this week

See here for more: https://istio.io/latest/news/releases/

## Expected Behaviour

On Tuesday 18th 1.10 will be released

## Current Behaviour

We're using 1.9

## Possible Solution

Update the Istio app and download version to 1.10

## Steps to Reproduce (for bugs)

```bash
# CLI:
arkade get istio

# App to Kubernetes
arkade install istio
```

**Comment by nitishkumar71** [comment]
I will work on this.

**Comment by alexellis** [comment]
Thanks @nitishkumar71 

I can't see a release yet, so it may be worth checking back tomorrow: https://istio.io/latest/news/releases/

cc @howardjohn
