### ISSUE TITLE
update k9s to v0.24.10

### ISSUE THREAD

**Issue by a5r0n** [alexellis/arkade#408]
## Expected Behaviour

download and use k9s v0.24.10 

## Current Behaviour

v0.24.2 is used
## Possible Solution

Just update the version string in pkg?

**Comment by alexellis** [comment]
Feel free to go ahead.

@nitishkumar71 do you want to take it?

**Comment by nitishkumar71** [comment]
Sure

**Comment by alexellis** [comment]
Interesting to see that the K9s download URL format changed. This means that arkade won't be able to download earlier releases.

cc @derailed

**Comment by alexellis** [comment]
@a5r0n this change is now available in the master branch and will be released within a few days.

Please do consider becoming a [GitHub Sponsor to support our work on arkade](https://github.com/sponsors/alexellis)

This is for individual users and / or companies including custom amounts and one-time options.
