### ISSUE TITLE
`arkade get mc` on arm64 device fails

### ISSUE THREAD

**Issue by vielmetti** [alexellis/arkade#410]
## Expected Behaviour

`arkade get mc` fails on an arm64 device.

## Current Behaviour

```
(base) emv@ny-c1-large-arm-01:~/src/github.com/alexellis/arkade$ arkade get mc
Downloading mc
{$arch = "arm64"}}

                        https://dl.min.io/client/mc/release/linux-aarch64/mc
Error: check with the vendor whether this tool is available for your system: parse "{$arch = \"arm64\"}}\n\t\t\t\n\t\t\thttps://dl.min.io/client/mc/release/linux-aarch64/mc": net/url: invalid control character in URL

```
## Possible Solution

Fix the tools.go file to correct the syntax.

## Steps to Reproduce (for bugs)

1. Get an arm64 device
2. `arkade get mc`

## Context

Working my way through the apps catalog for arm64.

## Your Environment

```
% arkade version
Version: 0.7.15
Git Commit: 426546ce181648f68380e06c572ae529f5cd6eba
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [x] Yes
- [ ] No

**Comment by Shikachuu** [comment]
I can confirm thi issue is already fixed, here is an arm64 mac download:
![image](https://user-images.githubusercontent.com/32636587/177000793-34dbd5cf-f33a-4bb2-a98c-db342153187d.png)

and here is an arm64 linux download:
![image](https://user-images.githubusercontent.com/32636587/177000806-f45d2e6e-7820-4b4f-8413-7803e872e753.png)
