### ISSUE TITLE
kind github url broken

### ISSUE THREAD

**Issue by crobinson89** [alexellis/arkade#413]
## Expected Behaviour
After typing `arkade get kind` it is expected to download and install kind.

## Current Behaviour
404 error

## Possible Solution
Fix URL for the `arkade get kind`

## Steps to Reproduce (for bugs)
1. Setup MicroSD with Ubuntu server
2. Updates,configs,etc
3. Follow Alex Ellis install/setup guide

## Context

Below doesn't matter. Kind did an update to their releases and the link is broken.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```
latest

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [ ] Yes
- [x] No

**Comment by alexellis** [comment]
Cc @developer-guy

**Comment by alexellis** [comment]
I see.. glad I could help. Do fill out the whole form next time, or we may not be able to help you.

Having to ask clarifying questions that are already asked in the template is an unfortunate waste of a precious and limited resource.

If you do find value in Arkade and my other work/blog posts, and if you find personal technical support helpful, consider becoming a sponsor. At any amount.
