### ISSUE TITLE
arkade get buildx on arm64 fails to get published binary

### ISSUE THREAD

**Issue by vielmetti** [alexellis/arkade#419]
## Expected Behaviour

`arkade get buildx` on arm64 tries to fetch the file `buildx-v0.4.2.linux-aarch64`, whereas the project has published the file 
`buildx-v0.4.2.linux-arm64`.

## Current Behaviour

`arkade get buildx` fails to download the correct binary for arm64.

## Possible Solution

Fix the `tools` configuration to point to the correct binary.

## Steps to Reproduce (for bugs)

1. login to an arm64 system
2. install arkade
3. `arkade get buildx` fails
4. inspect https://github.com/docker/buildx/releases/tag/v0.4.2 to see that there is a buildx binary to be had.

## Context

Part of an effort to test `arkade get` for arm64.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Ubuntu 20.04 LTS on WSL1 on Windows on Arm.
```

* What arkade version is this?

```
arkade version

Version: 0.7.13
Git Commit: a7418b1652e1f96c6f86985572c828a96d136836
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [x] Yes
- [ ] No

**Comment by alexellis** [comment]
@vielmetti happy to take a PR for this

I think you're finding that very few arkade users have an arm64 desktop.

Have you just bought one?
