### ISSUE TITLE
Convert Test_DownloadKubectl tests to test table format

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#423]
## Task

Convert Test_DownloadKubectl tests to test table format

## Benefit

More maintainable, and easier to follow now that we have a newer test format such as `Test_DownloadOpa` or `Test_DownloandPolarisCli`

**Comment by dirien** [comment]
Hi got this covered -> https://github.com/alexellis/arkade/pull/430

**Comment by alexellis** [comment]
Thank you @dirien - looks good to me.
