### ISSUE TITLE
Kubectl install fails with 404 because of incorrect url

### ISSUE THREAD

**Issue by LucasRoesler** [alexellis/arkade#436]
The github.com/openfaas/certifier CI is failing because arkade fails to install kubectl

## Expected Behaviour

[This script](https://github.com/openfaas/certifier/blob/master/contrib/get_tools.sh) should work, as it did previously

```sh
KUBE_VERSION=v1.18.8

echo ">>> Installing kubectl $KUBE_VERSION"
arkade get kubectl --version $KUBE_VERSION
sudo mv $HOME/.arkade/bin/kubectl /usr/local/bin/
```

## Current Behaviour

```sh
>>> Installing kubectl v1.18.8
Downloading kubectl
https://storage.googleapis.com/kubernetes-release/release/vv1.18.8/bin/linux/amd64/kubectl
Error: Process completed with exit code 1.
```

The url is incorrect, it contains two `v` in the path: `vv1.18.8`

## Possible Solution

Ideally the installation should be able to handle specifying the version with or without a `v` and still build the correct URL

## Steps to Reproduce (for bugs)

1. Run `arkade get kubectl --version v1.18.8`

## Your Environment

* What Kubernetes distribution are you using?
Not applicable

* What arkade version is this?

```
arkade version
```

```
Version: 0.7.19
Git Commit: a6a37d06ae25663b03f6279c3aaf7b01d3505eca
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [x] Yes
- [ ] No

**Comment by alexellis** [comment]
From my perspective, this is still working as designed.

```
alex@am1 ~ % arkade get kubectl
Downloading kubectl
https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/darwin/amd64/kubectl
44.09 MiB / 44.09 MiB [--------------------------------------------------------------------------------------------------------] 100.00%
Tool written to: /Users/alex/.arkade/bin/kubectl

# Add (kubectl) to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/Users/alex/.arkade/bin/kubectl

# Or install with:
sudo mv /Users/alex/.arkade/bin/kubectl /usr/local/bin/

alex@am1 ~ % arkade get kubectl --version 1.20.0
Downloading kubectl
https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/darwin/amd64/kubectl
44.09 MiB / 44.09 MiB [--------------------------------------------------------------------------------------------------------] 100.00%
Tool written to: /Users/alex/.arkade/bin/kubectl

# Add (kubectl) to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/Users/alex/.arkade/bin/kubectl

# Or install with:
sudo mv /Users/alex/.arkade/bin/kubectl /usr/local/bin/

alex@am1 ~ % 
```

The v cannot be hard-coded for apps because quite often, what you'll see is URLs that have this:

SEGMENT/version_without_v/BINARY_NAME-version-withv

or

SEGMENT/version_with_v/BINARY_NAME-version-without-v

So as a rule, the v prefix isn't passed in to apps. (It's fair to say that this isn't documented in the README)

So to fix this issue, I would write: `KUBE_VERSION=1.18.8`

Or `KUBECTL_VERSION=1.18.1`

Option 2 is to do what @yankeexe is suggesting, however it may lead to issues where people then pass `--version v1.0.0` into all apps, and get surprised by the cases where it fails.

I wish download URLs were consistent.

**Comment by okuuva** [comment]
While the opening post is about hardcoded v-prefix, the issue described in the title has become relevant since Google has moved hosting kubectl in different domain:
`https://dl.k8s.io/release/v${version}/bin/${os}/${arch}/kubectl`

**Comment by alexellis** [comment]
Hi @okuuva perhaps you could raise a separate issue and describe what problem you're running into?

I've had no issues with kubectl or with specifying a version.

```
alex@bq:~$ arkade get kubectl
Downloading: kubectl
Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.24.2/bin/linux/amd64/kubectl
43.59 MiB / 43.59 MiB [------------------------------------------------] 100.00%
/tmp/kubectl written.
2023/02/27 10:00:35 Copying /tmp/kubectl to /home/alex/.arkade/bin/kubectl

Wrote: /home/alex/.arkade/bin/kubectl (45.71MB)

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/alex/.arkade/bin/kubectl

# Or install with:
sudo mv /home/alex/.arkade/bin/kubectl /usr/local/bin/

🐳 arkade needs your support: https://github.com/sponsors/alexellis
alex@bq:~$ arkade get kubectl@v1.26.0
Downloading: kubectl
Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.26.0/bin/linux/amd64/kubectl
45.80 MiB / 45.80 MiB [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/kubectl written.
2023/02/27 10:00:44 Copying /tmp/kubectl to /home/alex/.arkade/bin/kubectl

Wrote: /home/alex/.arkade/bin/kubectl (48.02MB)

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/alex/.arkade/bin/kubectl

# Or install with:
sudo mv /home/alex/.arkade/bin/kubectl /usr/local/bin/

🐳 arkade needs your support: https://github.com/sponsors/alexellis
alex@bq:~$ 
```

Alex
