### ISSUE TITLE
"arkade get kind" fails with "check with the vendor whether this tool is available"

### ISSUE THREAD

**Issue by dinesh707** [alexellis/arkade#439]
I was trying to install kind in my machine using arkade and following is the error i got. 
```
$ arkade get kind
Downloading kind
Error: check with the vendor whether this tool is available for your system: Head "https://github.com/kubernetes-sigs/kind/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

```
## Expected Behaviour
Expected to be installed without any failures.

## Current Behaviour
See the error above.

## Possible Solution
UNKNOWN

## Steps to Reproduce (for bugs)
just run `arkade get kind`

## Your Environment

* What Kubernetes distribution are you using?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
$ uname -a
Linux dinesh-VirtualBox 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
$ arkade version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.7.20
Git Commit: 5c09a1403be8d89dd93a6d341b2f2ade8bae7bcc
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [ ] Yes
- [x ] No

**Comment by dirien** [comment]
Can you see if you can acess the url https://github.com/kubernetes-sigs/kind/releases/latest maybe try a curl...

```bash
➜  ~ curl https://github.com/kubernetes-sigs/kind/releases/latest
<html><body>You are being <a href="https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1">redirected</a>.</body></html>%
➜  ~
```

Maybe you use some kind of proxy? I cant reproduce the error...

**Comment by dinesh707** [comment]
Thanks @dirien . I can reach the url from the browser. If I curl, this is the output i see (which is quite similar to what you seeing)

```
$ curl https://github.com/kubernetes-sigs/kind/releases/latest
<html><body>You are being <a href="https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1">redirected</a>.</body></html>(base) 
```

I'll see if there is any proxy causing the issue.

**Comment by dinesh707** [comment]
My nameserver was not responding fast enough. It was the problem. Thanks for checking

**Comment by dirien** [comment]
Good to hear!
