### ISSUE TITLE
Add Confluent's Kafka and Zookeeper projects as apps

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#446]
## Description

Add Confluent's Kafka and Zookeeper projects as apps using [their respective helm charts](https://github.com/confluentinc/cp-helm-charts)

## Context

Required for testing OpenFaaS' Kafka event-trigger, and for others who wish to test Kafka locally on their cluster.

This is unlikely to work with ARM, so add a block if that turns out to be the case.

Install with defaults for development, i.e. 1 broker, not 3. No persistence, but a flag to enable it if required.

See also: [OpenFaaS quickstart with self-hosted Kafka](https://github.com/openfaas/faas-netes/blob/master/chart/kafka-connector/quickstart.md)

**Comment by dirien** [comment]
Question: should we enable zookeeper per default or not? 

```yaml
cp-zookeeper:
  enabled: true
```
or via --set cp-zookeeper.enabled=true

**Comment by alexellis** [comment]
I imagine Zookeeper is required, it always has been since we started using Wurstmeister, then the Incubator chart in the old Helm repo.

If arkade can handle installing Zookeeper in a single app then we should do that.

I just don't want any bloat installed like Prometheus Operators or monitoring stacks. Kafka + Zookeeper with a minimal configuration.

**Comment by dirien** [comment]
understandable... sooner or later zookeper will be history too for kafka installs... https://www.confluent.de/blog/kafka-without-zookeeper-a-sneak-peek/
