### ISSUE TITLE
[CLI] kgctl

### ISSUE THREAD

**Issue by squat** [alexellis/arkade#450]
## Expected Behaviour
I'd like to be able to install `kgctl`, the CLI for Kilo, via arkade, a la:
```shell
arkade get kgctl
```
The Kilo project provides precompiled binaries for every release: https://github.com/squat/kilo/releases.

## Current Behaviour
Nothing!

## Possible Solution
Add `kgctl` to the installable tools.

## Context
I'm the creator and a maintainer of the [Kilo](https://github.com/squat/kilo) project. Kilo is a multi-cloud network overlay built on WireGuard and designed for Kubernetes. The companion `kgctl` tool helps administrators inspect their meshes and configure peers for their clusters.

## Are you a GitHub Sponsor (Yes/No?)
- [x] No

**Comment by dirien** [comment]
That looks really cool! I tested kilo on Scaleway Kosmos. Worked really well!
