### ISSUE TITLE
[CLI] Porter

### ISSUE THREAD

**Issue by dirien** [alexellis/arkade#457]
![image](https://user-images.githubusercontent.com/38325136/125625371-3b225078-2708-44ce-9dc0-045a106cc916.png)

Add the Porter CLI to arkade.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Context

What is Porter?
Take everything you need to do a deployment, the application itself and the entire process to deploy it: command-line tools, configuration files, secrets, and bash scripts to glue it all together. Package that into a versioned bundle distributed over standard Docker registries or plain tgz files.

Now anyone can install your application without deep knowledge of your deployment process, or following a step-by-step deployment doc, regardless of the tech stack.

**Comment by dirien** [comment]
i will cover this

**Comment by alexellis** [comment]
Approved, thanks for the suggestion.
