### ISSUE TITLE
[CLI] Equinix Metal (packet-cli)

### ISSUE THREAD

**Issue by dirien** [alexellis/arkade#458]
![image](https://user-images.githubusercontent.com/38325136/125634003-29d61fd2-af98-4bdb-a018-4c405738b243.png)

Add the Equinix Metal (https://github.com/packethost/packet-cli)  to arkade

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

**Comment by dirien** [comment]
i got this covered

**Comment by alexellis** [comment]
Approved, thanks for the suggestion.
