### ISSUE TITLE
[Feature] Add App type to arkade

### ISSUE THREAD

**Issue by aidun** [alexellis/arkade#46]
Add an type `App` to arkade, to unify the way commands such as `install` and `update` interact with apps. 

## Expected Behaviour

I would suggest an interface in `pkg/app`:

```
type App interface {
  Install()
  Verify()
  Info()
}
```

In addition to this a Helm3-Implementation in `pkg/app` wich will cover the most apps:
```
type Helm3App struct {
.... all values needed to install a normal chart
}
```

In `pkg/apps/` I would place a `<app-name>.go` file which has a `Make<app-name>App` function. This function should return the static app. 

This way you can test the creation of each command with unit tests, this makes it much simpler to make global changes.

In `cmd/apps` are the final commands and the dynamic parts of the apps should be set.

## Current Behaviour
Every command follows ( or not ) a convention. There is no > one way to do it <.

## Context

I try to make it easier to implement and test new commands.

**Comment by alexellis** [comment]
This would be part of #21 in my opinion, I'm going to close as a duplicate. Can you leave a brief comment on the issue with your suggestion?
