### ISSUE TITLE
Problem with Jenkins installation

### ISSUE THREAD

**Issue by GinjiJizai** [alexellis/arkade#464]
## Expected Behaviour
the init container should work correctly after arkade install jenkins

## Current Behaviour
If i try to install Jenkins with 'arkade install jenkins' the init container fails to start with the error message in the init container log:

exec user process caused “exec format error”

## Are you a GitHub Sponsor (Yes/No?)
no

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution
After some research is saw that the jenkins install with arkade doesnt support ARM. It was also stated in the following issues descreption:

https://github.com/alexellis/arkade/pull/90

it would be nice to add some hint in the readme for this. Best would be a way to install jenkins via arkade also on ARM Architecture

## Steps to Reproduce (for bugs)
1. Install Arkade via git bash on windows maschine
2. create a cluster with k3sup on a linux node
3. try to install jenkins via arkade install jenkins
4. check init container logs

## Context
I want to use jenkins in my cluster

## Your Environment

* What Kubernetes distribution are you using?

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.12+k3s1", GitCommit:"559d0c4729493b62e4cda02f85ea3c3a5c3d7428", GitTreeState:"clean", BuildDate:"2021-06-21T20:31:37Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/arm"}

* Operating System and version (e.g. Linux, Windows, MacOS):

See in "steps to reproduce" and:

Windows 10 (Arkade installed):
MINGW64_NT-10.0-19042 DESKTOP-40KGGHO 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys

Linux Node:

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"

* What arkade version is this?

0.7.22

**Comment by alexellis** [comment]
AFAIK Jenkins is not supported on Raspberry Pi. 

@developer-guy or @nitishkumar71 or @dirien could one of you please ensure that there's an if guard to prevent installation on aarchv7?

Thanks

**Comment by GinjiJizai** [comment]
Ok, thank you for your time. So i need to find another solution.

**Comment by dirien** [comment]
Hi @GinjiJizai , there are two ways to get this fly:

using the set in arkade to change all the imags to `jenkins4eval` type eg ->https://hub.docker.com/r/jenkins4eval/jenkins/tags?page=1&ordering=last_updated

```bash
--set controller.image: "jenkins4eval/jenkins"
--set controller.tag: "2.291-slim"
--set contoller. numExecutors:  4 (or how much executors you want)
```

According to the offical roadmap of jenkins (https://www.jenkins.io/project/roadmap/) ARM support is anounced for near term

**Comment by alexellis** [comment]
@dirien could you add an if statement to block installation? So the reverse of this: https://github.com/alexellis/arkade/commit/50d374dec9579a874c6e1e0cb118b994c35bcd4a

Is there an image for ARM64, but not ARM32?

Alex

**Comment by GinjiJizai** [comment]
Hi @dirien 

it worked with this image, thank you :)

**Comment by dirien** [comment]
@alexellis: done
