### ISSUE TITLE
Add Cosign CLI to arkade

### ISSUE THREAD

**Issue by dirien** [alexellis/arkade#474]
Add Cosign CLI to arkade

## Expected Behaviour

I can download the cosign cli via arkade

## Current Behaviour

Its not in arkade available

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

**Comment by alexellis** [comment]
For anyone landing here and wondering why Cosign doesn't work on Alpine Linux, it seems the binary was compiled with CGO, but in a future release it will be statically linked.
