### ISSUE TITLE
[APP] Cassandra

### ISSUE THREAD

**Issue by DavidIsa** [alexellis/arkade#491]
Support the installation of Cassandra for Kuberenetes

## Expected Behaviour

`arkade install cassandra`  should install "Apache Cassandra" on Kubernetes.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

**Comment by alexellis** [comment]
Thanks for raising this.

> would install Rabbitmq on Kubernetes

This might be a typo: should install "Apache Cassandra" on Kubernetes.
