### ISSUE TITLE
Add Table of Contents

### ISSUE THREAD

**Issue by yankeexe** [alexellis/arkade#493]
Add Table of Contents for an intuitive overview of the project, and quicker navigation to the section user is interested in.

## Expected Behaviour

Table of Contents for at a glance view of project, features and other related resources.

## Current Behaviour

No Table of Contents. 

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Possible Solution

Add Table of Contents

**Comment by alexellis** [comment]
Sure, I've added the ToC, let me know what else you had in mind? Happy for you to propose it here

**Comment by alexellis** [comment]
Unfortunate side-effect of doing this -> there's now two pages of scrolling before you even get to the first bit of content 🤔 

Suggestions?

**Comment by yankeexe** [comment]
> Unfortunate side-effect of doing this -> there's now two pages of scrolling before you even get to the first bit of content 
> 
> Suggestions?

@alexellis here are few changes we can make: 
* I guess we can add just the headings (without sub-headings) for sections like [community and contribution](https://github.com/alexellis/arkade#community--contributing) and [Developer Workflow](https://github.com/alexellis/arkade#developer-workflow)

* This can be Grouped under a FAQ section: 
![image](https://user-images.githubusercontent.com/13623913/128375407-a33cdd1a-3589-4a1e-85da-214805cbc23c.png)

* The sub-headings are a bit off, these should not be indented under "Uninstall an app.
![image](https://user-images.githubusercontent.com/13623913/128375741-e56d7e30-d6a8-4727-8b31-8372f53f11aa.png)
