### ISSUE TITLE
Update mongodb helm repository uri because stable is deprecated

### ISSUE THREAD

**Issue by arnobroekhof** [alexellis/arkade#494]
## Expected Behaviour
It installs and works as before

## Current Behaviour
it works but the chart is deprecated

## Are you a GitHub Sponsor (No)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No --> not at the moment

## Possible Solution
Change the repo inside the file mongodb_app.go

## Context
the last update of the currently used chart in november 2020 and in the current chart supported by bitnami there are many changes since then.

Created pull request for this on

## Your Environment

* Kind
* Okteto
* Azure Kubernetes Service

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

* Operating System and version (e.g. Linux, Windows, MacOS):
```
uname -a
Linux littleone 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

* What arkade version is this?

```
0.7.26
```

**Comment by Shikachuu** [comment]
Fixed in #723
