### ISSUE TITLE
Metrics server uses amd64 image on arm nodes

### ISSUE THREAD

**Issue by kadern0** [alexellis/arkade#50]
## Expected Behaviour
Check node architecture and use appropriate image. Following images available:
- metrics-server
- metrics-server-amd64
- metrics-server-arm
- metrics-server-arm64

## Current Behaviour

```
Normal   Pulled     19s (x2 over 37s)  kubelet, master    Container image "gcr.io/google_containers/metrics-server-amd64:v0.3.6" already present on machine
  Normal   Created    19s (x3 over 38s)  kubelet, master    Created container metrics-server
  Normal   Started    19s (x3 over 38s)  kubelet, master    Started container metrics-server
  Warning  BackOff    2s (x6 over 36s)   kubelet, master    Back-off restarting failed container
```
## Possible Solution
Check node architecture and use right image.
## Steps to Reproduce (for bugs)
1.  ./arkade install metrics-server --namespace kube-system --helm3
```
kubectl get pods -n kube-system 
NAME                                      READY   STATUS             RESTARTS   AGE
metrics-server-85774544d5-nn876           0/1     CrashLoopBackOff   6          8m42s
```

**Comment by alexellis** [comment]
Is there an alternative for this, or do we just need to block it?

It may be the reason that @ibuildthecloud ships metrics-server inside k3s (which is available for different architectures)

**Comment by kadern0** [comment]
In this case, it should be an easy fix. We can choose image depending on the node arch. I can give it a go.
