### ISSUE TITLE
Mongodb and PostgreSQL install fails on arm nodes

### ISSUE THREAD

**Issue by kadern0** [alexellis/arkade#51]
Trying to install mongodb or PostgreSQL on a Raspberry Pi cluster doesn't work.

## Expected Behaviour
Using a working image or throwing an error to prevent creation of all resources in the cluster.
## Current Behaviour
It uses the image x86-64:
`docker.io/bitnami/mongodb:4.2.4-debian-10-r0`
`docker.io/bitnami/postgresql:11.7.0-debian-10-r9`

## Possible Solution
MongoDB and PostgreSQL ARM images do exist, but I assume they will require some configuration and testing. Until then, an error message should be fine.
## Steps to Reproduce (for bugs)
1.
```
arkade install mongodb
 kubectl get pods
NAME                       READY   STATUS   RESTARTS   AGE
mongodb-58bc75c45c-j9vlw   0/1     Error    7          12m
postgresql-postgresql-0    0/1     CrashLoopBackOff   4          3m46s
```

**Comment by alexellis** [comment]
(FYI: no Bitnami images work on ARM) please see my comment on #52 

We will need to do an architecture check on each and then prevent the installation.

**Comment by kadern0** [comment]
PR ready!

**Comment by dharmit** [comment]
This is probably tangential to what's covered in this issue. I'm seeing below on my laptop:
```sh
$ arkade install postgresql
Using kubeconfig: /home/dshah/.kube/config
Node architecture: ""
Error: only Intel, i.e. PC architecture is supported for this app

$ lscpu | grep 'Model name'
Model name:                      Intel(R) Core(TM) <snipped>
```
Kubernetes cluster in question is a [minishift VM](https://www.okd.io/minishift/) running on my laptop. Am I missing something?

**Comment by joebowbeer** [comment]
#942 Bitnami postgresql chart now supports arm64
