### ISSUE TITLE
Add `dive` tool for exploring each layer in a docker image

### ISSUE THREAD

**Issue by yankeexe** [alexellis/arkade#513]
https://github.com/wagoodman/dive

Dive feels like the perfect tool to fit on the DevOps toolkit. It facilitates exploring a docker image, layer contents, and discovering ways to shrink the size of your Docker/OCI image.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

**Comment by alexellis** [comment]
Thanks for the suggestion.

@dirien what do you think?

**Comment by dirien** [comment]
@alexellis, definitely! Thats a really cool tool!

**Comment by yankeexe** [comment]
@alexellis @dirien will be sending a PR for this

**Comment by dirien** [comment]
@yankeexe, what do you think it would be the effort to build "groups" of tools. So if i would say arkade get dev-ops i get a nice bundle of, opinionated, dev-ops tools?

**Comment by yankeexe** [comment]
@dirien yeah I proposed something similar to @alexellis a while back, basically adding a new `label` element on the `Tool` struct and using `enum` kind list of items to choose from to label that tool would do. 

So based on that label like you said the command could be: 
` arkade get devops-tools`, ` arkade get security` and such.

**Comment by dirien** [comment]
@yankeexe, I think that would give arkade such a unique feature. Having an opinionated bundle of the already hand-curated tools.

**Comment by yankeexe** [comment]
Yes it feels like an intuitive next feature for the tool.
