### ISSUE TITLE
PostgreSQL install fails on arm nodes

### ISSUE THREAD

**Issue by kadern0** [alexellis/arkade#52]
Trying to install PostgreSQL on a Raspberry Pi cluster doesn't work.
## Expected Behaviour
Using a working image or throwing an error to prevent creation of esources in the cluster.

## Current Behaviour
It uses the image x86-64:
`docker.io/bitnami/postgresql:11.7.0-debian-10-r9` 

## Possible Solution
PostgreSQL ARM images do exist, but they will require some configuration and testing. Until then, an error message should be fine.

## Steps to Reproduce (for bugs)

1.
```
./arkade install postgresql
kubectl get pods
NAME                       READY   STATUS             RESTARTS   AGE
postgresql-postgresql-0    0/1     CrashLoopBackOff   4          3m46s
```

**Comment by alexellis** [comment]
Hi, no need to raise issues for each app, just use one to track compatibility and then add the restriction flag we talked about.
