### ISSUE TITLE
[CLI]: vCluster CLI support 

### ISSUE THREAD

**Issue by developer-guy** [alexellis/arkade#526]
[vCluster](https://github.com/loft-sh/vcluster)- Create fully functional virtual Kubernetes clusters - Each vcluster runs inside a namespace of the underlying k8s cluster. It's cheaper than creating separate full-blown clusters and it offers better multi-tenancy and isolation than regular namespaces.

Project Site: https://www.vcluster.com
Stars: 897
Contributors: 10
Slack Channel: https://slack.loft.sh/

## Expected Behaviour

```shell
$ arkade get vCluster
```

## Current Behaviour

There is no support for installing **vCluster** CLI.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [x] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

**Comment by alexellis** [comment]
Hi could you provide some more context?

What company creates this project? Does it have any traction? How many GitHub stars? How many contributors?

Thanks

**Comment by developer-guy** [comment]
should we put these details to the issue template, just an idea 🤔

**Comment by developer-guy** [comment]
maybe we can create two separate issue templates one for applications one for CLIs, does it make sense?

**Comment by alexellis** [comment]
I took another look at this today. So vCluster is the tool from loft-sh, right?

That sounds fine. Can you go ahead and add a PR for the CLI? @developer-guy 

Their download page has lots of tabs that would just become "arkade get"

![image](https://user-images.githubusercontent.com/6358735/144296094-2ef31733-24a7-4979-b2ce-3f8f3b6d08b9.png)
