### ISSUE TITLE
Update the inlets-pro template to support Apple / M1

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#535]
Update the inlets-pro template to support Apple / M1

## Expected Behaviour

Update the inlets-pro template to support Apple / M1 so that `arkade get inlets-pro` on an Apple M1 downloads the darwin/arm64 binary

## Current Behaviour

It will probably download the  amd64 one instead or possibly return an error

## Possible Solution

You can test this with a unit test by updating the Go template, you do not need to own a Mac or an Apple M1 to create this PR.

https://github.com/alexellis/arkade/tree/master/pkg/get
https://github.com/alexellis/arkade/blob/master/pkg/get/tools.go

**Comment by Shikachuu** [comment]
The request change was merged yesterday, should we close this? :thinking:
