### ISSUE TITLE
Error when charts folder already exists (regression)

### ISSUE THREAD

**Issue by aidun** [alexellis/arkade#55]
If you install an app twice arakde will fail.

## Expected Behaviour

Arkade should install the app with new parameteres or set the default values.

## Current Behaviour

```
Using kubeconfig: /home/markus/.config/k3d/k3s-default/kubeconfig.yaml
Using helm3
Client: x86_64, Linux
2020/03/11 11:38:35 User dir established as: /home/markus/.arkade/
"jetstack" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "bitnami-redis" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
[Warning] unable to create namespace cert-manager, may already exist: Error from server (AlreadyExists): namespaces "cert-manager" already exists
Error: failed to untar: a file or directory with the name /tmp/charts/cert-manager already exists
Error: exit code 1

```

## Possible Solution

Cleanup the `/tmp/charts` directory after installation.

## Steps to Reproduce (for bugs)

1. arkade install cert-manager
2. arkade install cert-manager
3.
4.

## Your Environment

* What arkade version is this?

```
master branch
```

**Comment by LucasRoesler** [comment]
I am also seeing the same behavior

```sh
Update Complete. ⎈ Happy Helming!⎈
Error: failed to untar: a file or directory with the name /var/folders/st/lt0d5y4j0sn7qm0z2mrb63zm0000gn/T/charts/openfaas already exists
Error: exit code 1
```

**Comment by alexellis** [comment]
Can you rm -rf the tmp/charts folder?

**Comment by alexellis** [comment]
/set title: Error when charts folder already exists (regression)

**Comment by alexellis** [comment]
@Waterdrips this seems like regression. Would you be able to take a look into it?

**Comment by LucasRoesler** [comment]
Removing the tmp folder does work, but of course needs to be done every time.

I took a quick look at the code and I didn't see any obvious global way to handle this, it would have to be added to each app.  There are 16 cases of `chartPath := path.Join(os.TempDir(), "charts")`

![image](https://user-images.githubusercontent.com/891889/76683670-34ce6580-6606-11ea-88fa-9547c79b038b.png)

**Comment by alexellis** [comment]
This is regression and it used to work fine. I wonder if it was caused by #37 #36 ?

**Comment by Waterdrips** [comment]
/assign: me
I saw this last week when I ctrl-c an app half way through install. 

Didint think much of it at the time
I'll take a look today or early tomorrow
