### ISSUE TITLE
Unable to install krew due to incorrect URL

### ISSUE THREAD

**Issue by sjdrc** [alexellis/arkade#550]
## Expected Behaviour
`arkade get krew` should install krew without error

## Current Behaviour
```
$ arkade get krew
Downloading: krew
2021/10/21 17:47:53 Looking up version for krew
2021/10/21 17:47:53 Found: v0.4.2
Downloading: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.2/krew.tar.gz
Error: incorrect status for downloading tool: 404
```
Error when getting krew

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution

https://github.com/kubernetes-sigs/krew/releases/download/v0.4.2/krew.tar.gz is the URL that tried to get fetched.
https://github.com/kubernetes-sigs/krew/releases/download/v0.4.2/krew-$osStr.tar.gz is the file that should be downloaded

## Steps to Reproduce (for bugs)

1. `arkade get krew`

## Context
Unable to oneliner install krew

## Your Environment

* What Kubernetes distribution are you using?
v1.20.11
```
kubectl version
```
v1.20.11
* Operating System and version (e.g. Linux, Windows, MacOS):

```
$ uname -a
Linux hyperion 5.14.11-arch1-1 #1 SMP PREEMPT Sun, 10 Oct 2021 00:48:26 +0000 x86_64 GNU/Linux

$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

```

* What arkade version is this?

```
$ arkade version
Version: 0.8.5
```

**Comment by alexellis** [comment]
Thanks for raising this @YuviGold and for contributing. Perhaps the krew URL changed upstream? This does happen from time to time.

**Comment by dirien** [comment]
@alexellis, yes indeed!
