### ISSUE TITLE
Add the build status from GitHub Actions to the set of README badge

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#553]
## Expected Behaviour

Add the build status from GitHub Actions to the set of README badgets

## Current Behaviour

I removed it because it was pointing at Travis, which we no longer use so was giving out false information.

## Possible Solution

See the GitHub Actions tab / docs for how to get a badge. Insert it just after the sponsor badge please.

**Comment by Shikachuu** [comment]
/close
#562 fixed this
