### ISSUE TITLE
terraform aarch64 not available

### ISSUE THREAD

**Issue by Xos73** [alexellis/arkade#564]
- Raspberry pi 4 with Ubuntu 20.04.3 64 bit
- uname -a: Linux rpi4a 5.4.0-1045-raspi # 49-Ubuntu SMP PREEMPT Wed Sep 29 17:49:16 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
- Installed arkade on 23/20/2021
Command issued: `arkade get terraform`

## Expected Behaviour
Downloading terraform and unzipping it

## Current Behaviour
Package is not downloading. Getting 403 error code

Content of https://releases.hashicorp.com/terraform/1.0.0/ :
../
terraform_1.0.0_SHA256SUMS
terraform_1.0.0_SHA256SUMS.72D7468F.sig
terraform_1.0.0_SHA256SUMS.sig
terraform_1.0.0_darwin_amd64.zip
terraform_1.0.0_freebsd_386.zip
terraform_1.0.0_freebsd_amd64.zip
terraform_1.0.0_freebsd_arm.zip
terraform_1.0.0_linux_386.zip
terraform_1.0.0_linux_amd64.zip
terraform_1.0.0_linux_arm.zip
terraform_1.0.0_linux_arm64.zip
terraform_1.0.0_openbsd_386.zip
terraform_1.0.0_openbsd_amd64.zip
terraform_1.0.0_solaris_amd64.zip
terraform_1.0.0_windows_386.zip
terraform_1.0.0_windows_amd64.zip

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Possible Solution
According to what I understood and read, aarch64 and arm64 are referring the same architecture, so would assume to get/ download arm64 version instead.
Indirectly linked to issue #557 

## Steps to Reproduce (for bugs)
arkade get terraform
Downloading: terraform
Downloading: https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_aarch64.zip
Error: incorrect status for downloading tool: 403

## Context
Trying to create a 4 node k8s cluster on raspberry pi 4 devices.
Following/ inspired by https://blog.alexellis.io/self-hosting-kubernetes-on-your-raspberry-pi/

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
(k8s not yet running)
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Linux rpi4a 5.4.0-1045-raspi #49-Ubuntu SMP PREEMPT Wed Sep 29 17:49:16 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* What arkade version is this?

```
arkade version

root@rpi4a:~/.arkade# ark version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.8.8
Git Commit: 10f4f5e0b2f5012b85a7a2b4b45a0aecdb4d8ea6
```

**Comment by Shikachuu** [comment]
> aarch64 should be "translated" to arm64. Which is missing for `terraform` right now
> 
> https://github.com/alexellis/arkade/blob/f032138e8bedfee04b06c3f29ba58ac9fd5583b3/pkg/get/tools.go#L607-L618

Packer is also missing this "translate".

**Comment by Shikachuu** [comment]
@Xos73 with 0.8.9 this issue should be fixed, can you confirm that and close the issue?

**Comment by alexellis** [comment]
Closing. Thanks @Shikachuu
