### ISSUE TITLE
 added kanister app #569 

### ISSUE THREAD

**Issue by MichaelCade** [alexellis/arkade#570]
Added arkade install kanister 

## Expected Behaviour

works as expected 
arkade install kanister 
arkade info kanister 

## Are you a GitHub Sponsor (No)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

**Comment by alexellis** [comment]
Added in #585
