### ISSUE TITLE
Feature request: Add Kuma helm chart + kumactl cli app

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#571]
Add `kumactl` to `arkade get` and add Kuma itself to `arkade install`.

## Expected Behaviour
`arkade install kuma` should install the Kuma helm chart and `arkade get kumactl` should install kumactl.

## Current Behaviour
Neither the helm chart nor kumactl implemented.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution
Add kumactl to cli and the helm chart to arkade.

## Steps to Reproduce (for bugs)
This isn't a bug.

## Your Environment

* What Kubernetes distribution are you using?

Kubectl and OS version shouldn't matter since this is not implemented yet.

* What arkade version is this?

```
Version: 0.8.8
Git Commit: 10f4f5e0b2f5012b85a7a2b4b45a0aecdb4d8ea6
```

**Comment by alexellis** [comment]
Approved 👍

**Comment by Shikachuu** [comment]
/edit title: Feature request: Add Kuma helm chart + kumactl cli app
