### ISSUE TITLE
kube-bench install fails

### ISSUE THREAD

**Issue by xshyamx** [alexellis/arkade#576]
Installing kube-bench with ark fails with HTTP 404 error

## Expected Behaviour

Binary should be installed succesfully in `$HOME/.arkade/bin`

## Current Behaviour

Gets HTTP 404 because of incorrect URL

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Possible Solution

`BinaryTemplate` in tools.go needs to be updated to reflect the correct url 

Incorrect URL: https://github.com/aquasecurity/kube-bench/releases/download/0.4.0/kube-bench_0.4.0_linux_amd64.tar.gz
Correct URL: https://github.com/aquasecurity/kube-bench/releases/download/v0.4.0/kube-bench_0.4.0_linux_amd64.tar.gz

## Steps to Reproduce (for bugs)

1. Run ark get kube-bench

```sh
$ ark get kube-bench
Downloading: kube-bench
Downloading: https://github.com/aquasecurity/kube-bench/releases/download/0.4.0/kube-bench_0.4.0_linux_amd64.tar.gz
Error: incorrect status for downloading tool: 404
$ 
```

## Context

Able to use workaround as follows for now but, it would be better if fixed in the code

```
$ ark get kube-bench -v v0.6.5
```

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux x86_64 x86_64 GNU/Linux

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* What arkade version is this?

```
$ ark v
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.8.8
Git Commit: 10f4f5e0b2f5012b85a7a2b4b45a0aecdb4d8ea6
```

**Comment by alexellis** [comment]
Thanks for the issue. Is this regression due to changes upstream?

Are you wanting to send a PR and updated unit tests?

**Comment by alexellis** [comment]
If you're a regular user of arkade, please consider becoming a sponsor. It doesn't cost a lot and every little helps with all this work :)

**Comment by alexellis** [comment]
Fixed in: https://github.com/alexellis/arkade/releases/tag/0.8.9

Run `arkade update`

Also you can get tools using an `@` syntax now:

```
./arkade get kube-bench -v v0.6.5
Downloading: kube-bench
Downloading: https://github.com/aquasecurity/kube-bench/releases/download/v0.6.5/kube-bench_0.6.5_linux_amd64.tar.gz
9.88 MiB / 9.88 MiB [----------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/kube-bench_0.6.5_linux_amd64.tar.gz written.
```

**Comment by xshyamx** [comment]
I did not expect such a fast response. By the time I revisited the issue it is already closed and released in the new version. Kudos :)
