### ISSUE TITLE
Feature request: Add hostctl to `arkade get`

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#579]
https://github.com/guumaster/hostctl
hostctl is a nice and handy tool to manage different host profiles and host files in general on every os.

## Expected Behaviour
`arkade get hostctl` installs the binary

## Current Behaviour
Not implemented

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution
Add `hostctl` to `pkg/get/tools.go`

## Context

Recently started using that, and it is really awsome!

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+k3s2", GitCommit:"3f5774b41eb475eb10c93bb0ce58459a6f777c5f", GitTreeState:"clean", BuildDate:"2021-10-05T20:29:33Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux pop-os 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
Version: 0.8.3-40-g4bf1460
Git Commit: 4bf14606fcb64e19b050b277ba36226df6c632d6
```

**Comment by alexellis** [comment]
@Shikachuu if you use this tool, then feel free to submit a PR.

Alex

**Comment by Shikachuu** [comment]
/edit title: Feature request: Add hostctl to `arkade get`
