### ISSUE TITLE
Kubectx not using dynamic versioning

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#583]
Tools downloaded from GitHub should be able to download the latest release, yet kubectx is capped to `v0.9.1`.

## Expected Behaviour
`arkade get kubectx` downloads the latest version of kubectx.

## Current Behaviour
It downloads `v0.9.1`.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution
1. Update to the version by hand every time. (please don't do this!)
2. Remove the `Version` field from `pkg/get/tools.go` on line `160`

## Steps to Reproduce (for bugs)
1. Run `arkade get kubectx`
2. Check the logs which version has been downloaded.

## Context
If we have the possibility to install the latest version, I assume we should do that.

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+k3s2", GitCommit:"3f5774b41eb475eb10c93bb0ce58459a6f777c5f", GitTreeState:"clean", BuildDate:"2021-10-05T20:29:33Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux pop-os 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
Version: 0.8.3-40-g4bf1460
Git Commit: 4bf14606fcb64e19b050b277ba36226df6c632d6
```

**Comment by alexellis** [comment]
I can't remember why this was, but if you can make it work, feel free to go ahead with this.

**Comment by Shikachuu** [comment]
> I can't remember why this was, but if you can make it work, feel free to go ahead with this.

Just tried it with latest release and it is working fine.

I'll definetly do a PR!

**Comment by alexellis** [comment]
Thanks @Shikachuu I'll look out for it.

**Comment by Yannig** [comment]
This PR (https://github.com/alexellis/arkade/pull/602) can be used to download latest version of kubectx or kubens.
Use latest as version value to retrieve the last one:

    arkade get kubens@latest
