### ISSUE TITLE
Update Portainer app to use its helm chart

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#587]
Update [Portainer](https://www.portainer.io) app to use its helm chart

## Expected Behaviour

We should use the Portainer chart.

https://portainer.github.io/k8s/charts/portainer/

## Possible Solution

Copy the approach used for the openfaas app or one of the others.

Where to edit:

https://github.com/alexellis/arkade/blob/master/cmd/apps/portainer_app.go

Examples to follow:

https://github.com/alexellis/arkade/blob/master/cmd/apps/openfaas_app.go
https://github.com/alexellis/arkade/blob/master/cmd/apps/inletsoperator_app.go

## Context

This means users can take advantage of all Portainer features made available by the project.

**Comment by alexellis** [comment]
/add label: help wanted, good first issue

**Comment by alexellis** [comment]
Hi @srebala please take a look at what needs to be done and then confirm whether you think you can manage it in your first contribution?

**Comment by Shikachuu** [comment]
I can take this issue, I am intrested in Portainer anyways.
I think the ETA is somewhere between today (2021.11.24) and tomorrow (2021.11.25).
