### ISSUE TITLE
binary relocation leaves wrong user and permissions and suggested PATH changes are not idempotent.

### ISSUE THREAD

**Issue by sjmudd** [alexellis/arkade#594]
Download instructions work fine, but the suggestion to move under `/usr/local/bin` will leave files with the wrong ownership (not `root` and not `go = group/other` executable) and leaving in user's `PATH` blindly adding `$HOME/.arkade/bin` is not ideal (could leave repeated entries).

## Expected Behaviour

- provide a simpler _one-click_ way to `chmod go=rx <binaries>` of the binaries and `chown root:root <binaries>` as part of the relocation.
- if relocated provide a way to move them back so removing anything can not leave things hanging around
- if leaving the binaries in their pre-installed location either suggest adding or add something like

```
if ! echo $PATH | grep -q $HOME/.arkade/bin; then 
    export PATH=$PATH:$HOME/.arkade/bin # no trailing slash!
fi
```
## Current Behaviour
- current moving of binaries leaves the binaries executable by only the user. In `/usr/local/bin` that's not expected
- suggestion to add to `~/.bashrc` or `~/.bash_profile`  (or other shells) if repeated would repeat the path multiple times which should not happen.
- you can also check the current `PATH` setting and suggest it be updated.

## Are you a GitHub Sponsor (Yes/No?)

- [x] No

## Possible Solution

See above.

## Steps to Reproduce (for bugs)

```
myuser@myhost:~$ arkade get kubectl
Downloading: kubectl
Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.22.2/bin/linux/amd64/kubectl
44.73 MiB / 44.73 MiB [-----------------------------------------------------------------------------------------------------] 100.00%
/tmp/kubectl written.
2021/12/04 19:34:40 Copying /tmp/kubectl to /home/myuser/.arkade/bin/kubectl

Tool written to: /home/myuser/.arkade/bin/kubectl

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/myuser/.arkade/bin/kubectl

# Or install with:
sudo mv /home/myuser/.arkade/bin/kubectl /usr/local/bin/
myuser@myhost:~$ ls -l .arkade/bin/kubectl
-rwx------ 1 myuser myuser 46907392 Dec  4 19:34 .arkade/bin/kubectl
myuser@myhost:~$
```

## Context

First time install, trying this out which sounds like a nice feature and simplifies k3s / k8s type usage.

## Your Environment

Linux, still playing with k8s (at home) having tried microk8s, minikube and now looking at k3s and trying to find a solution which works easily with home storage.

* What Kubernetes distribution are you using?

currently was trying k3s instructions from your blog on using k3sup etc for kubernetes home usage.
```
kubectl version v1.22.4
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
CentoS 8 / Ubuntu 20.04 LTS
on x86_64 but also testing on a pi4
```

* What arkade version is this?
from today, 4/Dec/2021

```
arkade version
```
Version: 0.8.11
Git Commit: f6c134889f89c4bfe1b06f0f97037f16caf2b6a3

**Comment by alexellis** [comment]
@sjmudd is this an actual problem you experienced?

Do you have multiple users logging into your laptop?

I'm trying to understand if this is a purest/prescriptive critique or solving an actual problem that users are facing. 

Alex

**Comment by sjmudd** [comment]
I don't have multiple users connected to my pc but I do expect binaries installed in `/usr/local/bin` to be configured properly. There's a standard for this and having binaries with unexpected problems is not ideal and may cause issues. Expecting a single user to login to the computer is I think misguided. If you want to install binaries into only the user's environment than that's different but that's not what you're doing.
So local permissions are fine, but pushing that ownership and permissions into `/usr/local/bin` is really not ideal.

**Comment by alexellis** [comment]
Hi @sjmudd thanks for your suggestion.

I'm going to leave this issue here (but closed). If it affects someone, they are welcome to comment here and we can triage your suggestions.

You are under no requirement to move tools downloaded by arkade to /usr/local/bin, you can simply use them from $HOME/.arkade/bin as is the default.
 
Alex
