### ISSUE TITLE
kustomize failing on Linux AMD64

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#595]
## Expected Behaviour

kustomize should continue to work

## Current Behaviour

It's failing to download for me on Linux / AMD64:

```bash
arkade get kustomize
Downloading: kustomize
2021/12/14 17:23:10 Looking up version for kustomize
2021/12/14 17:23:11 Found: v0.13.0
Downloading: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv0.13.0/kustomize_v0.13.0_linux_amd64.tar.gz
Error: incorrect status for downloading tool: 404
```

Let's get it fixed?

**Comment by developer-guy** [comment]
I can take care of this one

**Comment by alexellis** [comment]
Thank you

**Comment by dirien** [comment]
Hi @developer-guy and @alexellis, I quickly fixed this. Hope its okay?

**Comment by alexellis** [comment]
Thanks @dirien - you caught me in the Christmas period so I'll take a look.
