### ISSUE TITLE
ark get kubeseal has outdated version

### ISSUE THREAD

**Issue by mirageglobe** [alexellis/arkade#603]
kubeseal library source is outdated. running ark get kubeseal downloads and older version 0.14.

![image](https://user-images.githubusercontent.com/577792/149512390-4d6ccf53-3572-465a-b942-62b958edab0c.png)

using versioned fails

![image](https://user-images.githubusercontent.com/577792/149512243-6bd656cb-302e-4dab-a2d3-7818d2dce6b9.png)

## Expected Behaviour

to install kubeseal latest

## Current Behaviour

installs an older version

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Possible Solution

the file format seems to be wrong.

- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.14.1/kubeseal-darwin-amd64

and should be

- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.2/kubeseal-0.17.2-darwin-amd64.tar.gz

there is a version number embedded in the filename

## Steps to Reproduce (for bugs)
1. ark get kubeseal@v0.17.2

## Context

N/A

## Your Environment

N/A

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

N/A

* What arkade version is this?

```
arkade version
Version: 0.8.0
```

**Comment by alexellis** [comment]
Hi @mirageglobe thanks for letting us know

This happens when projects change downstream.

Let's see if there's someone who wants to work on a fix?

@dirien @welteki @Yannig @cpanato 

Seems like a gzipped tar is now used instead of a regular binary. We have examples like this that can be used for a starting point.

![image](https://user-images.githubusercontent.com/6358735/150187159-3aa88331-a1d0-4fe9-aa6b-58afc3cf6a9c.png)

**Comment by yankeexe** [comment]
@alexellis  I will take this issue.

**Comment by Yannig** [comment]
I'm working on a feature to detect the last release and try to guess the one compatible with the current os and arch.

In this way we can autodetect the archives which correspond to certain common criteria (the presence of linux, mac or windows strings or the presence of amd64, arm64, etc).

As soon as I've made some progress on the subject, I'll create a branch with my work.

**Comment by Yannig** [comment]
Here a first version of this feature: https://github.com/alexellis/arkade/pull/614
