### ISSUE TITLE
Release 0.8.12 is missing arkade-darwin-arm64 binary

### ISSUE THREAD

**Issue by brysk** [alexellis/arkade#606]
I've follewed Readme instruction to download arkade but it looks like [arkade-darwin-arm64 ](https://github.com/alexellis/arkade/releases/download/0.8.12/arkade-darwin-arm64) binary is missing:

`curl -sLS https://get.arkade.dev | sudo sh`

## Expected Behaviour
Binary is downloaded and installed

## Current Behaviour
https://github.com/alexellis/arkade/releases/download/0.8.12/arkade-darwin-arm64 returns 404

```
curl -sLS https://get.arkade.dev |  sh
Downloading package https://github.com/alexellis/arkade/releases/download/0.8.12/arkade-darwin-arm64 as /tmp/arkade-darwin-arm64
Download complete.

Running with sufficient permissions to attempt to move arkade to /usr/local/bin
New version of arkade installed to /usr/local/bin
Creating alias 'ark' for 'arkade'.
/usr/local/bin/arkade: line 1: Not: command not found
```

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Possible Solution
Fix build process?

## Steps to Reproduce (for bugs)

Try to install arkade on macbook M1 

## Your Environment

* What Kubernetes distribution are you using?

* Operating System and version (e.g. Linux, Windows, MacOS):

```
MacOS
```

**Comment by alexellis** [comment]
cc @TomTucka

**Comment by alexellis** [comment]
Here's the new binary: https://github.com/alexellis/arkade/releases/download/0.8.13/arkade-darwin-arm64

For some CLIs you mat need to run `arkade get --arch x86_64` since there are limited choices for Darwin ARM64 at present.
