### ISSUE TITLE
 There is no latest version support for most tools

### ISSUE THREAD

**Issue by Yannig** [alexellis/arkade#610]
## Expected Behaviour

Be able to download the latest version of any tools using version=latest or something similar.

## Current Behaviour
When we try to download k9s, we get the latest version. On the other hand, when trying to get helm or kubectl, you get a fixed value and - unless you know the version number - there is no way to automate this process.

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution

The code already exists in the GitHub Release find method. It would suffice to reuse it when the value is at latest (or something approaching it) in order to detect the latest version available.

## Steps to Reproduce (for bugs)

1. Download Kubectl
2. kubectl version is not the latest one

## Context

I want to be able to download latest version even if a static version is set inside arkade.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

Linux dell-xps 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

* What arkade version is this?

```
Version: 0.8.11
Git Commit: f6c134889f89c4bfe1b06f0f97037f16caf2b6a3
```

**Comment by alexellis** [comment]
> When we try to download k9s, we get the latest version. On the other hand, when trying to get helm or kubectl, you get a fixed value and - unless you know the version number - there is no way to automate this process.

We specifically always download the latest version of tools if no version is set in the template. What makes you think otherwise?

Give me some examples?

**Comment by alexellis** [comment]
If you agree that this is the same issue as #560 I'll close this as a duplicate and we can continue to chat on the issue I wrote up last year. If not, let me know what is specifically different.

Alex

**Comment by Yannig** [comment]
Sure.
