### ISSUE TITLE
The loki stack chart has been deprecated and breaks with K8s 1.23+

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#620]
The loki stack chart has been deprecated and breaks with K8s 1.23+

## Current Behaviour

The [Loki-Stack Helm Chart](https://github.com/grafana/loki/tree/main/production/helm/loki-stack) used in `arkade install loki --grafana` has been deprecated

It fails to install on K8s 1.23 due to using `rbac.authorization.k8s.io/v1beta1` which has been removed from that version of K8s.

## Possible Solution

I assume that the fix is to use the new upstream chart.

A fix is required here: https://github.com/alexellis/arkade/blob/master/cmd/apps/loki_app.go

## Steps to Reproduce (for bugs)

1. Create a Kind or EKS 1.23 cluster
2. `arkade install loki --grafana`
3. See the error

## Context

This affects [Time travelling through your OpenFaaS Function logs](https://www.openfaas.com/blog/openfaas-loki-into/) cc @LucasRoesler 

Reported by @willfore

**Comment by Shikachuu** [comment]
The helm repository url should here: https://github.com/alexellis/arkade/blob/master/cmd/apps/loki_app.go#L57 should be https://grafana.github.io/helm-charts

Also I don't know about any value changes, but definetly worth to run over it and check if the value names are still the same.

**Comment by alexellis** [comment]
Also happy for @LucasRoesler to work on it. The sooner we get it fixed the better as it will start to affect more people as they move to K8s 1.23
