### ISSUE TITLE
Feature request: Add Consul to `arkade install`

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#626]
Originally reported by: @nicholasjackson

## Expected Behaviour
`arkade install consul` installs [HashiCorp Consul](https://www.consul.io/).

## Current Behaviour
Not implemented.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution
Add Consul as an installable app.

## Context

Consul is a service mesh, created by HashiCorp.

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux pop-os 5.15.15-76051515-generic #202201160435~1642693824~21.10~97db1bb SMP Thu Jan 20 17:35:05 U x86_64 x86_64 x86_64 GNU/Linux

```

* What arkade version is this?

```
Version: 0.8.14
Git Commit: a5ab3168867c1bdc258d2ba800385b9d85256fd3
```

**Comment by YuviGold** [comment]
Also would be nice to have the [consul CLI](https://www.consul.io/commands)

**Comment by alexellis** [comment]
Feel free to raise an issue for the consul CLI @YuviGold

@jsiebens / @Jasstkn are either of you interested in adding Consul as an app? Do you know what values would be a useful default for K8s?

**Comment by jsiebens** [comment]
Consul is already available as an app:

```
> arkade install consul-connect --help
Install Consul Service Mesh to any Kubernetes cluster

Usage:
  arkade install consul-connect [flags]

Examples:
  arkade install consul-connect

Flags:
  -d, --datacenter string              The name of the datacenter that the agents should register as (default "dc1")
      --enable-connect-injector        If true, all the resources necessary for the Connect injector process to run will be installed (default true)
      --enable-gossip-encryption       If true, Consul's gossip encryption is enabled (default true)
      --enable-tls-encryption          If true, TLS encryption across the cluster to verify authenticity of the Consul servers and clients is enabled (default true)
      --gossip-encryption-key string   The gossip encryption key; when empty, a new, random key is generated
  -h, --help                           help for consul-connect
      --manage-system-acls             If true, the ACL tokens and policies for all Consul and consul-k8s components will automatically be managed (default true)
  -n, --namespace string               The namespace used for installation (default "consul-system")
      --set stringArray                Use custom flags or override existing flags 
                                       (example --set image=org/repo:tag)
      --update-repo                    Update the helm repo (default true)

Global Flags:
      --kubeconfig string   Local path for your kubeconfig file
      --wait                If we should wait for the resource to be ready before returning (helm3 only, default false)
```

**Comment by jsiebens** [comment]
> it's different consul. this one enables service mesh. I guess task is about installing vanilla consul (e.g. https://www.consul.io/docs/k8s)

Not much of a difference I guess. It's the same consul helm chart, which enables the service mesh by default. 
Perhaps that's the reason we chose `arkade install consul-connect` instead of `arkade install consul`

**Comment by Jasstkn** [comment]
> > it's different consul. this one enables service mesh. I guess task is about installing vanilla consul (e.g. https://www.consul.io/docs/k8s)
> 
> Not much of a difference I guess. It's the same consul helm chart, which enables the service mesh by default. Perhaps that's the reason we chose `arkade install consul-connect` instead of `arkade install consul`

yes, you are right: https://github.com/alexellis/arkade/blob/master/cmd/apps/consul_app.go#L107

**Comment by alexellis** [comment]
Sounds like we may not need this then? Should we wait until a user asks for it specifically rather than the company that sells it?
