### ISSUE TITLE
Feature request: Add Vault to `arkade install`

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#627]
Originally reported by: @nicholasjackson

## Expected Behaviour
`arkade install vault` installs HashiCrop Vault.

## Current Behaviour
Not implemented.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution
Add Vault as an installable app.

## Context

Vault is a secret management service, created by HashiCorp.

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux pop-os 5.15.15-76051515-generic #202201160435~1642693824~21.10~97db1bb SMP Thu Jan 20 17:35:05 U x86_64 x86_64 x86_64 GNU/Linux

```

* What arkade version is this?

```
Version: 0.8.14
Git Commit: a5ab3168867c1bdc258d2ba800385b9d85256fd3
```

**Comment by Jasstkn** [comment]
Hey @Shikachuu! I would like to try to implement this if it's still up-to-date issue.

**Comment by Shikachuu** [comment]
Hey @Jasstkn,
As far as I know it is still up-to-date! 

We should implement this as a cli tool and a helm chart too in two separate PRs.

For the helm chart, check out some already implemented projects, like:
Kubernetes Dashboard
https://github.com/alexellis/arkade/blob/master/cmd/apps/kubernetes_dashboard_app.go
Or Grafana
https://github.com/alexellis/arkade/blob/master/cmd/apps/grafana_app.go

**Comment by Jasstkn** [comment]
One of the PRs to fix this issue is being submitted:
- https://github.com/alexellis/arkade/pull/738

**Comment by Jasstkn** [comment]
And another one about adding Vault to apps is also ready to be reviewed:
https://github.com/alexellis/arkade/pull/739
