### ISSUE TITLE
Allow a license file for inlets operator

### ISSUE THREAD

**Issue by Waterdrips** [alexellis/arkade#64]
## Expected Behaviour

Provide a license key file location ad a command line flag, the contents of this file should be used as the license.

## Current Behaviour

You have to provide a license as a string, which gets printed to the console by `arkade`
## Possible Solution

add a new flag for `--license-file` which reads the file.

**Comment by Waterdrips** [comment]
@codeanit was taking a look at this

**Comment by codeanit** [comment]
@Waterdrips Thanks.

As discussed, I will review the codebase, and get back to you on how we will be collaborating on this as I am a newbie here :)

Cheers,

**Comment by codeanit** [comment]
@Waterdrips Hope things are well at your end. 
I got delayed with some personal matters. We(Kathmandu, Nepal) are having a lock down from tomorrow. 
Could you please attach a sample license file? The nature to file(type, content) could be helpful.
Thanks.

**Comment by Waterdrips** [comment]
/close 

This was fixed by #83
