### ISSUE TITLE
Feature request: Add Mozilla SOPS to arkade get

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#648]
SOPS is a secret management toolkit, mostly used to encrypt secrets in yaml or json files.

## Expected Behaviour
`arkade get sops` downloads the latest binary.

## Current Behaviour
Not implemented.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution
Add sops to `pkg/get/tools.go`

## Context
With sops we can use age, gpg or any cloud provider's kms, to encrypt/decrypt secrets.
It doesn't encrypt the keys, only values in the yaml/json/env etc. files.
Also recommended by Flux and the GitOps toolkit.

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+k3s2", GitCommit:"3f5774b41eb475eb10c93bb0ce58459a6f777c5f", GitTreeState:"clean", BuildDate:"2021-10-05T20:29:33Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux pop-os 5.16.11-76051611-generic #202202230823~1646248261~21.10~2b22243 SMP PREEMPT Wed Mar 2 20: x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
Version: 0.8.15
Git Commit: 8c5d0daf3c6817ba2395371f7084dc0737e5f206
```

**Comment by alexellis** [comment]
Happy to have this 👍
