### ISSUE TITLE
ark get terraform uses wrong URL for M1 

### ISSUE THREAD

**Issue by hwchiu** [alexellis/arkade#665]
## Expected Behaviour

```
-> % ./arkade get terraform
Downloading: terraform
Downloading: https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_darwin_arm64.zip
18.47 MiB / 18.47 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/var/folders/yn/j63ycsqj2294wfsp3z56_s_w0000gn/T/terraform_1.1.7_darwin_arm64.zip written.
Name: terraform_1.1.7_darwin_arm64.zip, size: 193710952022/04/06 01:45:22 Extracted: /var/folders/yn/j63ycsqj2294wfsp3z56_s_w0000gn/T/terraform
...

-> % $HOME/.arkade/bin/terraform version
Terraform v1.1.7
on darwin_arm64
```

## Current Behaviour

Two issues in the Terraform checking function.
1. No check the Mac M1
2. Default version 1.0.0 doesn't have the pre-build binary for Mac M1.

```
-> % ark get terraform
Downloading: terraform
Downloading: https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_darwin_.zip
Error: incorrect status for downloading tool: 403
```

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [X] No

## Possible Solution

1. Check the M1 arch properly
2. Upgrade the default version to the latest version, 1.1.7

## Steps to Reproduce (for bugs)

1. ark get terraform
3.
4.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Darwin Mini 21.4.0 Darwin
 Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
cat /etc/os-release
cat: /etc/os-release: No such file or directory
```

* What arkade version is this?

```
arkade version
Version: 0.8.18
Git Commit: f8a4add41fb0c2141147c52b6485ffbfa93f3aa3
```

**Comment by alexellis** [comment]
Thanks for this @hwchiu 

As we're finding out with @Shikachuu too, Darwin is `arm64`, Linux uses `aarch64`

**Comment by hwchiu** [comment]
@alexellis 
Yes, I'm also thinking define a new variable for the `arm64` in the testing file, so we don't have to hardcode lots of  "amr64" in the whole file.

**Comment by alexellis** [comment]
Please go for it
