### ISSUE TITLE
Error installing metrics-server

### ISSUE THREAD

**Issue by nimamahmoudi** [alexellis/arkade#68]
## Expected Behaviour
running `arkade install metrics-server` to install metrics server.

## Current Behaviour
```
arkade install metrics-server
Using kubeconfig: /home/nima/.kube/config
Node architecture: "amd64"
Using helm3
Client: "x86_64", "Linux"
2020/03/21 11:13:30 User dir established as: /home/nima/.arkade/
Error: no repositories found. You must add one before updating
Error: exit code 1
```
## Possible Solution
I believe this is an issue with the help version, not sure though.

## Steps to Reproduce (for bugs)
1. `k3sup install` to install a k3sup server.
2. `arkade install metrics-server`

## Context
Trying to install `metrics-server`.

* What Kubernetes distribution are you using?

```
kubectl version
# output:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Linux savi-ds 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

* What arkade version is this?

```
arkade version
Version: 0.2.0
Git Commit: f2af156fadc052c641aaddaa1282f825f6474de0
```

**Comment by kadern0** [comment]
Hi @nimamahmoudi same version works fine for me. Do you have helm3 installed? Could you try same command with `--helm3=false` to see if this could be the issue?

**Comment by nimamahmoudi** [comment]
@kadern0 Thanks for following up. I checked the cluster and it seems like it had metrics-server installed by default (don't know why it was enabled by default, but I also had traefik ingress installed there by default). I expected it to work like installing Kubernetes. Issue is resolved.
