### ISSUE TITLE
get.sh script exists with non-zero exit code on CentOS 

### ISSUE THREAD

**Issue by welteki** [alexellis/arkade#683]
When running `curl -sLS https://get.arkade.dev | sudo sh` on CentOS the script exits with a non-zero exit code. Despite this arkade is installed.

## Expected Behaviour

`curl -sLS https://get.arkade.dev | sudo sh` should exit successfully

## Current Behaviour

`curl -sLS https://get.arkade.dev | sudo sh` exits with non-zero exit code.

## Are you a GitHub Sponsor yet (Yes/No?)

- [x] Yes
- [ ] No

## Steps to Reproduce (for bugs)

Run `curl -sLS https://get.arkade.dev | sudo sh`

Output:
<img width="875" alt="Screenshot 2022-05-04 at 17 21 40" src="https://user-images.githubusercontent.com/16267532/166714698-9ea93072-4dff-4ba9-bdac-58413834aa69.png">

## Context

Discovered this issue while testing https://github.com/openfaas/faasd/pull/261 on CentOS

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```
<img width="1043" alt="Screenshot 2022-05-04 at 17 25 49" src="https://user-images.githubusercontent.com/16267532/166715575-4da983ba-fabf-4700-b438-f5335c743acc.png">

* What arkade version is this?

```
arkade version
```

**Comment by rgee0** [comment]
Replicated:

```
[root@centos-s-2vcpu-2gb-intel-lon1-01 ~]# curl -sLS https://get.arkade.dev | sudo sh
x86_64
Downloading package https://github.com/alexellis/arkade/releases/download/0.8.23/arkade as /tmp/arkade
Download complete.

Running with sufficient permissions to attempt to move arkade to /usr/local/bin
New version of arkade installed to /usr/local/bin
which: no ark in (/sbin:/bin:/usr/sbin:/usr/bin)
Creating alias 'ark' for 'arkade'.
main: line 187: arkade: command not found
```

**Comment by Shikachuu** [comment]
@welteki or @rgee0 can you provide `bash --version`?

If the problem only occures when using the `get.sh`, which seems like the case here since, I think its good to know the bash version!

Thanks! :smile:

**Comment by rgee0** [comment]
This is mine:
```
# bash --version
GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
