### ISSUE TITLE
Feature Request: Add terragrunt as CLI binary to arkade

### ISSUE THREAD

**Issue by MrWormHole** [alexellis/arkade#689]
As a user, I want to be able to install terragrunt just like I install terraform. I will be willing to do a PR for this awesome project and the legend maintainer. Terragrunt is basically kustomize for terraform files.

Note: I would like to do this task if approval is given

## Expected Behaviour

When I do arkade get terragrunt, it should get it to arkade's installed directory.

## Current Behaviour

can not install terragrunt

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No :( (I will be hopefully again)

## Context

It is a suggestion, I don't know the terms and agreements of terragrunt, terragrunt is maintained by these folks gruntwork.io

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at:  16,839 in total

https://somsubhra.github.io/github-release-stats/

## Your Environment

* What Kubernetes distribution are you using? 1.22.4

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS): Fedora Linux

Linux sourbrownie 5.17.5-200.fc35.x86_64 #1 SMP PREEMPT Thu Apr 28 15:41:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
uname -a

cat /etc/os-release
```

* What arkade version is this? 0.8.11

```
arkade version
```

**Comment by alexellis** [comment]
Fine by me.

Alex

**Comment by MrWormHole** [comment]
hmm @Shikachuu I think that one was for snyk CLI but I managed to add the header wrong, oops.

**Comment by alexellis** [comment]
I've added this into Arkade via a commit.
