### ISSUE TITLE
Increase FindGitHubRelease timeout

### ISSUE THREAD

**Issue by sagneessens** [alexellis/arkade#693]
The timeout for finding the latest github release is set to 5 seconds currently and this causes a timeout error.

## Expected Behaviour

The get timeout should be able to find the latest version and install the app.

## Current Behaviour

```
arkade get k3sup                                                                                                            ✔  6s   11:12:55  
Downloading: k3sup
2022/05/19 11:22:37 Looking up version for k3sup
Error: Head "https://github.com/alexellis/k3sup/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Possible Solution

Increase the timeout value in the FindGIthubRelease function to 10 seconds: https://github.com/alexellis/arkade/blob/0acde43ee7abf23dc2f0164faad5ccb352cef3a2/pkg/get/get.go#L178-L185

## Steps to Reproduce (for bugs)

1. arkade get k3sup

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux 2022010001P 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* What arkade version is this?

```
            _             _
  __ _ _ __| | ____ _  __| | ___
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Open Source Marketplace For Developer Tools

Version: 0.8.24
Git Commit: 0acde43ee7abf23dc2f0164faad5ccb352cef3a2

 🐳 arkade needs your support, learn more: https://my.arkade.dev
```

**Comment by alexellis** [comment]
How do you know that a longer timeout would fix this? The GitHub HTTP URL should be instant and never take more than a few milliseconds.

You could try a local patch to see, but my suspicion is that you have some local networking issues.

Alex

**Comment by cyantarek** [comment]
Nonetheless, I think the error message returned from the tool is very cryptic and not so user friendly honestly.

`Error: Head "https://github.com/alexellis/k3sup/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
`
Could be returned like this
`Error: Timeout while waiting for getting response back from the release repository`

**Comment by alexellis** [comment]
There's no reason that I can think of why GitHub would take more than a few milliseconds to complete a HTTP request. Increasing the timeout is the wrong solution, but you're welcome to do a local build to see if it's different. 

You may not like the error message, however it's from the Go standard library, so I'd suggest you raise an issue with Google and see if they can accommodate you.

As mentioned before, you may need to check your own networking.

Do you live in a country with a restrictive or invasive proxy/interception policy? Or do you use a work VPN? Either of those points could cause GitHub to be blocked.

**Comment by sagneessens** [comment]
I've tested it with the extended timeout of 10 seconds and I can confirm that works.
It is however on an company network and on rerouting the traffic through another VPN it works as expected with the 5 second timeout.

So it is indeed a networking issue.

Perhaps a timeout flag or some documentation on this subject can help on preventing this issue with other user on a company network in the future?

**Comment by alexellis** [comment]
@sagneessens please feel free to go ahead and change the timeout to 10 seconds. Thank you for working through the comments with me.
