### ISSUE TITLE
add --helm3 to the  minio app

### ISSUE THREAD

**Issue by Waterdrips** [alexellis/arkade#7]
## Expected Behaviour

we should be able to use helm3 for minio and make it default
## Current Behaviour

helm2
## Possible Solution

add helm3 using the same pattern as other apps

**Comment by Waterdrips** [comment]
Derek add label: help wanted, skill/beginner, good first issue

**Comment by kadern0** [comment]
While working on this, I've found an issue in the code. If the user doesn't supply access and secret keys, they get generated with:
`password.Generate()`

Then we pass such keys within the `overrides` parameter to `helm3Upgrade` and in there, we parse them and use them as `Args` in `execute.ExecTask`.

The problem is that the key contains a "," the task execution will fail because it will be unable to parse the arguments.

Example (I've added code to print all the arguments passed to the task):
```
./arkade install minio
Using kubeconfig: /home/kaderno/.kube/config
Using helm3
Client: x86_64, Linux
2020/03/08 18:06:54 User dir established as: /home/kaderno/.arkade/
"stable" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "openfaas" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
Access Key not provided, one will be generated for you
Secret Key not provided, one will be generated for you
VALUES values.yaml
upgrade
--install
minio
stable/minio
--namespace
default
--values
/tmp/charts/minio/values.yaml
--set
accessKey=6v5l4b854Zh483OmNya7
--set
secretKey=gwZ7BEspAO761P@qRjIX7&W[9UW8TJ53J,gH8V\r
--set
persistence.enabled=false
Command: /home/kaderno/.arkade/bin/helm3/helm [upgrade --install minio stable/minio --namespace default --values /tmp/charts/minio/values.yaml --set accessKey=6v5l4b854Zh483OmNya7 --set secretKey=gwZ7BEspAO761P@qRjIX7&W[9UW8TJ53J,gH8V\r --set persistence.enabled=false]
Error: failed parsing --set data: key "gH8Vr" has no value
Error: exit code 1, stderr: Error: failed parsing --set data: key "gH8Vr" has no value
```

**Comment by Waterdrips** [comment]
Can the keys be quoted? Will that fix the problem?

**Comment by kadern0** [comment]
@Waterdrips got it fixed! Sometimes reading the documentation helps :)

**Comment by alexellis** [comment]
Are the values being sent via Command or Args?

**Comment by kadern0** [comment]
Same as before, just limited the allowed symbols within the generated secret key
