### ISSUE TITLE
Feature request: add cilium CLI

### ISSUE THREAD

**Issue by recollir** [alexellis/arkade#702]
## Expected Behaviour
`arkade get cilium` installs the [cilium](https://github.com/cilium/cilium-cli) CLI binary.

## Current Behaviour
Not implemented.

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
Add `cilium` CLI to the `tools.go` file.

## Context
The `cilium` CLI is used to interact with the `cilium` CNI - for installation, configuration and debug tasks. This is in particular useful with `kind` dev clusters.

## If requesting a CLI for "arkade get"
How many downloads does this tool have? 23041.

## Your Environment

* What Kubernetes distribution are you using?

Kubernetes 1.19 to 1.24

* Operating System and version (e.g. Linux, Windows, MacOS):

```
macOS Monterey 12.4
Darwin 21.5.0
```

* What arkade version is this?

```
Version: 0.8.28
Git Commit: 650ceaa1f922602f55bec71b70fe8f239f2b7b2b
```

(Submitting feature request as request in comment for PR #701 - I can refine the PR as requested)

**Comment by recollir** [comment]
A PR based on #701 and the requested changes is ready to be submitted.

**Comment by alexellis** [comment]
Thanks

**Comment by recollir** [comment]
Great. I will submit it then later on this evening.

**Comment by recollir** [comment]
@alexellis See above submitted PR #707. I am ready to use this to also work on #703 once it gets approved and the issue the go ahead.

**Comment by alexellis** [comment]
Merged
