### ISSUE TITLE
Feature request: add hubble CLI

### ISSUE THREAD

**Issue by recollir** [alexellis/arkade#703]
## Expected Behaviour
`arkade get hubble` installs the [hubble](https://github.com/cilium/hubble) CLI binary.

## Current Behaviour
Not implemented.

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
Add `hubble` CLI to the `tools.go` file.

## Context
The `hubble` CLI is used to interact with the `cilium` CNI - for installation, configuration and debug tasks. This is in particular useful with `kind` dev clusters.

## If requesting a CLI for "arkade get"
How many downloads does this tool have? 83009.

## Your Environment

* What Kubernetes distribution are you using?

Kubernetes 1.19 to 1.24

* Operating System and version (e.g. Linux, Windows, MacOS):

```
macOS Monterey 12.4
Darwin 21.5.0
```

* What arkade version is this?

```
Version: 0.8.28
Git Commit: 650ceaa1f922602f55bec71b70fe8f239f2b7b2b
```

(Submitting feature request as request in comment for PR #701 - I can refine the PR as requested)

**Comment by recollir** [comment]
A PR based on #701 and the requested changes is ready to be submitted.

**Comment by recollir** [comment]
Shall I proceed with this, now that #702 is done through #707? @alexellis @Shikachuu

**Comment by Shikachuu** [comment]
> Shall I proceed with this, now that #702 is done through #707? @alexellis @Shikachuu

Sure!

**Comment by recollir** [comment]
PR submitted a minute ago.

**Comment by Shikachuu** [comment]
Thanks for the PR, @recollir I'll close this for now.
