### ISSUE TITLE
Code duplication for kumactl

### ISSUE THREAD

**Issue by recollir** [alexellis/arkade#704]
The code to set up `arkade get` for kumactl is duplicated.

## Expected Behaviour
Single occurance of the code.

## Current Behaviour
Occurrence 1 - lines 2127 to 2150 in `cmd/get/tools.go`:
https://github.com/alexellis/arkade/blob/8b65a09f693cb71403cdcd07937788fa5b5e3c5a/pkg/get/tools.go#L2127-L2150

Occurrence 2 - lines 2180 to 2203 in `cmd/get/tools.go`:
https://github.com/alexellis/arkade/blob/8b65a09f693cb71403cdcd07937788fa5b5e3c5a/pkg/get/tools.go#L2180-L2203

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
Remove one occurrence.

**Comment by alexellis** [comment]
Thanks for mentioning this, would you like to send a PR for us?

Otherwise, @Shikachuu perhaps you can run with this?

**Comment by recollir** [comment]
I can do it, @alexellis.

**Comment by alexellis** [comment]
Great, thank you

**Comment by recollir** [comment]
@alexellis Done. PR submitted.

**Comment by recollir** [comment]
Closing this now. #708 was merged.
