### ISSUE TITLE
Feature request: add gomplate

### ISSUE THREAD

**Issue by AmrSaber** [alexellis/arkade#706]
## Expected Behaviour

`arkade get gomplate` installs [gomplate](https://github.com/hairyhenderson/gomplate) cli

## Current Behaviour

Not implemented
## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

The tool has 628,233 downloads for the latest release

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04

**Comment by alexellis** [comment]
Please go ahead and send us a pull request @AmrSaber 

The easiest way to get started, is to look at a closed and merged pull request to see what to change.

Let us know if you need anything cc @Shikachuu 

Alex
