### ISSUE TITLE
"Forbidden" errors when running kubernetes-dashboard

### ISSUE THREAD

**Issue by eddible** [alexellis/arkade#713]
I've installed kubernetes-dashboard using Arkade but when I run it I get loads of errors, saying:

`namespaces is forbidden: User "system:serviceaccount:kubernetes-dashboard:default" cannot list resource "namespaces" in API group "" at the cluster scope`

The same error is then repeated for every aspect of the dashboard. 

I followed the guide here to the letter but I think something may have changed? : https://alexellisuk.medium.com/walk-through-install-kubernetes-to-your-raspberry-pi-in-15-minutes-84a8492dc95a

This is using a completely fresh install of Raspberry Pi OS (flashed today) on a Raspberry Pi 4 4GB. I'm very new to k3s so apologies if I've missed something obvious, let me know if I can provide further info. The other kubectl commands (such as top node) all work fine, so it looks like the install from k3sup has worked fine. 

## Expected Behaviour
The dashboard should load without permission errors. 

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version 1.22.2
```

* Operating System and version (e.g. Linux, Windows, MacOS): Linux (on a Chromebook)

```
uname -a - Linux penguin 5.10.114-16024-gbdf1547bd4f4 #1 SMP PREEMPT Wed Jun 22 19:04:26 PDT 2022 x86_64 G

cat /etc/os-release - PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* What arkade version is this?

```
arkade version 0.8.28
```

**Comment by Shikachuu** [comment]
This issue seems like a namespace or kubeconfig permission problem.
With the current version of the dashboard you are unable to change the namespace, I'm not sure if this is a global problem or not, but I assume #715 should fix yours at least.
