### ISSUE TITLE
Feature: Allow to configure where to store downloaded binaries with `arkade get`

### ISSUE THREAD

**Issue by Rabattkarte** [alexellis/arkade#716]
## Expected Behaviour

`arkade` should allow me to override the output dir of to be installed apps. Either by a config flag and/or an environment variable such as `ARKADE_BIN_DIR`.

I'd like to see the option to have a bin dir in my project's directory to store the right versions of all necessary tools.

## Current Behaviour

Please consider the following two commands:

1. `arkade get kubectl`

   Downloads the app to `$HOME/.arkade/bin/`, in this case `$HOME/.arkade/bin/kubectl`

1. `arkade get kubectl --stash=false`

   Downloads the app to the per-user temporary files and caches, e.g. `/var/folders/c0/<random>/T/kubectl`

`arkade` is opinionated where to store the downloaded app. This also disables the possibility to install say `kubectl@v1.21.0` and `kubectl@v1.22.0` simultaneity, since the later overwrites the prior.

---

_PS: Not my point, but this behaviour also violates the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)._

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Possible Solution

`arkade` should allow me to override the output dir of to be installed apps. Either by a config flag and/or an environment variable such as `ARKADE_BIN_DIR`.

## Steps to Reproduce (for bugs)

1. `arkade get kubectl` - installs to `$HOME/.arkade/bin/kubectl`
1. `arkade get kubectl@v1.21.0` - also installs to `$HOME/.arkade/bin/kubectl`, **overwriting the last download**
1. `arkade get kubectl@v1.21.0 --stash=false` - installs to a temp dir, making this install not reusable

## Context

I'd like to have different versions of the same tools installed in different contexts at the same time.

## Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS):

```sh
$ uname -a
Darwin <machine name> 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
```

- What arkade version is this?

```sh
$ arkade version
Version: 0.8.28
Git Commit: 650ceaa1f922602f55bec71b70fe8f239f2b7b2b
```

Installed via `brew install arkade`.

**Comment by dirien** [comment]
I like this idea, and would love to implement it.

**Comment by Shikachuu** [comment]
I also like the idea, to create a flag or an env var (ideally both) for the bin directory.
Should we add something like this? @alexellis

**Comment by Shikachuu** [comment]
> I'm coming in a bit late to this one.
> 
> I want to make sure we are driving this from a use-case, rather than adding a feature because "it would be nice" or "this could be made configurable, so the right choice is to make it so"
> 
> Can you clarify that you have a concrete usecase where you want two versions of kubectl and are planning on putting them in two different folders?
> 
> Another way of asking this is: why do you specifically need this?
> 
> If it's because you want multiple versions of the same tool, that's a problem that we can think about as a group. "I want to store binaries where I want" is a technical solution, without a concrete problem.

There is an easy to replicate concrete use case for this one regarding `kubectl` specifically!

Lets assume you have 2 K8s clusters, one running v1.21.x and the other running v.1.24.x, ideally you would like to use different `kubectl`s for each cluster, [the offical docs state this too](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#before-you-begin).

**Comment by alexellis** [comment]
I'm not sure that's a use-case that needs two versions of the same tool.

The documentation says that you can use later versions of kubectl for older clusters

> For example, a v1.24 client can communicate with v1.23, v1.24, and v1.25 control planes. Using the latest compatible version of kubectl helps avoid unforeseen issues.
