### ISSUE TITLE
Feature request: add talosctl

### ISSUE THREAD

**Issue by mrichar1** [alexellis/arkade#720]
## Expected Behaviour
`arkade get talosctl` should install the Talos Linux OS cli tool: https://www.talos.dev/

## Are you a GitHub Sponsor yet?

- [ ] Yes
- [X] No

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

1097 downloads of talosctl for release 1.1.0 (2022-06-22)

**Comment by Shikachuu** [comment]
Hey @mrichar1,
Thanks for the intrest in arkade!
Please go ahead and create a PR for this, there are a lot of great examples in the merged PRs.

Let us know if you need anything!
