### ISSUE TITLE
Add just to arkade get

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#721]
## Expected Behaviour
`arkade get just` installs just.

## Current Behaviour
Not implemented.

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
Add just as an installable cli tool.

## Context
Just is a really nice, modern alternative for GNU make.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? **210,429**
https://somsubhra.github.io/github-release-stats/?username=casey&repository=just&page=1&per_page=5

## Your Environment

* What Kubernetes distribution are you using?

```
{
  "clientVersion": {
    "major": "1",
    "minor": "24",
    "gitVersion": "v1.24.0",
    "gitCommit": "4ce5a8954017644c5420bae81d72b09b735c21f0",
    "gitTreeState": "clean",
    "buildDate": "2022-05-03T13:46:05Z",
    "goVersion": "go1.18.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.4"
}

```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux desktop 5.18.11-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 12 22:52:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
Version: 0.8.28
Git Commit: 650ceaa1f922602f55bec71b70fe8f239f2b7b2b
```

**Comment by Shikachuu** [comment]
Also if this tool gets accepted/merged we could create a PR for just, to add arkade as a package manager in the following readme section: https://github.com/casey/just#packages=

**Comment by alexellis** [comment]
Thanks for the suggestion. Feel free to try it out and if it makes sense as a downloadable app, put the PR up for me to merge 👍
