### ISSUE TITLE
add example of Ingress for gitea

### ISSUE THREAD

**Issue by blaisep** [alexellis/arkade#725]
Thank you @Technowlogick I was excited to see gitea... but I want to use it with Ingress and not `port-forward`
Do you have an example handy?

If not, I can write it up as a blog post. It would be nice to give arkade some more love.
@alexellis ?

_Originally posted by @techknowlogick in https://github.com/alexellis/arkade/issues/212#issuecomment-691319223_

**Comment by Shikachuu** [comment]
I think it would be nice if you create a write up about this, but you can update the post install message too if you want to.

Also can you fill the whole issue template please?

**Comment by alexellis** [comment]
> Also can you fill the whole issue template please?

+1 to this

We have an `openfaas-ingress` app, perhaps you were thinking of something like that?

The Gitea chart supports ingress, so you can just set those values via `arkade install gitea --set key=value`

Have a look here for what you need:

https://gitea.com/gitea/helm-chart/#ingress

Bear in mind that there's SSH access along with HTTP as options. SSH can't be exposed through ingress and would require a NodePort or a TCP LoadBalancer (like Inlets can provide)

Let us know if you have any issues setting the ingress as it seems to use an array / slice `ingress.hosts[0].host`

**Comment by blaisep** [comment]
Oh! That's right, I have the inlets-operator running but not open faas
ingress

**Comment by alexellis** [comment]
OK great, so I think we've answered the question. I'm going to close this and let us know how you get on with the ingress.hosts syntax and the `--set` flag for the gitea app.
