### ISSUE TITLE
Add lazygit to arkade get

### ISSUE THREAD

**Issue by welteki** [alexellis/arkade#729]
Lazygit is simple terminal UI for git commands.
https://github.com/jesseduffield/lazygit

## Expected Behaviour

`arkade get lazygit` install lazygit

## Current Behaviour

Not implemented

## Are you a GitHub Sponsor yet (Yes/No?)

- [x] Yes
- [ ] No

## Possible Solution

Add lazygit as an installable cli tool.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Lazygit is a simple terminal UI for git commands. It simplifies the use of some powerful git features.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? 49,094
https://somsubhra.github.io/github-release-stats/?username=jesseduffield&repository=lazygit&page=1&per_page=5

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux cromulon 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?
```
Version: 0.8.30
Git Commit: f80689248728d4ba1385fb46d858fb494ffd5743
```

**Comment by alexellis** [comment]
/add label: status/approved, good first issue, help wanted

**Comment by Jasstkn** [comment]
I would like to work on this task too if you don't mind :)

**Comment by Shikachuu** [comment]
> I would like to work on this task too if you don't mind :)

Sure, let us know if you need a hand!

Thanks for picking this up! :smile:
