### ISSUE TITLE
Add golangci-lint to arkade get

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#730]
## Expected Behaviour
`arkade get golangci-lint` installs the tool

Link to project: https://github.com/golangci/golangci-lint

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
Add golangci-lint to pkg/get/tools.go

## Context
Install it as a linter.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Total downloads: 275,446

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux t570 5.18.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 3 15:44:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
Version: 0.8.30
Git Commit: f80689248728d4ba1385fb46d858fb494ffd5743
```

**Comment by alexellis** [comment]
/add label: help wanted, good first issue

**Comment by Jasstkn** [comment]
@alexellis Hello. May I work on this?

**Comment by Shikachuu** [comment]
> @alexellis Hello. May I work on this?

Sure, let me know if you need anything!

**Comment by alexellis** [comment]
👍 

When do you think you can get to it?

I'd suggest looking at recently merged PRs for an example of what we are looking for.

**Comment by Jasstkn** [comment]
> 👍
> 
> When do you think you can get to it?
> 
> I'd suggest looking at recently merged PRs for an example of what we are looking for.

I am going to start working on this today. Thanks for pointing to the examples, I will definitely check them out.

**Comment by Jasstkn** [comment]
FYI: I submitted a PR.
