### ISSUE TITLE
Add colima to arkade get 

### ISSUE THREAD

**Issue by Jasstkn** [alexellis/arkade#744]
## Expected Behaviour

`arkade get colima` installs lima 

Link to the project: https://github.com/abiosoft/colima/blob/main/docs/INSTALL.md

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Possible Solution

Add colima to pkg/get/tools.go

## Context

I use colima pretty often to use as a replacement for docker and spin up Kubernetes

## If requesting a CLI for "arkade get"

687

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:36:49Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:58Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Darwin laptoplocal.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
```

* What arkade version is this?

```
Version: 0.8.34
Git Commit: b273819ddf3f78f5d23f5af204ed815638f97d56
```

**Comment by alexellis** [comment]
The way that Lima is packaged isn't compatible with arkade and the maintainer actively said he wasn't going to change the packaging to suit arkade better.

I'm not sure if colima has the same issues? https://github.com/lima-vm/lima/issues/591

**Comment by Jasstkn** [comment]
Yes, you are right. If deps aren't satisfied (e.g. limactl) it won't work.

**Comment by alexellis** [comment]
There may be a case for using `arkade system install` here. What kinds of steps are required to install Lima?

**Comment by Jasstkn** [comment]
@alexellis Hello. For lima installation steps aren't trivial tho:
https://github.com/lima-vm/lima#installation

**Comment by Jasstkn** [comment]
I checked installation requirements. As a first step we have to install qemu which isn't possible via single binary - it either requires brew or `make` call from the directory with qemu's source code.
