### ISSUE TITLE
Arkade installs old version of Helm

### ISSUE THREAD

**Issue by krzwiatrzyk** [alexellis/arkade#745]
Currently the newest version of Arkade installs Helm in version 3.5.2.
Newest Helm is in version 3.9.1.

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

**Comment by alexellis** [comment]
Hi @krzwiatrzyk, tanks for your interest. Please do fill out the whole template, which includes questions where you can tell us how this affects you and whether you're willing to send a PR to fix it.

**Comment by Jasstkn** [comment]
As we discussed, I started working on it here: https://github.com/alexellis/arkade/pull/746
