### ISSUE TITLE
Add butane to arkade

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#748]
## Expected Behaviour
`arkade get butane` installs butane.

## Current Behaviour
Not implemented

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
Add Butane to `pkg/get/tools.go`

## Context

Butane is a CoreOS config transpiler, generates Ingition files used for Flatcar Linux and Fedora/RedHat CoreOS.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

Github Downloads: 1,201
But the docs advocates to use the docker image.

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.22.2+k3s2
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux desktop 5.18.19-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 21 15:52:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
Version: 0.8.32
Git Commit: b004f9adb0f90c89ef1440f988685fd6b6111d3f
```

**Comment by alexellis** [comment]
Go for it @Shikachuu
