### ISSUE TITLE
Add hadolint to arkade

### ISSUE THREAD

**Issue by Shikachuu** [alexellis/arkade#749]
## Expected Behaviour
`arkade get hadolint` installs hadolint.

## Current Behaviour
Not implemented

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
Add Hadolint to `pkg/get/tools.go`

## Context
Hadolint is one of the most popular docker file linter, I mostly use it in my gitlab CI for my personal projects.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

Github Downloads: 216,390
DockerHub Downloads:
![image](https://user-images.githubusercontent.com/32636587/186944795-1b2bd205-73c8-4589-a268-f43884221ef6.png)

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.22.2+k3s2
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux desktop 5.18.19-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 21 15:52:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
Version: 0.8.32
Git Commit: b004f9adb0f90c89ef1440f988685fd6b6111d3f
```

**Comment by alexellis** [comment]
I don't trust Docker Hub stats but if you use this we could add it. Feel free to go ahead
