### ISSUE TITLE
Error when arkade get helmfile mac m1

### ISSUE THREAD

**Issue by Jasstkn** [alexellis/arkade#760]
Arkade fails when trying to install helmfile:

```bash
arkade get helmfile
Downloading: helmfile
2022/09/02 11:34:33 Looking up version for helmfile
2022/09/02 11:34:34 Found: v0.144.0
Downloading: https://github.com/roboll/helmfile/releases/download/v0.144.0/helmfile_darwin_386
Error: incorrect status for downloading tool: 404
```

## Expected Behaviour

arkade successfully installs helmfile

## Current Behaviour

404 not found

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Possible Solution

1. helmfile migrated to dedicated org, owner field should be updated to `helmfile`
2. in the new repo binary is replaced by archive with `tar.gz`, so we need to update template
3. Condition should be added 
```go
{{- else if or (eq .Arch "aarch64") (eq .Arch "arm64") -}}
{{$arch = "arm64"}}
```

## Steps to Reproduce (for bugs)

1. run `arkade get helmfile`
4.
5.
6.

## Context

Can't install helmfile via arkade

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:36:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Darwin mariakot-osx 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64
```

* What arkade version is this?

```
Version: 0.8.39
Git Commit: 2e76c2c3681a3796b03483c3c04fb2ebcba0fa3e
```

**Comment by Jasstkn** [comment]
I'll work on this one later today if there are no objections.

**Comment by Shikachuu** [comment]
> I'll work on this one later today if there are no objections.

Sure, thanks!
