### ISSUE TITLE
[CLI request] flyctl

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#766]
## CLI suggestion - flyctl

This is the CLI for fly.io and I wanted it whilst following: https://github.com/jsiebens/inlets-on-fly

https://github.com/superfly/flyctl/releases

**Comment by alexellis** [comment]
Would either of you like to pick this up @YuviGold / @Shikachuu / @Jasstkn ?

**Comment by Jasstkn** [comment]
I'll take it. I'm going to submit PR later today.
