### ISSUE TITLE
Add tc-redirect-tap to system apps

### ISSUE THREAD

**Issue by welteki** [alexellis/arkade#768]
Add a system app to install the tc-redirect-tap CNI plugin. The plugin allows you to adapt pre-existing CNI plugins/configuration to a tap device.

Binaries are being built in this repo of Alex:
https://github.com/alexellis/tc-tap-redirect-builder

## Expected Behaviour

`arkade system install tc-redirect-tap` should install tc-redirect-tap

## Current Behaviour

No system app for tc-redirect-tap

## Are you a GitHub Sponsor yet (Yes/No?)

- [x] Yes
- [ ] No

## Possible Solution

This should be similar to the cni plugins system app, except that it is just a single binary instead of a multiple binaries in a tar archive.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

We need this for actuated. There is no binary release available in the official repo.

**Comment by welteki** [comment]
Would you like to pick this up @Jasstkn?

**Comment by Jasstkn** [comment]
> Would you like to pick this up @Jasstkn?

hey. If it's not super urgent and expected to be done strictly today, then yes, I can take this into work :)

**Comment by alexellis** [comment]
Does by the end of the weekend sound reasonable?

**Comment by Jasstkn** [comment]
> Does by the end of the weekend sound reasonable?

Yep, I'll definitely manage to submit a PR by it 👍🏻

**Comment by welteki** [comment]
Hi @Jasstkn. Have you started to work on this already?

**Comment by alexellis** [comment]
@welteki please can you run with this, so we can get the app in place now that it's been two weeks without a PR?

**Comment by alexellis** [comment]
Thanks @welteki
