### ISSUE TITLE
Command to get the RabbitMQ secret results in empty string

### ISSUE THREAD

**Issue by ibliss** [alexellis/arkade#773]
The command at 
https://github.com/alexellis/arkade/blob/master/cmd/apps/rabbitmq_app.go#L117
does not work

## Expected Behaviour
The command given should output the secret

## Current Behaviour
There is no output
Suggestion: Correct the command, and add a newline to improve readability

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
https://github.com/alexellis/arkade/compare/master...ibliss:arkade:master

## Steps to Reproduce (for bugs)
1. ark install rabbitmq
2. ark info rabbitmq
3. Run the command given under "# To get your password run:"

## Context
Quickly set up a RabbitMQ service for prototyping systems.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

## Your Environment

* What Kubernetes distribution are you using?

MacOS / Docker Desktop with Kubernetes
```
 kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
MacOS 12.6
```

* What arkade version is this?

```
$arkade version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Open Source Marketplace For Developer Tools

Version: 0.8.42
Git Commit: cd54f6a171afb07ef27f8e8e23e9cb13a4e3878b

 🐳 arkade needs your support: https://github.com/sponsors/alexellis
```

**Comment by alexellis** [comment]
PRs are welcome if you know what the command should be

Otherwise if you'd like to become a sponsor maybe we can spend a few hours to look into it for you

**Comment by alexellis** [comment]
@DavidIsa do you have time to look into this for @ibliss?

**Comment by DavidIsa** [comment]
Yes, I will look into it

**Comment by alexellis** [comment]
Thank you 🙏
