### ISSUE TITLE
[Feature Request] Adding Consul & Vault support

### ISSUE THREAD

**Issue by developer-guy** [alexellis/arkade#78]
There is a great documentations for usage of Helm charts of these Hashicorp tools like Consul & Vault. 

It would be great if we added Consul & Vault installation support to Arkade.

https://www.vaultproject.io/docs/platform/k8s/helm/configuration/
https://www.consul.io/docs/platform/k8s/helm.html

**Comment by Waterdrips** [comment]
/close
Superseded by #202 and #203 

We are happy to take contributions for these implementations :+1:
