### ISSUE TITLE
[Question] Unusable offline?

### ISSUE THREAD

**Issue by shawnngtq** [alexellis/arkade#780]
This is unusable for offline machine right?

## Are you a GitHub Sponsor yet (Yes/No?)
- [ ] Yes
- [x] No

## Context

I am using **restrictive offline redhat VM**. This is the recommended tool to install openfaas over helm and I am really hoping somehow it's usable.

Otherwise, I have no choice but to go with helm and deal with the complexities.

If you offer this offline feature, it will be helpful for enterprise users.

## Your Environment

**Comment by alexellis** [comment]
Helm is the right tool for an offline installation of OpenFaaS.

Feel free to reach out to us if you need support air gapping OpenFaaS CE / OpenFaaS Pro. https://openfaas.com/support

You may also want to look at faasd, which doesn't use helm or Kubernetes and has a bash installer: https://github.com/openfaas/faasd

**Comment by alexellis** [comment]
/set title: Can I install the openfaas arkade app without the Internet?
