### ISSUE TITLE
Add Temporal's CLI to arkade get

### ISSUE THREAD

**Issue by Jasstkn** [alexellis/arkade#791]
## Expected Behaviour

`arkade get tctl` works

https://github.com/temporalio/tctl

## Current Behaviour

No such CLI is added

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Possible Solution

Add to `pkg/get/tools.go`

## Context

Can't install tctl via arkade

## If requesting a CLI for "arkade get"

How many downloads does this tool have? 3,387

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

Darwin mariarti-laptoplocal.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64
```

* What arkade version is this?

```
arkade version
Version: 0.8.45
Git Commit: 7b7ade38cff998b68886fe7f1260d080e881383a
```

**Comment by alexellis** [comment]
Go for it @Jasstkn
