### ISSUE TITLE
add eksctl-anywhere to arkade get

### ISSUE THREAD

**Issue by tuxtof** [alexellis/arkade#792]
## Expected Behaviour

`arkade get eksctl-anywhere` works

[eks-anywhere](https://github.com/aws/eks-anywhere)

## Current Behaviour

Error: tool eks-anywhere not found

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4"
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release

Linux jump 5.15.0-1020-kvm #24-Ubuntu SMP Fri Oct 14 08:03:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

* What arkade version is this?

```
arkade version
Version: 0.8.47
```

**Comment by alexellis** [comment]
If it has a static binary then please feel free to send us a PR for this. 

For a guide on how to add it and test it, please see recently closed PRs. @Jasstkn provides good examples

**Comment by tuxtof** [comment]
Hello @alexellis 
if external PR are accepted , let's do it
