### ISSUE TITLE
Add Support for clusterawsadm

### ISSUE THREAD

**Issue by tuxtof** [alexellis/arkade#803]
## Expected Behaviour

Add Support for clusterawsadm CLI

## Current Behaviour
NA

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

  Total Downloads 62,680

**Comment by alexellis** [comment]
Adding the "missing link": https://cluster-api-aws.sigs.k8s.io/clusterawsadm/clusterawsadm.html 🙂 

Feel free to send a PR for this, use a closed PR as a template and pay attention to the testing steps we require too.
