### ISSUE TITLE
[Feature Request] Add Jenkins App

### ISSUE THREAD

**Issue by aidun** [alexellis/arkade#82]
@alexellis want to have Jenkins as app in Arkade

## Expected Behaviour

Jenkins should be installed to the cluster and should be able to run jobs. In addition it would be nice, if Jenkins could spawn containers as worker nodes.

## Possible Solution

* Jenkins should be install via the https://github.com/helm/charts/tree/master/stable/jenkins helm chart. 
* Jenkins should run in its own namespace
* There should be proper resource limits for doing a maven build
* Jenkins should be reachable via LoadBalancer and with admin credentials
* The Kubernetes integration should be able to deploy applications and manifests to any namespace of the cluster

**Comment by alexellis** [comment]
The only acceptance criteria for me is the following:

> Jenkins should be install via the https://github.com/helm/charts/tree/master/stable/jenkins helm chart.

That's it, and it's more or less a one-liner.

Beyond that I'd like to see the usual checks on arm and the persistence flag set to false by default.

If the chart has an LB option, feel free to bubble that up in a flag too, like we do with openfaas. 

Do you think you'd have time to work on the app this week?

**Comment by aidun** [comment]
Okay, no Problem, I can implement it in this way. I think I can do it today or tomorrow.

**Comment by aidun** [comment]
I think I have the PR ready, but some strange behavior while testing. I think it might be a problem of my internet connection. I think I can push it tested this evening.
