### ISSUE TITLE
arkade get hostctl fails on m1 mac

### ISSUE THREAD

**Issue by lakamsani** [alexellis/arkade#822]
with reference to that `hostctl` CLI listed here https://github.com/alexellis/arkade#catalog-of-clis , `arkade get hostctl` fails like this:

```
Downloading: hostctl
2022/12/10 12:30:12 Looking up version for hostctl
2022/12/10 12:30:13 Found: v1.1.3
Downloading: https://github.com/guumaster/hostctl/releases/download/v1.1.3/hostctl_1.1.3_macOS_.tar.gz
Error: incorrect status for downloading tool: 404
```
possibly due to M1 mac. Worked on a x86 mac before. Able to build `hostctl` from the code. So not a blocker, just FYI.

**Comment by rgee0** [comment]
@lakamsani [0.8.52](https://github.com/alexellis/arkade/releases/tag/0.8.52) has been released which _should_ resolve this issue

**Comment by lakamsani** [comment]
just tried on my M1 and got the same error. Does  the fix take some more time to propagate? lmk when I can re-test/confirm on my M1. thanks. 

```
arkade get hostctl
Downloading: hostctl
2022/12/25 12:30:48 Looking up version for hostctl
2022/12/25 12:30:48 Found: v1.1.3
Downloading: https://github.com/guumaster/hostctl/releases/download/v1.1.3/hostctl_1.1.3_macOS_.tar.gz
Error: incorrect status for downloading tool: 404
```

**Comment by rgee0** [comment]
What does `arkade version` show?

**Comment by lakamsani** [comment]
yes, had the older version. Works with the 0.8.52 version or `arkade`. Thanks for the fix.
