### ISSUE TITLE
arkade get helm downloads an old version

### ISSUE THREAD

**Issue by vassie79** [alexellis/arkade#831]
## Expected Behaviour
`arkade get helm` should install the latest version (v3.10.3 as of writing)

## Current Behaviour
```
arkade get helm
Downloading: helm
Downloading: https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz
```

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Steps to Reproduce (for bugs)

1. Run `arkade get helm`

## Context

Currently downloading the binary manually.

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:18:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15-gke.100", GitCommit:"4262ac74f84d8f8ec8f692ea2080483e932554f9", GitTreeState:"clean", BuildDate:"2022-09-22T09:24:03Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux DESKTOP-QE2MDKG 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

* What arkade version is this?

```
Version: 0.8.52
Git Commit: 2e201a1a48bf273cc7cd61111159a96aa3f28215
```

**Comment by rgee0** [comment]
Looks like a chore: https://github.com/alexellis/arkade/issues/745

**Comment by alexellis** [comment]
Hi @vassie79 

We used to pin the version of Helm used for compatibility issues with certain charts.

I'm going to unpin it, which will close this issue.

Thanks for using arkade.

Alex

**Comment by vassie79** [comment]
Thanks @alexellis but it looks like removing the version has caused this issue...
```
arkade get helm
Downloading: helm
Downloading: https://get.helm.sh/helm--linux-amd64.tar.gz
Error: incorrect status for downloading tool: 404
```

**Comment by alexellis** [comment]
OK, perhaps we need to keep pinning the version then.

**Comment by alexellis** [comment]
Have fun, and please [support arkade](https://github.com/alexellis/arkade#help-fund-arkade-) if you find it useful

https://github.com/alexellis/arkade/releases/tag/0.8.54
