### ISSUE TITLE
Add syft/grype CLIs from anchore

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#839]
Add syft/grype CLIs from anchore

## Context

These tools are often used to generate Software Bill of Materials files and to scan for vulnerabilities in software.

https://github.com/anchore/syft/releases/ - Linux / Darwin / Windows available

https://github.com/anchore/grype/releases - Linux / Darwin only

**Comment by Jasstkn** [comment]
> @Jasstkn would you be interested in picking this up?

I will implement it later today if it's fine :)

**Comment by Jasstkn** [comment]
First PR is wired: https://github.com/alexellis/arkade/pull/841.
I'll mark the second PR as closing this issue.

**Comment by Jasstkn** [comment]
Another one is ready. https://github.com/alexellis/arkade/pull/842
JFYI: grype is also available for windows (see the full list of releases on the project's page).
