### ISSUE TITLE
Add links to projects in the Catalog of CLIs section of the README

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#845]
## Expected Behaviour

I'd like to be able to link to each project using the URL we have for the tool, when generating the markdown output for the README

## Current Behaviour

Not available right now.

## Possible Solution

Output a URL from the tool's definition?

**Comment by Jasstkn** [comment]
Looks like good issue that I can help to implement. @alexellis let me know if you don't mind it 😎

**Comment by alexellis** [comment]
Yes please
