### ISSUE TITLE
Add Support for croc

### ISSUE THREAD

**Issue by tuxtof** [alexellis/arkade#850]
## Expected Behaviour

Add croc CLI to the arkade get
https://github.com/schollz/croc

## Current Behaviour
Error: tool croc not found

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

Total Downloads: 115,077

**Comment by alexellis** [comment]
Hey there

Is this a tool that you will personally download with arkade?

Are you planning on sending a PR?

Alex

**Comment by tuxtof** [comment]
Hello Alex

Yes twice

You ask me to create issue before each PR

So am I 🤓
