### ISSUE TITLE
Improve output when arkade get gives a 404

### ISSUE THREAD

**Issue by Jasstkn** [alexellis/arkade#853]
## Expected Behaviour

`arkade get <tool>` should print a friendly message that this tool maybe unavailable for the current architecture: <arch x os >. Check using link:, if it's there, create an <issue>(link). If you want you can contribute and submit a PR to fix this, bla, bla.

## Current Behaviour

```bash
arkade get gh
Downloading: gh
2023/02/05 15:59:25 Looking up version for gh
2023/02/05 15:59:25 Found: v2.22.1
Downloading: https://github.com/cli/cli/releases/download/v2.22.1/gh_2.22.1_macOS_arm64.tar.gz
Error: incorrect status for downloading tool: 404
```

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Possible Solution

1. ask users to create an issue / submit a PR if the binary can be installed.
2. prints out the possibility that the binary can't be installed

## Steps to Reproduce (for bugs)

1. arkade get gh on ARM x darwin.
2.
3.
4.

## Context

Pretty often I'm trying to install a tool and it's not clear if it doesn't exist for ARM or we have a bug. Printing links can speed up things as we already have projects' links in the readme description. That means that it should be fairly easy to improve UX.

**Comment by alexellis** [comment]
Thanks for the suggestion. Happy to review the PR.

Alex
