### ISSUE TITLE
Fix viddy tool

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#856]
## Expected Behaviour

E2e tests should pass, but the [viddy tool](https://github.com/sachaos/viddy/releases) has had a breaking change and is causing a failure.

## Possible Solution

Investigate what changed and update templates

## Steps to Reproduce (for bugs)

1. `make e2e`

https://github.com/alexellis/arkade/actions/runs/4194318807/jobs/7272319718

**Comment by rgee0** [comment]
Error is HTTP/403

The paths looks the same and there hasn't been a Viddy release since June 2022.

A subsequent run https://github.com/alexellis/arkade/actions/runs/4199349285/jobs/7284102754 completed successfully.  

Could this have been a transient issue?

**Comment by Jasstkn** [comment]
Works to me as well:
```
PASS
coverage: 54.4% of statements
ok      github.com/alexellis/arkade/pkg/get     17.942s coverage: 54.4% of statements
```

**Comment by alexellis** [comment]
Thanks both for looking.
