### ISSUE TITLE
May need a default version upgrade for `arkade install linkerd`

### ISSUE THREAD

**Issue by mrwormhole** [alexellis/arkade#864]
I have installed fresh k3s cluster, when I wanted to do `arkade install linkerd`, there was a problem with helm chart, see below

![image](https://user-images.githubusercontent.com/22800416/222822756-8cc815ed-8262-4c4d-847b-48dce93d07be.png)

I quickly googled and found out that it needs to correct helm chart kind from batch/v1beta1 to batch/v1 which Linkerd stable-2.12.0 uses now

---

![image](https://user-images.githubusercontent.com/22800416/222822607-38a7b7d0-0e19-4360-ab18-9a6be7a911ac.png)

https://github.com/alexellis/arkade/blob/master/cmd/apps/linkerd_app.go

https://github.com/linkerd/linkerd2/issues/9523

## Expected Behaviour

when I run `arkade install linkerd` should install correct via helm chart?? I am not sure, if apps is using manifests or charts, I am so terrible at understanding helm charts and where they come from and who stores where (YAML files are my nightmares)

## Current Behaviour

I believe current behaviour is using old version of helm charts but k8s API has changed in 1.25 or 1.26?

## Are you a GitHub Sponsor yet (Yes/No?)
yep

- [X] !Yes!1!1one1!
- [ ] No

## Possible Solution

need to change helm chart's resource kind from batch/v1beta1 to batch/v1 which Linkerd stable-2.12.0 uses now, but feel free to point me in a direction where I can understand the root cause more

## Steps to Reproduce (for bugs)

1. Install fresh version of k3s
2. do `arkade install linkerd`

## Context

I am trying to install linkerd, If issue is not resolved, I will heck in with bare manifests. I am expecting some sort of helm chart breakage, they are quite famous with helm 3 and helm 2 incompatible changes breakthrough :dagger: 

## Your Environment

* What Kubernetes distribution are you using?

k3s

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:47:47Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

Linux sourbrownie 6.1.11-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  9 19:20:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

NAME="Fedora Linux"
VERSION="37 (Workstation Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation

* What arkade version is this?

Version: 0.8.56
Git Commit: faff958880813d477a3b8d433a87a61fc1bc1611

**Comment by mrwormhole** [comment]
no longer an issue https://github.com/alexellis/arkade/blob/master/cmd/apps/linkerd_app.go#L25, works when version is specified as 2.12.0

**Comment by alexellis** [comment]
Hey thanks for dropping by. Would you like to send a PR?

**Comment by mrwormhole** [comment]
if I change this constant, it is likely to break v1.26 below k8s clusters btw, it may not be an issue or it may be an issue https://github.com/alexellis/arkade/blob/master/cmd/apps/linkerd_app.go#L25

**Comment by alexellis** [comment]
So Linkerd released a change that breaks in K8s 1.25 and lower? That doesn't sound like their style.

Can you confirm through testing?

If so, which I really find hard to believe, then we'd just maintain an if statement in the code after fetching the K8s version.

cc @wmorgan for comment

**Comment by joebowbeer** [comment]
Clarifications:

`arkade install linkerd` installs using the linkerd CLI (as recommended) not helm.

The version currently installed is stable-2.11.1 (10/28/2021), which is behind the current release: stable-2.13.0

The minimum Kubernetes version supported by stable-2.11.0 was v1.17.0
The minimum Kubernetes version supported by stable-2.13.0 is v1.21.0

https://linkerd.io/2.13/tasks/upgrade/#upgrade-notice-stable-2-13-0

**Comment by mrwormhole** [comment]
yea probably I should update the go file linkerdVersion to 2.13 as min version
