### ISSUE TITLE
Output of "arkade get" is too wide for a normal terminal

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#872]
## Expected Behaviour

Rendering without wrapping.

## Current Behaviour

Tiny font / zoomed out:

<img width="1544" alt="Screenshot 2023-03-14 at 08 25 50" src="https://user-images.githubusercontent.com/6358735/224940502-b5b6ae42-14e9-4236-9b65-a623b861b380.png">

Normal-sized font:

<img width="1552" alt="Screenshot 2023-03-14 at 08 25 54" src="https://user-images.githubusercontent.com/6358735/224940518-844a7c28-c0a4-4364-9385-cc99b8438593.png">

## Possible Solution

Don't render the URL when viewing in user mode, keep it for the markdown mode

## Steps to Reproduce (for bugs)

1. `arkade get`

## Context

Looks distracting / hard to read.

```
# arkade version

Version: 0.9.0
```

**Comment by alexellis** [comment]
@Jasstkn thoughts?

**Comment by Jasstkn** [comment]
@alexellis the suggested solution makes sense to me. I can take a look into this today.

**Comment by alexellis** [comment]
Thank you
