### ISSUE TITLE
ark alias conflicts with Ark, the KDE archiving tool

### ISSUE THREAD

**Issue by PierreRustOrange** [alexellis/arkade#88]
## Expected Behaviour
When  arkade is installed, my os basic tools should keep working... ;)

## Current Behaviour
When arkade is installed, it creates a symlink `/usr/local/bin/ark` that override the `ark` utility ( located in `/usr/bin/ark`) which is used to handle all archive file on KDE desktops (tar, bz, etc.). All gui-based operations on these files are then broken (from the file manager, etc.).

## Possible Solution
Avoid creating that alias by default, use a command line argument to create it only when explicitly requested.

**Comment by alexellis** [comment]
Hi @PierreRustOrange would it be useful to you if we have an env-var to suppress the alias?

```
export CREATE_ARKADE_ALIAS=0
```

**Comment by PierreRustOrange** [comment]
Thanks for your answer.

I'd rather have an env-var to create the alias than to suppress it,  it's actually very easy to fix the problem (only need to rm the symlink), the only difficult part is to identify it. It took me some time to understand why I could not open any tar.gz anymore...
Either way, as long as it is mentioned in the doc I'd say it's fine !

**Comment by alexellis** [comment]
What if we checked for ark existing in PATH before creating it? Would that resolve this issue?

**Comment by PierreRustOrange** [comment]
That's a great idea, that would completely resolve the issue and could probably be implemented by simply checking the return form `whereis ark` before creating the symlink.

**Comment by alexellis** [comment]
I know you didn't come here necessary to write a PR, but would you be up for giving it a shot? we use get.sh in this repo.

**Comment by PierreRustOrange** [comment]
You're right, I should have done that before.
The PR is done, my bash is probably a bit rusty, there might be a more efficient way to implement that check but it seems to do the trick.

**Comment by Waterdrips** [comment]
/close
This was implemented in #89 
thanks
