### ISSUE TITLE
Add download for SeaweedFS

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#880]
## Description

SeaweedFS (Apache 2.0) is an alternative for Minio which is now licensed as AGPLv3

17k GitHub Stars, and comes with a static binary for the download:

https://github.com/seaweedfs/seaweedfs/releases

**Comment by alexellis** [comment]
@Jasstkn fancy taking this one up?

**Comment by alexellis** [comment]
How about yourself @nitishkumar71 ?

**Comment by nitishkumar71** [comment]
Thanks. I will work on it.

**Comment by alexellis** [comment]
Sounds good
