### ISSUE TITLE
Add kyverno-cli

### ISSUE THREAD

**Issue by joebowbeer** [alexellis/arkade#890]
Add kyverno-cli for unit testing and applying (aka verifying) kyverno policies in CI/CD or local development.

## Expected Behaviour

```bash
arkade get kyverno
kyverno apply ...
```

## Possible Solution

https://kyverno.io/docs/kyverno-cli/#manual-binary-installation

## Context

For GitOps CI/CD it is useful to unit test changes to policies, and to apply the policies to proposed changes before the changes are merged. (Similar to contest, but for kyverno policies.)

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

kyverno v1.8.5 downloaded 31K times
kyverno v1.9.0 downloaded 25K times

## Your Environment

* What Kubernetes distribution are you using?

EKS 1.25

**Comment by alexellis** [comment]
Hi @joebowbeer are you going to submit a PR for this, or would you like to [sponsor me](https://github.com/sponsors/alexellis) and have me add it for you?

Regards,

Alex
