### ISSUE TITLE
PR: Update kubernetes dashboard & fix account creation

### ISSUE THREAD

**Issue by henry2man** [alexellis/arkade#9]
Kubernetes Dashboard is outdated (current version is 2.0.0-rc2). Also the script fails creating an admin user.

## Expected Behaviour

 `$> k3sup app install kubernetes-dashboard`

* Installs latest kubernetes-dashboard (2.0.0-rc2) and
* hints the user how to create admin user, not creating it directly. According to https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md#creating-sample-user the admin user "_**is for educational purposes only**_"

## Current Behaviour

Kubernetes Dashboard 2.0.0-beta6 is installed (an outdated version)

Also current code the admin account & ClusterRoleBinding are failing with these errors:

```
...
service/dashboard-metrics-scraper unchanged
deployment.apps/dashboard-metrics-scraper configured
error: must specify one of -f and -k
error: must specify one of -f and -k
=======================================================================
= Kubernetes Dashboard has been installed.                                        =
=======================================================================
...
```

If you try to use the token gotten from the outputs from the installation you cannot see anything in the dashboard, having unauthorized errors all the time.

## Possible Solution

I'm gonna create a pull request in order to:

* Update the kubernetes-dashboard url 
* Remove the automatic creation of the admin user 
* Update the script output to instruct the user how to create an admin user

## Steps to Reproduce (for bugs)

1. Install k3sup
2. Install kubernetes-dashboard using "k3sup app install kubernetes-dashboard"

## Context

Cannot use the installed kubernetes-dashboard , that's all.

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33Kubernetes Dashboard 2.0.0-beta6 is installed (an outdated version)

871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

k3sup install & join on a pair of Ubuntu Server 19.10 fresh nodes

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

Linux mypc 5.3.0-26-generic alexellis/k3sup#28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

```

**Comment by Shikachuu** [comment]
I'll close this, since it is seems a bit outdated, there were so much issue about the dashboard and even a new one came in (#713 ).

We'll update/refactor the dasboard soon.
