### ISSUE TITLE
Add kube-burner

### ISSUE THREAD

**Issue by tuxtof** [alexellis/arkade#901]
## Expected Behaviour

i would like to make a PR to add kube-burner (https://github.com/cloud-bulldozer/kube-burner)

Kube-burner is a tool aimed at stressing kubernetes clusters.

If approved, are you willing to submit a pull request for this?

YES

**Comment by tuxtof** [comment]
@alexellis I'm waiting for your green light to push a a PR

**Comment by alexellis** [comment]
Hey @tuxtof 

I appreciate the keenness.

Please go ahead and submit a PR, but make sure it follows the template and changes of an existing one so we can keep the feedback loop nice and tight.

Here's a good one:

https://github.com/alexellis/arkade/pull/917

And if you <3 arkade, please become a sponsor. Personal sponsors don't contribute much, but it all adds up to support me creating time for this project. 

Alex
