### ISSUE TITLE
Add openshift-install

### ISSUE THREAD

**Issue by tuxtof** [alexellis/arkade#902]
## Expected Behaviour
i would like to make a PR to add openshift-install tools (https://github.com/openshift/installer)

If approved, are you willing to submit a pull request for this?

YES

**Comment by tuxtof** [comment]
@alexellis I'm waiting for your green light to push a a PR

**Comment by alexellis** [comment]
Hey @tuxtof 

Is this something you can use?

I'm seeing something like a bug right now - with two downloads, then only one and no way to differentiate OSes and arches?

![image](https://github.com/alexellis/arkade/assets/6358735/06bd20c7-7581-4b3d-bd6a-30539e471cda)

Thoughts?

Alex

**Comment by tuxtof** [comment]
i have some idea ;-) let me make the PR and share it with you for discution
