### ISSUE TITLE
Add atuin for synchronising bash history

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#903]
## App

Add atuin for synchronising bash history

https://github.com/ellie/atuin/releases

It has a static binary available for x86 Linux and Darwin.

https://atuin.sh/blog/release-v13

**Comment by alexellis** [comment]
@ellie would you like to work on this?

Or perhaps @Jasstkn if she has time?

**Comment by ellie** [comment]
Sure! I'd be happy to work on this sometime in the next week

**Comment by alexellis** [comment]
Thanks @ellie 

Here's a sample PR including the testing done etc that is easy to merge: https://github.com/alexellis/arkade/pull/917
