### ISSUE TITLE
Adding new clis: buildctl, buildkitd and copa

### ISSUE THREAD

**Issue by derdanne** [alexellis/arkade#904]
I would like to add the clis buildctl, buildkitd and copa

## Expected Behaviour
Downlaod of these clis is working with:
`arkade get buildctl`
`arkade get buildkitd`
`arkade get copa`

## Current Behaviour
Arkade does not know these clis

## Possible Solution
I would like to create a PR for adding these clis

## Context

For container image building and updating i would like to have [buildctl, buildkitd](https://github.com/moby/buildkit) and copa (https://github.com/project-copacetic/copacetic) available

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

buildctl/buildkitd: 21,817
Copa: 404 (will definitely raise in the future)

If approved, are you willing to submit a pull request for this?

YES

**Comment by alexellis** [comment]
Hi @derdanne please go ahead and add buildctl via arkade get

For buildkitd - there are a bunch of binaries so we're doing it via a system installer in #910

**Comment by alexellis** [comment]
For `copa` please send a separate PR for `arkade get`

If you follow this pattern, including the testing steps then we should be able to get your PRs merged quite quickly and painlessly

https://github.com/alexellis/arkade/pull/888
