### ISSUE TITLE
Add task binary and 1password to arkade get

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#909]
## Description

Add task binary and 1password to arkade get

For @roderik

1Password URL:

https://github.com/settlemint/setup-op/blob/main/lib/utils.js#L25

Task binary:

https://github.com/go-task/task/releases

(Need to get the tar.gz file)

**Comment by alexellis** [comment]
@bxffour want to take this one instead? It would help out @roderik

**Comment by bxffour** [comment]
> @bxffour want to take this one instead? It would help out @roderik

Yeah, already working on it
