### ISSUE TITLE
Failures in multi user envronments

### ISSUE THREAD

**Issue by roderik** [alexellis/arkade#911]
## Expected Behaviour

A different user has run arkade to install yq, now this user wants to do it, and it fails because the temp download file is not permissioned correctly

<img width="541" alt="CleanShot 2023-05-21 at 08 16 29@2x" src="https://github.com/alexellis/arkade/assets/16780/7dc19bf0-52fe-404c-8db8-de6f04a4f4d5">

**Comment by nitishkumar71** [comment]
I did it on my local and one of the multipass virtual instance. It worked for me. Don't think it has anything to do with `arkade`. As per logs this is mostly permission issue for `/tmp` folder.

```
Downloading: yq
2023/05/21 17:19:59 Looking up version for yq
2023/05/21 17:20:00 Found: v4.33.3
Downloading: https://github.com/mikefarah/yq/releases/download/v4.33.3/yq_linux_amd64
8.43 MiB / 8.43 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/yq_linux_amd64 written.
2023/05/21 17:20:02 Looking up version for yq
2023/05/21 17:20:02 Found: v4.33.3
2023/05/21 17:20:02 Copying /tmp/yq_linux_amd64 to /home/ubuntu/.arkade/bin/yq

Wrote: /home/ubuntu/.arkade/bin/yq (8.839MB)

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/ubuntu/.arkade/bin/yq

# Or install with:
sudo mv /home/ubuntu/.arkade/bin/yq /usr/local/bin/

🐳 arkade needs your support: https://github.com/sponsors/alexellis
```

**Comment by NikhilSharmaWe** [comment]
It works for me too.

**Comment by roderik** [comment]
Yeah, i was not clear

```
sudo su - user1
arcade get yq  <-- works
exit
sudo su - user2
arcade get yq <- permission error on the tmp dl file as it is owned by user1
``

**Comment by nitishkumar71** [comment]
I think then we can close this issue, as nothing to do with arkade

**Comment by roderik** [comment]
But it is arkade that is doing this?

arkade downloads the download file to temp, it should either:

- delete it after it is done
- chmod the file so everyone can access it
- make a random temporary dir inside of /tmp to download  <- this is the best option as it also allows for concurrent installs

**Comment by alexellis** [comment]
Thanks everyone for the input and discussion.

@roderik if you could edit the issue template and add full repro instructions that'd help here => https://raw.githubusercontent.com/alexellis/arkade/master/.github/ISSUE_TEMPLATE.md

If `--stash` isn't being run, then we can delete any temporary files. This may be harder to do when we're untar-ing / unzipping an archive.

@nitishkumar71 @NikhilSharmaWe - perhaps we could use [os#MkdirTemp](https://pkg.go.dev/os#MkdirTemp) instead of just writing the files into the temp dir?

In this way, we'll not clash with other users.

**Comment by alexellis** [comment]
I opened this PR to address the above - https://github.com/alexellis/arkade/pull/914
