### ISSUE TITLE
Repository Move from stedolan/jq to jqlang/jq.  301 received and not followed

### ISSUE THREAD

**Issue by f-leclere** [alexellis/arkade#918]
Jq repository is moving from stedolan/jq to jqlang/jq and a redirection is implemented by stedolan

https://github.com/jqlang/jq/issues/2594

## Current Behaviour
ark get jq receive a 301 on jq releases listing and can't follow it.

## Expected Behaviour
Update ark jq repository link

# Possible Solution
alert and follow 301 with a new follow-redirect ark option

## Context
docker image

```
arkade version
```
0.9.18

**Comment by alexellis** [comment]
Hi @f-leclere 

Would you like to update the Tool definition and its unit tests to the new location?

If you're not in a position to contribute and test the change, no worries, just let me know and we'll find someone else.

cc @nitishkumar71 @NikhilSharmaWe 

Thanks,

Alex

**Comment by f-leclere** [comment]
Hi @alexellis 
Sorry, I'm not in position currently to contribute to fix this.
Thanks,
François

**Comment by NikhilSharmaWe** [comment]
@alexellis I would like to work on this.

I will ping you once the PR is ready.

**Comment by Obsecurus** [comment]
sorry, didn't mean to beat you to it 🤦🏼

**Comment by Obsecurus** [comment]
> Hi @alexellis Sorry, I'm not in position currently to contribute to fix this. Thanks, François

sorry, didn't mean to beat you to it 🤦🏼, see https://github.com/alexellis/arkade/pull/919

**Comment by alexellis** [comment]
No problems @f-leclere thanks for your interest in arkade.

Thanks for the PR @Obsecurus - I've replied on the there already.

I'd welcome anyone who uses or finds the tool useful to set up a sponsorship via GitHub to support the development of arkade. Most developers don't/won't which is of course a shame, but I wanted to make you aware that we are looking for support.

Alex
