### ISSUE TITLE
"arkade install" fails on Win (Git Bash) due to helm download URL guess?

### ISSUE THREAD

**Issue by mkol5222** [alexellis/arkade#92]
Hello, I am using arkade on Win10 in Git Bash installed via "choco install git"

WHAT FAILS
arkade install fails because trying to get helm from
https://get.helm.sh/helm-v3.1.1-mingw64_nt-10.0-18362-amd64.tar.gz

REPLICATION
```
$ uname -a
MINGW64_NT-10.0-18362 username-7480 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys

$ arkade install mongodb
Using kubeconfig: C:\Users\username/.kube/config
Node architecture: "amd64"
Client: "x86_64", "MINGW64_NT-10.0-18362"
2020/04/13 10:16:15 User dir established as: C:\Users\username/.arkade/
https://get.helm.sh/helm-v3.1.1-mingw64_nt-10.0-18362-amd64.tar.gz
2020/04/13 10:16:16 error extracting tarball into C:\Users\username/.arkade/bin/helm3 after 0 files, 0 dirs, 0s: requires gzip-compressed body: gzip: invalid header
Error: unable to add repo exec: "C:\\Users\\username/.arkade/bin/helm3/helm": file does not exist
```

Am I using wrong distro of Git Bash or startegy to guess helm download URL is not complete? (uname -a abobe)

Thank you

**Comment by mkol5222** [comment]
manual fix was:
- download helm from
```
curl -OL https://get.helm.sh/helm-v3.1.2-windows-amd64.tar.gz
```

- extract and copy helm.exe
```
tar xzvf helm-v3.1.2-windows-amd64.tar.gz
mv windows-amd64/helm.exe ~/.arkade/bin/helm3/
```

- testing some arkade install then worked for me
```
arkade install mongodb
```

**Comment by alexellis** [comment]
Hi "mkol5222"

Thanks for logging this issue. We should be able to resolve the auto-download of helm on Windows. I'll ping you when there's something to test. 

Alex

**Comment by alexellis** [comment]
PR #93 fixes this issue, you'll be able to test the new binary release when it's published via https://github.com/alexellis/arkade/releases/tag/0.2.6

To test simply `arkade upgrade`, then `rm -rf ~/.arkade` before running `arkade install` again with an app that uses helm3.

**Comment by mkol5222** [comment]
Many thanks for amazingly fast fix delivery. I was starting our new lab and it got latest arkade release that was able to fetch helm and all was working fine and smooth even on Win10 inside Git Bash.

**Comment by alexellis** [comment]
Tell me about what you're using arkade for? We have a Slack community with a general and contributors channel inside OpenFaaS slack https://slack.openfaas.io
