### ISSUE TITLE
Add charm/vhs to arkade get

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#927]
## Description

Add charm/vhs to arkade get

11.1k Stars

It's a CLI for recording demos... 

We should try it out and record a demo to host in the arkade README

https://github.com/charmbracelet/vhs/releases

https://github.com/charmbracelet/vhs/

**Comment by alexellis** [comment]
Example PR: https://github.com/alexellis/arkade/pull/928

**Comment by alexellis** [comment]
Sorry @bxffour looks like @NikhilSharmaWe got there before you!

I'd still like a video / ".tape" file for arkade so we can have it high up in the repository showing off some of the commands.

Alex

**Comment by bxffour** [comment]
> Sorry @bxffour looks like @NikhilSharmaWe got there before you!
> 
> I'd still like a video / ".tape" file for arkade so we can have it high up in the repository showing off some of the commands.
> 
> Alex

Here's a draft demo for arcade. Let me know what you think.

[arcade](https://vhs.charm.sh/vhs-VdggENURynyXu8AfTCGgv.gif)

Nana

**Comment by alexellis** [comment]
I like it a lot @bxffour 

Just captialise the start of each line.

And I wonder if you can write:

` # Download a specific version of a CLI`

rather than `echo etc... `

Does that still work? 

We should also show an example of getting > 1 tool - i.e. `arkade get kubectl helm`

Now that you have a demo file, can you just edit that by hand?

One more thing - there should be some output at the last step since this loops - to show that we've come to the end of the demo.

**Comment by bxffour** [comment]
> I like it a lot @bxffour
> 
> Just captialise the start of each line.
> 
> And I wonder if you can write:
> 
> ` # Download a specific version of a CLI`
> 
> rather than `echo etc... `
> 
> Does that still work?
> 
> We should also show an example of getting > 1 tool - i.e. `arkade get kubectl helm`
> 
> Now that you have a demo file, can you just edit that by hand?
> 
> One more thing - there should be some output at the last step since this loops - to show that we've come to the end of the demo.

Sorry this took a while. I couldn't get to it on time. Here's a version with your suggested changes 

![arkade_gif](https://vhs.charm.sh/vhs-5EneeBFtKbabiVe3bbUMWK.gif)

**Comment by alexellis** [comment]
To me that looks a lot smoother. Thank you :+1: 

Could you send a PR with this to the README?

How large is the gif file?

**Comment by alexellis** [comment]
I think we can trim out the OS/arch override since the auto-detection is the usual way to use the tool. We only have that for e2e testing.

**Comment by bxffour** [comment]
> To me that looks a lot smoother. Thank you +1
> 
> Could you send a PR with this to the README?
> 
> How large is the gif file?

Alright. I would.
The file size is around 2.5mb
