### ISSUE TITLE
Do not fail PostgreSQL install on arm64

### ISSUE THREAD

**Issue by joebowbeer** [alexellis/arkade#942]
Bitnami postgresql chart now supports arm64:

https://hub.docker.com/r/bitnami/postgresql/tags

## Expected Behaviour
`arkade install postgresql` succeeds on k8s with arm64 nodes

## Current Behaviour
`arkade install postgresql` fails on k8s with arm64 nodes

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Create cluster on MacBook Pro w/M1 chip
2. arkade install postgresql

**Comment by alexellis** [comment]
Commented here - https://github.com/alexellis/arkade/pull/943#issuecomment-1604107945

Thanks for sending this.
