### ISSUE TITLE
Add etcdctl

### ISSUE THREAD

**Issue by klutchell** [alexellis/arkade#945]
## Expected Behaviour

etcdctl provides a CLI for interacting with etcd servers. K3s does not bundle etcdctl.

## Current Behaviour

```
Error: tool etcd not found
Error: tool etcdctl not found
```

## Possible Solution

From https://docs.k3s.io/advanced#using-etcdctl and https://etcd.io/docs/v3.5/install/

```
ETCD_VERSION="v3.5.5"
ETCD_URL="https://github.com/etcd-io/etcd/releases/download/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-amd64.tar.gz"
curl -sL ${ETCD_URL} | sudo tar -zxv --strip-components=1 -C /usr/local/bin
```

## Steps to Reproduce (for bugs)

n/a

## If requesting a CLI for "arkade get"

* How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/?username=etcd-io&repository=etcd

68,166

* If approved, are you willing to submit a pull request for this?

Of course, when I get chance

## Your Environment

[k3s in Docker](https://docs.k3s.io/advanced#running-k3s-in-docker)

```
kubectl version
v1.24.2
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux 6c410f9 5.15.62-yocto-standard #1 SMP PREEMPT Mon Aug 22 15:16:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?

```
0.9.22
```

**Comment by alexellis** [comment]
Hi @klutchell 

> If approved, are you willing to submit a pull request for this?
> Of course, when I get chance

Cool, we'll hang on until you have time :+1:
