### ISSUE TITLE
Fix required for kubestr and k0s

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#961]
A fix is required for kubestr and k0s which have made breaking changes to their download URLs meaning the e2e tests are now failing.

## Expected Behaviour

`make e2e` should pass

## Current Behaviour

<img width="1470" alt="Screenshot 2023-07-25 at 14 44 47" src="https://github.com/alexellis/arkade/assets/6358735/11d5e36c-d083-4ac6-89f8-80de698b6965">

## Possible Solution

First confirm the issue with `arkade get k0s` etc

Then:

* Check the releases pages of each too
* Copy the URL for a binary
* Edit the template with the new URL format
* Run the unit tests

Finally, run `go build && ./arkade get k0s` and it should be fixed.

Do the same for kubestr and then send a PR.

**Comment by mkimberley** [comment]
I can pick this up?

**Comment by alexellis** [comment]
Sorry the e2e tests need fixing immediately, I'll take it.
