### ISSUE TITLE
e2e tests failing for atuin

### ISSUE THREAD

**Issue by mkimberley** [alexellis/arkade#962]
## Expected Behaviour
- make e2e should report all tests passed when building arkade

## Current Behaviour
- make e2e fails on "Test_CheckTools/Download_of_atuin"

## Possible Solution
- Correct the URL location for the atuin tool

## Steps to Reproduce (for bugs)
- clone arkade
-  make e2e

## Context

- This issue stops all PRs from pasisng, as global tests are failing

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

If approved, are you willing to submit a pull request for this?

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

failing at git commit 6f5d90ec728cbf9a34249cedb0009d30021266f4

**Comment by alexellis** [comment]
Thanks for raising this. And by the way Atuin seems to have arm binaries now if you wanted to send a PR to add them?

**Comment by mkimberley** [comment]
Ah awesome! I'll do that tomorrow and get a PR in. Btw, I didn't get your email last week (not at this address at least).Glad I could help! I'll raise two PRs, one for the ARM binaries and another for kubestr tomorrow On 31 Jul 2023 19:12, Alex Ellis ***@***.***> wrote:
Thanks for raising this. And by the way Atuin seems to have arm binaries now if you wanted to send a PR to add them?

**Comment by mkimberley** [comment]
I'll get a PR submitted!

**Comment by alexellis** [comment]
Is this still something you're taking care of @mkimberley ?
