### ISSUE TITLE
failed to download k9s in Windows Git Bash

### ISSUE THREAD

**Issue by jizusun** [alexellis/arkade#968]
## Expected Behaviour

arkade should download `k9s` at <https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Windows_amd64.zip> 
According to <https://github.com/derailed/k9s/releases/tag/v0.27.4>

## Current Behaviour

```
$ ark get k9s
Downloading: k9s
2023/08/19 01:45:25 Looking up version for k9s
2023/08/19 01:45:26 Found: v0.27.4
Downloading: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Windows_amd64.tar.gz

The requested version of k9s is not available or configured in arkade for MINGW64_NT-10.0-22621/x86_64

* Check if a binary is available from the project for your Operating System
* View the k9s releases page: https://github.com/derailed/k9s/releases
* Feel free to raise an issue at https://github.com/alexellis/arkade/issues for help

```

## Steps to Reproduce (for bugs)

1. Install `arkade` on Windows 
2. `ark get k9s`

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

Windows 11

* What arkade version is this?

```
$ ark version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Open Source Marketplace For Developer Tools

Version: 0.9.23
Git Commit: 3a36fb5e13bcb6455e000d3e06bcfd998e9895ef
```

**Comment by alexellis** [comment]
Hi @jizusun / @tuxtof / @Jasstkn do you want to send a PR for this?

**Comment by alexellis** [comment]
Thanks for raising this.

Seems like the extension is now .zip, or perhaps was wrongly added as .tar.gz in the past.

I've made a fix which you'll be able to test shortly:

https://github.com/alexellis/arkade/releases/tag/0.10.6
Alex

**Comment by tuxtof** [comment]
@alexellis You were the fastest 🥇
