### ISSUE TITLE
 Can't install software with Arkade, getting file not found error for .arkade/bin/helm  even though file exists 

### ISSUE THREAD

**Issue by MarkhamLee** [alexellis/arkade#978]
I'm getting the following error when trying to install software with Arkade:
Error: fork/exec /home/markham/.arkade/bin/helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/ --force-update: no such file or directory - however, the directory and the helm file do in fact exist. using the command "cd /home/markham/.arkade/bin/" takes you right to that directory and the helm file is present. 

## Expected Behaviour
Arkade installs the software without any issue. 

## Current Behaviour

I get an error message stating that  /home/markham/.arkade/bin/helm doesn't exist, when it in fact does. 

## Steps to Reproduce (for bugs)

1. Install k3sup on local machine
2. Install k3sup on server 
3. Attempt to install software via Arkade using the command arkade install kubernetes-dashboard 
4.

## Context

The plan was to use Arkade to get around some of the usual headaches with installing/configuring via yaml files, if I can't get Arkade to work I would probably try reinstalling the server OS and trying again from scratch or just install things the usual way via yaml files and the like. 

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

If approved, are you willing to submit a pull request for this?

## Your Environment

* What Kubernetes distribution are you using?
k3s 
```
kubectl version
```Shows 1.24 for client even though this is a fairly new machine and a recent install 

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 22.04.3 LTS x86
```
uname -a

cat /etc/os-release
```6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux


* What arkade version is this?

```
arkade version
```
Version: 0.10.10
Git Commit: 8f028584fc537ec79e0e1f70d7299ca5107765a8

**Comment by MarkhamLee** [comment]
For kubectl I intentionally installed the latest and it still shows 1.24

**Comment by alexellis** [comment]
Thanks for the issue. This is related to us fixing the way we start programs so that Arkade can work on Windows where people have a space in their home directory.

https://github.com/alexellis/arkade/issues/977

We have to make an update to split out:

```
	task := execute.ExecTask{
		Command:     fmt.Sprintf("%s repo add %s %s --force-update", env.LocalBinary("helm", subdir), name, url),

```

To use Command and Args separately.

For now Mark, use an older version of Arkade, or hang around and we should have this fixed shortly.

Alex

**Comment by alexellis** [comment]
@MarkhamLee see - https://github.com/alexellis/arkade/releases/tag/0.10.11 `arkade update` should download it for you

**Comment by MarkhamLee** [comment]
The update worked just fine, thank you.
