### ISSUE TITLE
Error installing Grafana

### ISSUE THREAD

**Issue by tomtom215** [alexellis/arkade#98]
## Expected Behaviour

Install Grafana

## Current Behaviour

Installation fails

## Possible Solution

Verifying the 'stable' repo for grafana

## Steps to Reproduce (for bugs)

1. install arkade
2. run 'arkade install grafana'

## Your Environment

* What Kubernetes distribution are you using?
```
k3s 1.17.2
```
```
kubectl version
1.18
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
cat /etc/os-release
VERSION="18.04.4 LTS (Bionic Beaver)"
```

* What arkade version is this?

```
arkade version
0.2.8
```

**Comment by alexellis** [comment]
Sorry I am going to need more information than that to be able to help.

Can you paste the whole console output please?

**Comment by alexellis** [comment]
cc @aidun @Amalkh5

**Comment by aidun** [comment]
I tried to verify this behavior. With arkade@master and k3d@1.17.4 the install process works fine. @tomtom215 if you can provide more information, I can look a bit more specific.

**Comment by Amalkh5** [comment]
I did get the same error `Error: repo stable not found` with arkade@0.2.8 and k8s@1.18.0.
``` 
$ arkade install grafana
2020/04/15 21:24:13 Client: x86_64, Darwin
2020/04/15 21:24:13 User dir established as: /Users/amal/.arkade/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "inlets" chart repository
Update Complete. ⎈ Happy Helming!⎈
Error: repo stable not found
Error: exit code 1 ```

**Comment by aidun** [comment]
😅 addHelmRepo is missing in the Code. I thought Helm has always a stable repo 🤔

**Comment by alexellis** [comment]
Not with helm 3. Who authored this app? We just need the add statement, should be present in the nginx-ingress app or similar.

**Comment by tomtom215** [comment]
> I did get the same error `Error: repo stable not found` with arkade@0.2.8 and k8s@1.18.0.
> 
> ```
> $ arkade install grafana
> 2020/04/15 21:24:13 Client: x86_64, Darwin
> 2020/04/15 21:24:13 User dir established as: /Users/amal/.arkade/
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "inlets" chart repository
> Update Complete. ⎈ Happy Helming!⎈
> Error: repo stable not found
> Error: exit code 1 ```
> ```

Apologies for the initial lack of details (dinner was ready). @Amalkh5  this is the same error I saw

> arkade install grafana
2020/04/15 19:42:50 Client: x86_64, Linux
2020/04/15 19:42:50 User dir established as: /home/tom/.arkade/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "openfaas" chart repository
Update Complete. ⎈ Happy Helming!⎈
Error: repo stable not found
Error: exit code 1

**Comment by aidun** [comment]
@alexellis I can fix it. Should be no problem.

**Comment by alexellis** [comment]
Thanks @aidun

**Comment by aidun** [comment]
PR is ready, tested with k3d and removed stable repo before testing.
