### ISSUE TITLE
Add rclone as a tool

### ISSUE THREAD

**Issue by code0x9** [alexellis/arkade#989]
## If requesting a CLI for "arkade get"

https://rclone.org/

- How many downloads does this tool have? Check at: 

309,767

https://somsubhra.github.io/github-release-stats/?username=rclone&repository=rclone&page=1&per_page=5

- If approved, are you willing to submit a pull request for this?

yes

## Your Environment

* What Kubernetes distribution are you using?

```
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.2
```

* Operating System and version (e.g. Linux, Windows, MacOS):

MacOS

* What arkade version is this?

```
            _             _
  __ _ _ __| | ____ _  __| | ___
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Open Source Marketplace For Developer Tools

Version: 0.10.13
Git Commit: 9c9b29c1e97c4a893a652e2c594a84e8001e6885

 🚀 Speed up GitHub Actions/GitLab CI + reduce costs: https://actuated.dev
```

**Comment by alexellis** [comment]
Thanks for the suggestion. Do you have a link to the release page on GitHub?

**Comment by code0x9** [comment]
here it is: https://github.com/rclone/rclone/releases
